### ISSUE TITLE
Newsletter 33 - April 2022

### ISSUE THREAD

**Issue by AngelOnFira** [rust-gamedev/rust-gamedev.github.io#1010]
# Newsletter 33: April 2022

###### tags: `newsletter`

**Editors:** @AngelOnFira, @17cupsofcoffee and @ozkriff 

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with April's news!

## Current Schedule

**The deadline for all section PRs is 8th April.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Rust Gamedev Meetup

- [ ] Details of this month's meetup - 🚧 WIP by @AngelOnFira

#### Rust Graphics Meetup

- [ ] Call for Presenters - 🆓 **free** 🚧 WIP by @AngelOnFira

#### Game Updates

- [x] Way of Rhea - ✔️ done by @MasonRemaley
- [ ] Veloren - 🚧 WIP by @AngelOnFira 
- [ ] Bitgun ([1](https://store.steampowered.com/app/1673940/BITGUN/), [2](https://www.reddit.com/r/rust/comments/uepde7/after_working_on_our_godot_rust_game_fulltime_for/)) - 🚧 WIP by @shosanna
- [ ] Last of the Sky Folk ([1](https://ianjk.com/ld50/), [2](https://github.com/kettle11/LD50)) - 🆓 **free** (@kettle11?)
- [ ] Melbourne Lockdown Simulator ([1](https://github.com/drobgrog/melsim)) - 🆓 **free** (@kanerogers?)
- [ ] heute-nicht ([1](https://www.reddit.com/r/rust_gamedev/comments/twwboj/made_a_3d_game_using_bevy_for_ludum_dare_and_its/), [2](https://eira-hx.itch.io/heute-nicht)) - 🆓 **free**
- [ ] Oasis of Lost Hope ([1](https://www.reddit.com/r/rust_gamedev/comments/txuowi/our_opensource_ld50_entry_made_with_godot_rust/)) - 🆓 **free** (@setzer22, @Bromeon?)
- [ ] Extremely Extreme Sports ([1](https://www.reddit.com/r/rust_gamedev/comments/u9zqrc/scored_top_3_in_fun_with_my_ludum_dare_game/), [2](https://kuviman.itch.io/ld50/devlog/372532/extremely-extreme-sports-postmortem)) - 🆓 **free** (@kuviman?)

#### Learning Material Updates

- [ ] Game Development with Rust and WebAssembly ([1](https://www.amazon.com/Game-Development-Rust-WebAssembly-building/dp/1801070970/)) - 🚧 WIP by @paytonrules
- [ ] Why I choose to build my game from scratch ([1](https://www.reddit.com/r/rust_gamedev/comments/uewu9h/reasons_why_i_choose_to_build_my_game_from/)) - 🚧 WIP by @HeavyRain266
- [ ] Brontefy Me # 2 ([1](https://www.youtube.com/watch?v=tx31BKX0yIA), [2](https://github.com/hedgein/BrontefyMe_Week2)) - 🆓 **free** (@hedgein?)
- [ ] Bevy engine tutorial series ([1](https://www.reddit.com/r/rust_gamedev/comments/tz75eb/bevy_game_engine_tutorial_series/)) - 🆓 **free** (@PhaestusFox?)
- [ ] Bevy 0.6 to 0.7 upgrade guide ([1](https://www.reddit.com/r/rust_gamedev/comments/u4uhs2/bevy_06_to_07_migration_guide/)) - 🆓 **free** (@PhaestusFox?)
- [ ] Rust multi-threading code review ([1](https://www.reddit.com/r/rust_gamedev/comments/twzp70/rust_multithreading_code_review/)) - 🆓 **free** (@TanTanDev?)

#### Engine Updates

- [x] Bevy 0.7 ([1](https://www.reddit.com/r/rust/comments/u4e63h/bevy_07/)) - ✔️ done by @Cart
- [x] DIMS ([1](https://www.reddit.com/r/rust_gamedev/comments/tuj9dg/far_from_finished_but_heres_our_terrain_tool/)) - ✔️ done by @FredrikNoren
- [ ] Hotham VR Engine demo - 🚧 WIP by @kanerogers
- [ ] Eldiron ([1](https://eldiron.com/), [2](https://github.com/markusmoenig/Eldiron)) - 🚧 WIP by @markusmoenig
- [ ] Fyrox - 🆓 **free** (@mrDIMAS?)

#### Tooling Updates

- [x] Vismut ([1](https://gitlab.com/vismut-org/vismut/-/releases/v0.5.0)) - ✔️ done by @lukors
- [ ] Noumenal ([1](https://noumenal.app/)) - 🚧 WIP by @HackerFoo
- [ ] Graphite - **free** (@keavon?)

#### Library Updates

- [ ] SuInput ([1](https://sorenon.github.io/Action-System/), [2](https://github.com/Sorenon/Action-System/)) - 🆓 **free** (@Sorenon?)
- [ ] tween ([1](https://github.com/sanbox-irl/tween)) - 🆓 **free** (@sanbox-irl?)
- [ ] cosync ([1](https://github.com/sanbox-irl/cosync)) - 🆓 **free** (@sanbox-irl?)
- [ ] Bevy Blender ([1](https://www.reddit.com/r/rust_gamedev/comments/u7acfc/update_on_bevy_blender_releasing_v02_and_inquiry/)) - 🆓 **free** (@jeraldamo?)
- [ ] Notan ([1](https://www.reddit.com/r/rust_gamedev/comments/uelubi/notan_has_now_audio_support_using_oddio_symphonia/)) - 🆓 **free** (@Nazariglez)

#### Other News

- [ ] Bullet points of any interesting news that doesn't have its own section - 🚧 WIP by @ozkriff

#### Discussions

- [ ] Simulating less powerful machines ([1](https://www.reddit.com/r/rust_gamedev/comments/ub4jq0/simulating_less_powerful_machines_for_benchmarking/)) - 🆓 **free**

#### Jobs

- [ ] Project Name (1) - 🆓 **free** (@AngelOnFira?)
    
## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @AngelOnFira
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @AngelOnFira
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @AngelOnFira
- [ ] Add a draft of next month's newsletter - by @AngelOnFira

**Comment by HackerFoo** [comment]
I would like to work on the section on Noumenal. Thanks.

**Comment by kanerogers** [comment]
I can do a section on engine updates for Hotham! 😀

**Comment by paytonrules** [comment]
I'd like to add a reference to a new book [Game Development with Rust and WebAssembly](https://amzn.to/3vTk9gh) to the learning materials. I wrote it so if that's inappropriate I won't.

**Comment by markusmoenig** [comment]
I will do the Eldiron section, thanks!

**Comment by AngelOnFira** [comment]
@paytonrules it should be fine :)

**Comment by HeavyRain266** [comment]
I would like to work on section with "Why I choose to build my game from scratch" since it's my own post.

**Comment by lukors** [comment]
I'll do Vismut, and the github username for it is me. :)

**Comment by cart** [comment]
Just grabbed Bevy 0.7

**Comment by shosanna** [comment]
Hey, I will write about BITGUN as we just released the game! :)

**Comment by FredrikNoren** [comment]
Just added a PR for Dims

**Comment by paytonrules** [comment]
Thanks! PR is opened.

**Comment by Nazariglez** [comment]
Added PR for Notan, thanks!

**Comment by AngelOnFira** [comment]
@kettle11 @kanerogers @setzer22 @kuviman @hedgein @PhaestusFox @HackerFoo
@Keavon @Sorenon @sanbox-irl @Nazariglez

Just sending out a ping to remind that today is the deadline for sections of the blog :)

**Comment by Nazariglez** [comment]
Hey! Notan is already merged #1020, I cannot change the checklist. Thanks for the ping!

**Comment by Bromeon** [comment]
Added short entry about our LD50 game: #1022.
Sorry for the last-minute submission!

**Comment by HackerFoo** [comment]
I don't have much to announce for Noumenal, so I'm going to hold off until next month. Thanks.

**Comment by cdsupina** [comment]
If it's there is still time I would like to mention my RustConf arcade cabinet project in this newsletter to get the word out.
https://twitter.com/carlosupina/status/1523715837726961664

**Comment by kanerogers** [comment]
@AngelOnFira Done! My first time doing this sort of thing, hope I didn't muck it up:

 https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1025

**Comment by 17cupsofcoffee** [comment]
> I was going to put this in "Other News", but it looks like that is just for one single line news. Is there a good place in the newsletter to talk about a arcade cabinet?

@cdsupina: Tricky one 😆 I'd probably put it under game updates,

**Comment by AngelOnFira** [comment]
My current plans are to spend a decent amount of tomorrow morning finalizing the existing PRs, and writing a few sections that haven't been covered yet. Expect a final review :)

**Comment by Keavon** [comment]
Is there somewhere we could add the new [blog post](https://graphite.rs/blog/distributed-computing-in-the-graphene-runtime/) for Graphite that we posted today? I've maxed out the word count in the section. But maybe there's a relevant list near the bottom (perhaps described as seeking comments about the blog post in the "Discussions" section?).

**Comment by ozkriff** [comment]
@Keavon since it was released today and doesn't seem to focus on April updates only, I guess it's better to include it in the May newsletter issue?

**Comment by ozkriff** [comment]
Taking the "Other News" section to help out with the newsletter completion

**Comment by Keavon** [comment]
> @Keavon since it was released today and doesn't seem to focus on April updates only, I guess it's better to include it in the May newsletter issue?

I wouldn't be opposed to waiting a month if we're sticking to the month designation. (I sort of assumed it was "most of April through early May" and abbreviated to the "April newsletter".)

**Comment by ozkriff** [comment]
The original idea was that the coordination issue should be created around 27th and the release should happen on 1st..3rd. But in practice, the dates keep slipping. I'd like to better stick to month boundaries too - I'll be the releasing editor next month and will try my best about it.

**Comment by AngelOnFira** [comment]
The final review is up for anyone that wants to look it over :tada: 

https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1029
