### ISSUE TITLE
Newsletter 34 - May 2022 

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#1033]
# Newsletter 34: May 2022

###### tags: `newsletter`

**Editors:** @ozkriff, @17cupsofcoffee, and @AngelOnFira

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with May's news!

## Current Schedule

**The deadline for all section PRs is 2022.05.31.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Announcements

- [x] rust gamedev meetup - ✔️ done by @AngelOnFira
- [x] rust grphics meetup 2 - ✔️ done by @AngelOnFira
- [x] 3D Ferris ([1](https://twitter.com/Ray__March/status/1512907700740444163), [2](https://twitter.com/Ray__March/status/1523717266730151936)) - ✔️ done by @RayMarch
- [x] Arcade Cabinet - ✔️ done by @cdsupina

#### Game Updates

- [x] Country Slice ([1](https://twitter.com/anastasiaopara/status/1520680553640599554), [2](https://twitter.com/anastasiaopara/status/1530473522224582656)) - ✔️ done by @anopara
- [x] limbo_pass ([1](https://github.com/shnewto/limbo_pass), [2](https://twitter.com/shnewto/status/1520897809968340992)) - ✔️ done by @shnewto
- [x] Rusty Doom ([1](https://github.com/flukejones/room), [2](https://twitter.com/flukejones/status/1521799760013033472), [3](https://twitter.com/flukejones/status/1522902155027714048), [4](https://twitter.com/flukejones/status/1525982340689715201)) - ✔️ done by @flukejones
- [x] Veloren ([1](https://veloren.net)) - ✔️ done by @AngelOnFira
- [x] ~~BITGUN ([1](https://twitter.com/LogLogGames/status/1522368279058292739)) - 🆓 **free** (@shosanna?)~~
- [x] ~~Gravity Well ([1](https://github.com/thebracket/gravity_well), [2](https://twitter.com/herberticus/status/1522575691614670848), [3](https://twitter.com/herberticus/status/1522585670983860224)) - 🆓 **free** (@thebracket?)~~
- [x] ~~Flesh ([1](https://twitter.com/Im_Oab/status/1523210359045206017), [2](https://twitter.com/Im_Oab/status/1525249464562491393), [3](https://twitter.com/Im_Oab/status/1529400914364465153)) - 🆓 **free** (@Im-Oab?)~~
- [x] Hug ([1](https://github.com/Hihaheho/Hug), [2](https://hug.hihaheho.com/)) - ✔️ done by @ozkriff
- [x] Battleship ([1](https://github.com/orhun/battleship-rs/)) - ✔️ done by @orhun
- [x] Hydrofoil Generation ([1](https://twitter.com/HydrofoilG/status/1526236691274637312)) - ✔️ done by @kunos
- [x] ~~Grocery Bagger 9000 ([1](https://reddit.com/r/rust_gamedev/comments/uxz0oz/introducing_our_very_first_game_grocery_bagger)) - 🆓 **free**~~
- [x] Combine&Conquer ([1](https://buckmartin.de/combine-and-conquer.html), [2](https://martinbucksoftware.itch.io/combine-and-conquer/devlog/378414/first-public-prototype-release)) - ✔️ done by @ozkriff
- [x] Way of Rhea - ✔️ done by @MasonRemaley

#### Learning Material Updates

- [x] rustacean-station 66 ([1](https://rustacean-station.org/episode/066-eric-smith/)) - ✔️ done by @ozkriff
- [x] ~~Bevy Cheatbook: GPU section ([1](https://bevy-cheatbook.github.io/gpu.html), [2](https://twitter.com/IyesGames/status/1522248147405316096)) - 🆓 **free** (@inodentry?)~~
- [x] Video: Basic Shaders with Bevy ([1](https://youtu.be/EKS0SSq8UPQ)) - ✔️ done by @mwbryant
- [x] Rusteroids tutorial series ([1](https://youtube.com/playlist?list=PLFOS-Gn3aXROnSfl26esPExssd-rQw6jD)) - ✔️ done by @filtoid
- [x] ~~A NixOS flake for Rust, egui, and OpenGL ([1](https://scvalex.net/posts/63/)) - 🆓 **free** (@scvalex?)~~
- [x] Comparing a Voxel Game in F# and Rust ([1](https://cragwind.com/blog/posts/comparing-voxel-game-fsharp-rust/)) - ✔️ done by @AngelOnFira
- [x] ~~Let's Code Snake with Rust and WASM ([1](https://youtu.be/iR7Q_6quwSI)) - 🆓 **free** (@yishn?)~~
- [x] ~~Bevy Basics video series ([1](https://youtube.com/playlist?list=PL6uRoaCCw7GN_lJxpKS3j-KXuThRiSXc6)) - 🆓 **free** (@PhaestusFox?)~~
- [x] GFS: Rust Game Development in 2022 ([1](https://gamefromscratch.com/rust-game-development-in-2022/)) - ✔️ done by @ozkriff
- [x] Lightning Talk: Wasmcloud + Bevy ECS ([1](https://youtube.com/watch?v=8q2sPPX5aXY&t=69), [2](https://github.com/alanpoon/qq_party))) - ✔️ done by @alanpoon
- [x] Multiplayer Game Development in Rust ([1](https://manning.com/books/multiplayer-game-development-in-rust), [2](https://twitter.com/ManningBooks/status/1530202996319084544)) -  ✔️ done by @ozkriff
- [x] Video: Starting a new 2d platformer with ECS ([1](https://youtube.com/watch?v=gjeEYntkvoY)) - ✔️ done by @ChristopherBiscardi
- [x] Audio Libraries Considered Challenging ([1](https://reddit.com/r/rust/comments/ur93w8/audio_libraries_considered_challenging)) - ✔️ done by @ozkriff

#### Engine Updates

- [x] minquad v0.3 ([1](https://twitter.com/fedor_games/status/1523763377071304705)) - ✔️ done by @not-fl3
- [x] fyrox 0.25 ([1](https://reddit.com/r/rust/comments/uq3ipk/im_happy_to_announce_that_fyrox_game_engine_025/), [2](https://reddit.com/r/rust/comments/uz6zbj/media_2d_platformer_tutorial_for_fyrox_game)) - ✔️ done by @mrDIMAS
- [x] DIMS ([1](https://youtube.com/watch?v=jgkhsY8aZO8), [2](https://twitter.com/DimsWorlds/status/1522287856869380097), [3](https://reddit.com/r/rust_gamedev/comments/ujhr3c/the_start_of_a_tool_that_lets_you_tweak_how_and), [4](https://twitter.com/DimsWorlds/status/1527214394966515719), [5](https://reddit.com/r/rust_gamedev/comments/usyz5g/dims_dev_log_now_you_can_make_a_landscape), [6](https://www.reddit.com/r/rust_gamedev/comments/uyb6bi/boom_now_you_can_do_simple_gameplay_scripting)) - ✔️ done by @ozkriff

#### Tooling Updates

- [x] ~~clymene ([1](https://github.com/lucas-miranda/clymene), [2](https://twitter.com/LukeRaccoon/status/1525597342379950088)) - 🆓 **free** (@lucas-miranda?)~~
- [x] Bloom ([1](https://twitter.com/kettlecorn/status/1529193509462360065)) - ✔️ done by @kettle11
- [x] Graphite - ✔️ done by @Keavon

#### Library Updates

- [x] ~~egui 0.18 ([1](https://twitter.com/ernerfeldt/status/1520476478403715073)) - 🆓 **free** (@emilk?)~~
- [x] ~~bevy_egui 0.14 ([1](https://twitter.com/penicillin_duck/status/1520703733755166720)) - 🆓 **free** (@mvlabat?)~~
- [x] ~~bevy_puffin ([1](https://github.com/mvlabat/bevy_puffin)) - 🆓 **free** (@mvlabat?)~~
- [x] ~~puffin_egui 0.15.0 ([1](https://twitter.com/ernerfeldt/status/1524368923931590657)) - 🆓 **free** (@emilk?)~~
- [x] bevy_silk 0.1,0.2 ([1](https://twitter.com/ManevilleF/status/1524820847571226625), [2](https://github.com/ManevilleF/bevy_silk), [3](https://twitter.com/ManevilleF/status/1525912939546435589), [4](https://twitter.com/ManevilleF/status/1527313861199527937)) - ✔️ done by @ManevilleF
- [x] bevy_scripting ([1](https://github.com/makspll/bevy_mod_scripting)) - ✔️ done by @makspll
- [x] bevy-pigeon ([1](https://github.com/MitchellMarinoDev/bevy-pigeon), [2](https://github.com/MitchellMarinoDev/carrier-pigeon), [3](https://github.com/MitchellMarinoDev/bong)) - - [x] Audio Libraries Considered Challenging ([1](https://reddit.com/r/rust/comments/ur93w8/audio_libraries_considered_challenging)) - ✔️ done by @ozkriff
- [x] bevy_kira_audio v0.10 ([1](https://twitter.com/nikl_me/status/1528326107963047938)) - ✔️ done by @NiklasEi
- [x] ~~bevy_rosc ([1](https://github.com/DrLuke/bevy_rosc)) - 🆓 **free** (@DrLuke?)~~
- [x] bevy_asset_loader v0.11 ([1](https://twitter.com/nikl_me/status/1531335926626099201), [2](https://github.com/NiklasEi/bevy_asset_loader/blob/main/CHANGELOG.md#v0110)) - ✔️ done by @NiklasEi
- [x] ~~mmap_cache ([1](https://crates.io/crates/mmap-cache)) - 🆓 **free** (@bonsairobo?)~~
- [x] ~~bustsuri ([1](https://github.com/NemuiSen/bustsuri)) - 🆓 **free** (@NemuiSen?)~~
- [x] ~~glyphon ([1](https://crates.io/crates/glyphon)) - 🆓 **free** (@?grovesNL)~~
- [x] notan v0.4 ([1](https://github.com/Nazariglez/notan/releases/tag/v0.4.0), [2](https://reddit.com/r/rust/comments/uqekq8/released_notan_040_and_some_info_about_future)) - ✔️ done by @Nazariglez
- [x] ~~stretch2/sprawl ([1](https://crates.io/crates/stretch2), [2](https://twitter.com/AliceICecile/status/1524176059985547264), [3](https://reddit.com/r/rust/comments/umwjt4/bevy_and_dioxus_are_collaborating_on_stretch2)) - 🆓 **free** (@alice-i-cecile?)~~
- [x] ~~crevice v0.10 ([1](https://github.com/LPGhatguy/crevice/blob/main/CHANGELOG.md#0100---2022-05-26)) - 🆓 **free** (@LPGhatguy?)~~
- [x] Sparsey 0.8 ([1](https://reddit.com/r/rust/comments/uzmfhj/sparsey_08)) - ✔️ done by @LechintanTudor

#### Discussions

- [x] ["Choosing a networking library for my game"](https://reddit.com/r/rust_gamedev/comments/ujk2s6/choosing_a_networking_library_for_my_game)

## Publishing Steps

- [x] Final review - by everyone
- [x] Publish - by @ozkriff
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff
- [x] Pin thread on Twitter - by @ozkriff
- [x] Add comment links - by @ozkriff
- [x] Add a draft of next month's newsletter - 🚧 WIP by @ozkriff

**Comment by ChristopherBiscardi** [comment]
Happy to take on the piece for "Video: Starting a new 2d platformer with ECS".

**Comment by flukejones** [comment]
I can write about rusty doom (room4doom) I guess.
The repo is [here](https://gitlab.com/flukejones/room4doom), and mirrored [here](https://github.com/flukejones/room4doom)

**Comment by filtoid** [comment]
I can write about the Rusteroids tutorial

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by orhun** [comment]
Hey, I just saw that my [battleship game](https://github.com/orhun/battleship-rs/) is on the list. Do I need to submit a PR to add it to this months newsletter or is it going to be in the "Other" section or something?

**Comment by ozkriff** [comment]
@orhun yeah, you're welcome to submit a PR!
(the ["Other News"](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/850) section is for stuff that no one has written about)

**Comment by makspll** [comment]
Happy to write about bevy_mod_scripting, thanks for the shoutout!

**Comment by 4JX** [comment]
Can I delay the mention of my project for a future issue? I feel it's not *quite* ready for prime-time yet.

**Comment by mwbryant** [comment]
I can handle my bevy shader videos, I actually just finished the 3 part series so it will fit nicely

**Comment by ozkriff** [comment]
@4JX sure! removed from the current plan.

**Comment by kunos** [comment]
will add a section on Hydrofoil Generation

**Comment by shnewto** [comment]
👋 I've got a blurb for limbo pass I'll PR shortly

**Comment by HangingClowns** [comment]
Am I supposed to do something?

**Comment by h3r2tic** [comment]
❤️ I'll do a `kajiya` one next month instead -- I was hoping to release a major update in the past few days, but it's gonna slip until the next weekend instead, thus June.

**Comment by gavlig** [comment]
I'll hopefully contribute with `Gryazevichki` for the next issue. At this stage i only have a few gifs of wip stuff but nothing is finished or ready for viewing yet. and the old published version is not worth another article imho.

**Comment by ozkriff** [comment]
@h3r2tic @gavlig sure, removed from the current plan!

@HangingClowns you're invited to contribute a section about https://rustacean-station.org/episode/066-eric-smith podcast episode if you want. If no one volunteers to write about it, it'll be mentioned only as a one-liner in the "Other news" section ([example](https://gamedev.rs/news/033/#other-news)).

**Comment by AngelOnFira** [comment]
Taking "Comparing a Voxel Game in F# and Rust"

**Comment by cdsupina** [comment]
I just got back from vacation, I wanted to leave an update on the status of the rustconf arcade cabinet. Since it ended up in the announcements section for n33 I was going to place it there.

**Comment by Nazariglez** [comment]
Just added Notan, thanks!

**Comment by 64kramsystem** [comment]
Hi there!

I have two entries I'd like to add:

1. I've just today completed my project of porting 4 games each using a different pure-Rust game engine
2. My work in progress tutorial about Bevy's ECS

Should I add them, or wait for the next month (or Godot? :grin:)

**Comment by AngelOnFira** [comment]
@64kramsystem feel free to add the sections, it's normally ok until we get to the final review phase :)

**Comment by ozkriff** [comment]
Final PR - https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1060 - everyone is invited to review! Merging in an hour if there're no objections.

**Comment by ozkriff** [comment]
It's out! Huge thanks to all editors, contributors, and reviewers!

:tada: https://gamedev.rs/news/034 :tada:
