### ISSUE TITLE
Newsletter 35 - June 2022

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/rust-gamedev.github.io#1065]
# Newsletter 35: June 2022

###### tags: `newsletter`

**Editors:** @17cupsofcoffee, @AngelOnFira, and @ozkriff

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with June's news!

## Current Schedule

**The deadline for all section PRs is the 3rd of July.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Announcements

- [x] Rusty Jam 2 - ✔️ done
- [x] Details of this month's meetup - ✔️ done
- [ ] Arcade Cabinet ([1](https://twitter.com/carlosupina/status/1537596165453225984)) - 🆓 **free** (@cdsupina?)
- [x] Rust GameDev Podcast with Cart ([1](https://rustgamedev.com/episodes/interview-with-carter-anderson-bevy)) - ✔️ done

#### Game Updates

- [x] Veloren ([1](https://veloren.net)) - ✔️ done
- [ ] Fires of Eschaton ([1](https://twitter.com/FiresOfEschaton/status/1534119771045826567)) - 🆓 **free** (@maciejhirsz?)
- [x] DIMS ([1](https://twitter.com/DimsWorlds/status/1537896460582211586), [2](https://twitter.com/DimsWorlds/status/1532696538950119425), [3](https://twitter.com/DimsWorlds/status/1532022023131627528)) - ✔️ done
- [ ] Idu ([1](https://twitter.com/epcc10/status/1532889644165120001)) - 🆓 **free** (@johann2?)
- [x] Hydrofoil Generation ([1](https://twitter.com/HydrofoilG), [2](https://twitter.com/KunosStefano), [3](https://twitter.com/KunosStefano/status/1537416082985820160), [4](https://twitter.com/HydrofoilG/status/1539232071624888321), [5](https://twitter.com/HydrofoilG/status/1541307745772703746)) \- ✔️ done
- [x] Quoridor-rs ([1](https://github.com/baehyunsol/Quoridor-rs)) - ✔️ done
- [x] Harvest Hero Origins ([1](https://store.steampowered.com/news/app/1651500/view/3356885688256120012)) - ✔️ done
- [ ] Combine And Conquer ([1](https://reddit.com/r/rust_gamedev/comments/vl87x4/sound_in_combine_and_conquer), [2](https://reddit.com/r/IndieDev/comments/v4omac/im_pretty_happy_with_the_zoom_in_combine)) - 🆓 **free** (@I3ck?)
- [ ] Fish Folly ([1](https://reddit.com/r/rust_gamedev/comments/vi5jok/media_fish_folly_a_fyrox_showcase_game))  - 🆓 **free** (@erlend-sh?)
- [ ] Punchy ([1](https://reddit.com/r/rust_gamedev/comments/vj9nag/media_punchy_a_fishy_beatemup_spinoff), [2](https://twitter.com/spicylobsterfam/status/1540105977810255872)) - 🆓 **free** (@erlend-sh?)
- [x] Star Machine ([1](https://twitter.com/Seldom_SE/status/1532909654681849856)) - ✔️ done
- [x] ~~Soccer ([1](https://github.com/64kramsystem/rust-game-ports))~~ *covered by `rust_game_ports` section*
- [x] RuggRogue ([1](https://reddit.com/r/rust_gamedev/comments/vluy7u/ruggrogue_a_simple_webplayable_roguelike_made)) - ✔️ done
- [x] vetovoima ([1](https://yourmagicisworking.itch.io/vetovoima), [2](https://twitter.com/MatiasKlemola/status/1541338040521707521)) - ✔️ done
- [x] rust_game_ports ([1](https://github.com/64kramsystem/rust-game-ports)) - ✔️ done
- [ ] Browser Jungle Chess ([1](https://reddit.com/r/rust_gamedev/comments/v3btkk/browser_jungle_chess_with_rust_wasm)) - 🆓 **free**
- [ ] Croquet OS / rapier demo ([1](https://twitter.com/gocroquet/status/1531336194725797889)) - 🆓 **free**
- [ ] Bevy City ([1](https://mungbungo.itch.io/bevy-city), [2](https://twitter.com/mungbungo/status/1537311604572065792), [3](https://twitter.com/mungbungo/status/1540105544438259712), [4](https://twitter.com/mungbungo/status/1542773838530105344))  - 🆓 **free**
- [ ] Measure Once ([1](https://robtfm.github.io/measure_once), [2](https://github.com/robtfm/bevy_carp))  - 🆓 **free** (@robtfm?)
- [ ] Galactic Mess ([1](https://youtube.com/watch?v=DO8vwehkr38))  - 🆓 **free**

#### Learning Material Updates

- [ ] rustacean-station egui ([1](https://rustacean-station.org/episode/emil-ernerfeldt)) - 🆓 **free** (@emilk?)
- [ ] Rusteroids tutorial series ([1](https://youtube.com/playlist?list=PLFOS-Gn3aXROnSfl26esPExssd-rQw6jD)) \- 🆓 **free** (@filtoid?)
- [ ] NVIDIA GPU profiling with Rust ([1](https://simbleau.github.io/blog/gpu-profiling-with-rust/)) - 🆓 **free** (@simbleau?)
- [x] Bevy Basics video series ([1](https://youtube.com/playlist?list=PL6uRoaCCw7GN_lJxpKS3j-KXuThRiSXc6)) - ✔️ done
- [x] Brontefy Me # 3 ([1](https://www.youtube.com/watch?v=oNxMN47tKxs)) - ✔️ done
- [ ] Video: Rust wgpu graphics programming tutorial ([1](https://reddit.com/r/rust/comments/vmpjcr/rust_wgpu_graphics_programming_tutorial_youtube))  - 🆓 **free** (@jack1232?)
- [ ] Way of Rhea interview ([1](https://youtube.com/watch?v=H0sIsrLWojs))  - 🆓 **free** (@MasonRemaley?)
- [ ] Video: Exploring Vulkan API with Rust ([1](https://youtube.com/watch?v=_PNiRGIAfY4))  - 🆓 **free** (@Lyrapuff?)

#### Engine Updates

- [x] ggez v0.8.0-rc0 ([1](https://www.reddit.com/r/rust_gamedev/comments/v6a3kn/ggez_080rc0)) - ✔️ done
- [ ] pufferfish ([1](https://github.com/pufferfish-rs/pufferfish/))  - 🆓 **free** (@lunabunn?)

#### Tooling Updates

- [ ] ~~Bloom ([1](https://twitter.com/kettlecorn/status/1536008004918816770?t=DrlQSewjlaamO4LflfuapQ&s=09)) - 🆓 **free** (@kettle11?)~~
- [x] Noumenal ([1](https://reddit.com/r/rust/comments/vj40qq/noumenal_my_3d_modeling_app_for_ios), [2](https://apps.apple.com/us/app/noumenal/id1584884105)) - ✔️ done
- [ ] quad-gif ([1](https://github.com/ollej/quad-gif), [2](https://twitter.com/ollej/status/1539693835286093831))  - 🆓 **free** (@ollej?)
- [ ] Game Boy Emulator ([1](https://reddit.com/r/rust/comments/vbgk1q/a_game_boy_emulator_written_in_rust), [2](https://github.com/p4ddy1/gbemulator))  - 🆓 **free** (@p4ddy1?)

#### Library Updates

- [x] kajiya ([1](https://twitter.com/h3r2tic/status/1532829918194806784)) - ✔️ done
- [x] ezinput v0.3.* ([1](https://crates.io/crates/ezinput/versions)) - ✔️ done
- [ ] bevy_mod_picking v0.7 ([1](https://github.com/aevyrie/bevy_mod_picking/releases/tag/v0.7.0)) - 🆓 **free** (@aevyrie?)
- [ ] bevy_mod_outline ([1](https://github.com/komadori/bevy_mod_outline)) - 🆓 **free** (@komadori?)
- [ ] bevy-yoleck ([1](https://github.com/idanarye/bevy-yoleck)) - 🆓 **free** (@idanarye?)
- [x] notan v0.5 ([1](https://github.com/Nazariglez/notan/releases/tag/v0.5.0)) - ✔️ done
- [x] psf2 ([1](https://github.com/Ralith/psf2)) - ✔️ done
- [x] glam ([1](https://github.com/bitshifter/glam-rs/blob/main/CHANGELOG.md#0210---2022-06-22)) - ✔️ done
- [ ] bevy_mod_raycast v0.5 ([1](https://github.com/aevyrie/bevy_mod_raycast/releases/tag/v0.5))  - 🆓 **free** (@aevyrie?)
- [ ] taffy (pka sprawl) ([1](https://github.com/DioxusLabs/taffy), [2](https://twitter.com/AliceICecile/status/1535329149245657091))  - 🆓 **free** (@alice-i-cecile?)

#### Other News

- [ ] Bullet points of any interesting news that doesn't have its own section - 🆓 **free** (@username?)

#### Discussions

- [x] [Shopping list](https://reddit.com/r/rust_gamedev/comments/v8tx37/shopping_list)
- [x] [Hands-on Rust: Further reading](https://reddit.com/r/rust_gamedev/comments/v4q4pr/handson_rust_further_reading)
- [x] [How can I start developing a 3D game engine?](https://reddit.com/r/rust_gamedev/comments/v3z4i1/how_can_i_start_developing_a_3d_game_engine)
- [ ] ~~[Should game engines have a visual editor?](https://twitter.com/cart_cart/status/1535128838971088898)~~
- [x] [Bevy or Fyrox for 3D Game Development?](https://reddit.com/r/rust_gamedev/comments/v7svhg/bevy_or_fyrox_for_3d_game_dev)

#### Jobs

- [x] [DIMS](https://www.dims.co/jobs) (Stockholm/Remote): Various roles, open applications accepted.
- [x] [Embark Studios](https://careers.embark-studios.com/jobs) (Stockholm/Hybrid Remote): Various roles, open applications accepted.
- [x] [Mutate](https://rustjobs.dev/featured-jobs/Mutate-Rust-Backend-Software-Engineer-7kfTlQFSagzwHhugw1p0)
    
## Publishing Steps

- [x] Final review - by everyone
- [x] Publish - by @17cupsofcoffee
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @17cupsofcoffee
- [x] Pin thread on Twitter - by @ozkriff
- [x] Add comment links - by @17cupsofcoffee
- [x] Add a draft of next month's newsletter - by @17cupsofcoffee

**Comment by h3r2tic** [comment]
I'll take `kajiya`! 🥳 Thanks for including me 🥰

**Comment by kettle11** [comment]
I appreciate the inclusion! But Bloom doesn't have any released features this month that merit an update. The linked Tweet is a preview of something upcoming that's not yet released.

**Comment by JMS55** [comment]
I will write about [botnet](https://github.com/JMS55/botnet) - a multiplayer wasm scripting game.

**Comment by nobbele** [comment]
I'll take `ggez`

**Comment by bitshifter** [comment]
I can take `glam`, thanks for the mention :)

**Comment by Seldom-SE** [comment]
I'll take Star Machine. Thanks!

**Comment by Ralith** [comment]
Taking psf2.

**Comment by klemola** [comment]
I'll take vetovoima. Delighted to see it on the list!

**Comment by kunos** [comment]
I'll do Hydrofoil Generation.. thx for including it

**Comment by baehyunsol** [comment]
I'll take `Quoridor-rs`. Thanks for including mine!

**Comment by filtoid** [comment]
I'm afraid I'm away at the moment, and Rusteroids is taking a bit of a break as a result. I'll have something for next month in the form of an update.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by tung** [comment]
I'll do RuggRogue. Thanks!

**Comment by 64kramsystem** [comment]
Hi there! I'll take the one assigned to me, which is actually also a group of games :smile: I'll also add my Bevy ECS tutorial, which is almost complete, and will be completed by the time the Newsletter is released.

**Comment by Bombfuse** [comment]
I'll take HHO! Will try and get something finished by EOW

**Comment by eexsty** [comment]
I'll take `ezinput`! Thanks for the opportunity :smile:

**Comment by HackerFoo** [comment]
I'll take Noumenal. Thanks!

**Comment by aevyrie** [comment]
First time being pinged for the newsletter, can I ask why this release of bevy_mod_picking was added to this list?

**Comment by 17cupsofcoffee** [comment]
@aevyrie: We generally gather the links for the newsletter outline from:

* Twitter
* /r/rust and /r/rust_gamedev on Reddit
* Various Rust Discord servers

If something's included, it just means one of us happened to see it and thought it was interesting :)

Important to mention: there's no obligation to contribute! We just ping people as a heads up in case they want to write about their project.

**Comment by not-fl3** [comment]
I'll do miniquad update
(not in the list, but there are some updates!)

**Comment by PhaestusFox** [comment]
I hoping to be done with my user input mini-series of bevy basics so ill do that. thanks for including me

**Comment by philpax** [comment]
Hi there! I'll take the game update for DIMS on behalf of @FredrikNoren - will get that in soon!

**Comment by Keavon** [comment]
I'll be submitting for Graphite tonight.

**Comment by lunabunn** [comment]
Thank you so much for the inclusion! I don't think I'll be able to get the PR in in time for this month since I'm going on a 14-hour-long plane trip tomorrow, but I'll hopefully have something next month :-)

**Comment by MasonRemaley** [comment]
Whoops was away from home and didn't see this in time--leaves more updates for next month's. :)

**Comment by alice-i-cecile** [comment]
Oops... Same here. I've been busy; I'll leave a note about `taffy` in next month :)

**Comment by 17cupsofcoffee** [comment]
Aiming to get the release PR posted tonight if I can - if you have any last minute submissions, please try to get them done soon!

**Comment by 17cupsofcoffee** [comment]
_and as usual by tonight I mean tomorrow_

The release PR and preview is ready for review: https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1092

**Comment by cdsupina** [comment]
If there is still time I would like to get the arcade cabinet mentioned. I can do it today after work.
