### ISSUE TITLE
Newsletter 36 - July 2022

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#1098]
# Newsletter 36: July 2022

###### tags: `newsletter`

**Editors:** @ozkriff, @AngelOnFira, and @17cupsofcoffee

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with TODO's news!

## Current Schedule

The soft deadline for all section PRs is the 3rd of August.

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Announcements

- [x] Rust Gamedev meetup - ✔️ done by @AngelOnFira
- [ ] Rust Tokyo Game Hack event ([1](https://reddit.com/r/rust/comments/w7bktx/2022_tokyo_and_elsewhere_rust_game_hack_event_aug)) - 🆓 **free** (@PabloMansanet?)
- [ ] Arcade cabinet ([1](https://twitter.com/carlosupina/status/1545856191338876928), [2](https://twitter.com/carlosupina/status/1546530134248898561), [3](https://twitter.com/carlosupina/status/1546887867183546370), [4](https://twitter.com/carlosupina/status/1547599507147214848)) - 🚧 WIP by @cdsupina
- [ ] nintendo switch target merged ([1](https://reddit.com/r/rust/comments/vzr6oq/aarch64nintendoswitchfreestanding_target_merged), [2](https://twitter.com/AliceICecile/status/1547809268790808579), [3](https://github.com/rust-lang/rust/pull/95897)) - 🆓 **free** (@jam1garner?)
- [x] rust-game-ports ([1](https://reddit.com/r/rust_gamedev/comments/wbwfxi/gamedev_wg_rust_game_ports_welcomes_your_game), [2](https://github.com/rust-gamedev/rust-game-ports)) - ✔️ done by @64kramsystem
- [x] 3D Ferris - ✔️ done by @RayMarch

#### Game Updates

- [x] Veloren ([1](https://veloren.net)) - ✔️ done by @AngelOnFira 
- [ ] Hydrofoil Generation ([1](https://twitter.com/HydrofoilG), [2](https://twitter.com/HydrofoilG/status/1544298693590908929), [3](https://twitter.com/HydrofoilG/status/1545051054840037381), [4](https://twitter.com/KunosStefano/status/1547226917912412161), [5](https://twitter.com/HydrofoilG/status/1549384166961209344)) - 🆓 **free** (@kunos?)
- [ ] Punchy v0.0.2 ([1](https://reddit.com/r/rust/comments/vt44wq/media_punchy_v002_scenes_egui_ui_enemy_ai_ci_and), [2](https://twitter.com/spicylobsterfam/status/1544827892064034817), [3](https://reddit.com/r/rust/comments/waltwb/media_fish_fight_punchy_v003_beatemup_made_in), [4](https://spicylobster.itch.io/punchy/devlog/409761/punchy-makes-its-debut-)) - 🆓 **free** (@erlend-sh?)
- [ ] Fish Folly ([1](https://youtube.com/watch?v=YRE5g57aZEg), [2](https://youtu.be/RuoLInE34dM)) - 🆓 **free** (@erlend-sh?)
- [x] Agma ([1](https://medium.com/@tucker.bull.morgan/summoning-a-devil-544b130c8889), [2](https://github.com/TuckerBMorgan/Agma)) - ✔️ done  by @TuckerBMorgan
- [ ] Combine And Conquer ([1](https://martinbucksoftware.itch.io/combine-and-conquer/devlog/401610/release-of-008-prototype-now-with-sound), [2](https://reddit.com/r/rust_gamedev/comments/wct13d/i_just_released_combine_and_conquer_009_with)) - 🆓 **free** (@I3ck?)
- [x] Flesh ([1](https://twitter.com/Im_Oab/status/1545336150310932480), [2](https://twitter.com/Im_Oab/status/1551696644001103872), [3](https://twitter.com/Im_Oab/status/1553488713782796289), [4](https://twitter.com/Im_Oab/status/1553149157950771200)) - ✔️ done by @Im-Oab
- [ ] Idu ([1](https://twitter.com/epcc10/status/1545918011185549313), [2](https://twitter.com/epcc10/status/1547723415015919622)) - 🆓 **free** (@johann2?)
- [ ] Life Code ([1](https://youtube.com/watch?v=a6ZnhXGp3JI)) - 🆓 **free**
- [ ] Legend of Worlds ([1](http://legendofworlds.com/dev-log-1/), [2](https://reddit.com/r/rust_gamedev/comments/w2508b/legend_of_worlds_1)) - 🆓 **free**
- [x] Robo Instructus 3y ([1](https://blog.roboinstruct.us/2022/07/16/3-years-old.html)) - ✔️ done by @alexheretic
- [x] Cyber Gate ([1](https://reddit.com/user/CyberSoulWriter/submitted)) - ✔️ done by @cybersoulK
- [x] gmtk: re-rolling ([1](https://mystal.itch.io/re-rolling), [2](https://twitter.com/mystalice/status/1548469410406342663)) - ✔️ done by @mystal
- [ ] bevy roguelike ([1](https://github.com/tomuxmon/bevy_roguelike)) - 🆓 **free** (@tomuxmon?)
- [ ] Theta Wave ([1](https://reddit.com/r/rust/comments/w4h4ad/my_game_thetawave_made_with_rust_is_now_playable), [2](https://twitter.com/carlosupina/status/1550110089058607104)) - 🆓 **free** (@cdsupina?)
- [ ] Paddlepunks ([1](https://twitter.com/sov_gott_games)) - 🆓 **free** (@halvnykterist?)
- [ ] Bounce Up! ([1](https://cryscan.itch.io/bounce-up), [2](https://youtube.com/watch?v=ohNQgahuj6U)) - 🆓 **free** (@cryscan?)
- [x] Botnet - ✔️ done by @JMS55
- [x] Simon Arcade - ✔️ done by @Vrixyz
- [x] Way oh Rhead - ✔️ done by @MasonRemaley
- [ ] Galactic Mess - 🚧 WIP by @Elogain

#### Learning Material Updates

- [x] Pathfinding in Rust: A tutorial with examples ([1](https://blog.logrocket.com/pathfinding-rust-tutorial-examples)) - ✔️ done by @gregstoll
- [ ] Learn WGPU updated to 0.13 ([1](https://sotrh.github.io/learn-wgpu/news/0.13/), [2](https://reddit.com/r/rust_gamedev/comments/vq5opd/learn_wgpu_updated_to_013)) - 🆓 **free** (@sotrh?)
- [x] Sand Fall With Compute Shaders in Rust ([1](https://reddit.com/r/rust_gamedev/comments/vmynrq/sand_fall_with_compute_shaders_in_rust), [2](https://www.okkohakola.com/posts/sandfall_tutorial/)) - ✔️ done by @hakolao
- [ ] Rust breakout game tutorial ([1](https://youtube.com/watch?v=xQ9YTY7ZgsI)) - 🆓 **free** (@TanTan)
- [ ] Port of vulkan-tutorial.com ([1](https://reddit.com/r/rust_gamedev/comments/w2g16h/yet_another_vulkan_tutorial)) - 🆓 **free** (@KyleMayes?)
- [ ] Bevy Basics video series ([1](https://youtube.com/playlist?list=PL6uRoaCCw7GN_lJxpKS3j-KXuThRiSXc6)) \- 🆓 **free** (@PhaestusFox?)
- [x] Rusteroids tutorial series ([1](https://youtube.com/playlist?list=PLFOS-Gn3aXROnSfl26esPExssd-rQw6jD)) - ✔️ done by @filtoid
- [x] Video: Creating mountains from planes with vertex shaders and Bevy ([1](https://youtube.com/watch?v=85uJc81SQZ4)) - ✔️ done by @ChristopherBiscardi
- [x] Video: What's in a wgsl fragment shader? ft Bevy ([1](https://youtube.com/watch?v=SOOOc9-joVo)) - ✔️ done by @ChristopherBiscardi
- [ ] RuggRogue Source Code Guide ([1](https://reddit.com/r/roguelikes/comments/vluuud/ruggrogue_a_simple_webplayable_roguelike_inspired), [2](https://reddit.com/r/rust_gamedev/comments/vluy7u/ruggrogue_a_simple_webplayable_roguelike_made), [3](https://tung.github.io/ruggrogue/source-code-guide/new-game-plus.html))  - 🆓 **free** (@tung?)

#### Engine Updates

- [x] godot-rust ([1](https://twitter.com/GodotRust/status/1548762938621714440)) - ✔️ done by @Bromeon
- [x] Gamercade ([1](https://reddit.com/r/rust_gamedev/comments/w8idew/announcing_gamercade_a_new_wasm_console), [2](https://gamercade.io/)) - ✔️ done by @RobDavenport
- [x] bevy 0.8 - ✔️ done by @cart
- [x] Dims - ✔️ done by @philpax

#### Tooling Updates

- [x] Blackjack - ✔️ done by @setzer22
- [ ] unitypacker ([1](https://reddit.com/r/rust/comments/vwpnj0/unitypackage_creator_made_with_rust), [2](https://github.com/paulfigiel/unitypacker)) - 🆓 **free** (@paulfigiel?)
- [x] NES Bundler ([1](https://github.com/tedsteen/nes-bundler)) - ✔️ done by @tedsteen
- [x] bevy_shadertoy_wgsl ([1](https://github.com/eliotbo/bevy_shadertoy_wgsl), [2](https://t.co/uCtmlrzHS0)) - ✔️ done by @eliotbo
- [ ] annelid ([1](https://github.com/dagit/annelid)) - 🆓 **free** (@dagit?)
- [x] Graphite - ✔️ done by @Keavon

#### Library Updates

- [ ] wgpu v0.13 ([1](https://reddit.com/r/rust_gamedev/comments/vp571t/release_of_wgpu_v013_and_call_for_testing), [2](https://gfx-rs.github.io/2022/06/30/release-0.13.html)) - 🆓 **free** (@cwfitzgerald?)
- [x] miniquad - ✔️ done by @not-fl3
- [x] shame ([1](https://github.com/RayMarch/shame), [2](https://twitter.com/Ray__March/status/1544683536694796290)) - ✔️ done by RayMarch
- [x] lyon v1.0 ([1](https://reddit.com/r/rust/comments/vwdxim/announcing_lyon_100)) - ✔️ done by @nical
- [ ] bonsai-bt ([1](https://github.com/Sollimann/bonsai), [2](https://reddit.com/r/rust_gamedev/comments/vxk8h9/bonsaibt_a_behavior_tree_library_in_rust)) - - 🆓 **free** (@Sollimann?)
- [x] hecs v0.8 ([1](https://github.com/Ralith/hecs/blob/master/CHANGELOG.md#080)) - ✔️ done by @Ralith
- [x] Wanderlust ([1](https://crates.io/crates/bevy_mod_wanderlust)) - ✔️ done by @PROMETHIA-27
- [ ] fdg ([1](https://github.com/grantshandy/fdg), [2](https://reddit.com/r/rust/comments/w92aya/fdg_a_force_directed_graph_drawing_framework)) - 🆓 **free** (@grantshandy?)
- [ ] bevy_pancam ([1](https://github.com/johanhelsing/bevy_pancam)) - 🆓 **free** (@johanhelsing?)
- [x] bevy_godot ([1](https://github.com/rand0m-cloud/bevy_godot)) - ✔️ done by @rand0m-cloud
- [x] renet & bevy_renet ([1](https://github.com/lucaspoffo/renet)) - ✔️ done by @lucaspoffo
- [ ] shades ([1](https://phaazon.net/blog/shades-edsl), [2](https://twitter.com/phaazon_/status/1553374646476701700)) - 🆓 **free** (@phaazon?)
- [x] bevy_fbx - ✔️ done by @nicopap
- [ ] wgpu&naga - 🚧 WIP by @cwfitzgerald

#### Other News

- [ ] Bullet points of any interesting news that doesn't have its own section

#### Discussions

- [ ] [Using WGPU + crates directly or Bevy?](https://reddit.com/r/rust_gamedev/comments/vrfjw2/using_wgpu_crates_directly_or_bevy)
- [ ] [Are these misconceptions about rust?](https://reddit.com/r/rust/comments/vruvxx/are_these_misconceptions_about_rust)
- [ ] [A 2D, lightweight graphics library, Rust-only?](https://reddit.com/r/rust_gamedev/comments/w9l1um/a_2d_lightweight_graphics_library_rustonly)
- [ ] [Framework or libraries for developing Android/iOS games](https://reddit.com/r/rust_gamedev/comments/wbg7xg/framework_or_libraries_for_developing_androidios)

## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @ozkriff
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @ozkriff
- [ ] Add a draft of next month's newsletter - by @ozkriff

**Comment by filtoid** [comment]
I'll take Rusteroids, I've got a couple of updates for it.

**Comment by nicopap** [comment]
- [`bevy_fbx`](https://github.com/HeavyRain266/bevy_fbx) an in-development and incoming plugin for the bevy game engine to load FBX files (@HeavyRain266 and me)
- AFAIK bevy 0.8 will be released before the newsletter is published

**Comment by philpax** [comment]
I'll write an update for Dims (game engine), as I did last time. (By the way - the deadline says 3rd of April, I assume that's meant to be August?)

**Comment by JMS55** [comment]
I'll be writing about https://github.com/JMS55/botnet again this month.

**Comment by PROMETHIA-27** [comment]
I've taken `bevy_mod_wanderlust`

**Comment by lucaspoffo** [comment]
When is the deadline? It's wrong in the description, `3rd of April`.

**Comment by grantshandy** [comment]
Hello, thanks for considering my project **[fdg](https://github.com/grantshandy/fdg)** for this newsletter. I should let you know that it really doesn't have much to do with game development though, **it's more in the data visualization space**.

If it still sounds like something you all want to mention in the newsletter I'm happy to see it put out there, but I just wanted to let you all know it's real purpose.

**Comment by ChristopherBiscardi** [comment]
I'll take on the two videos I'm tagged for.

**Comment by mystal** [comment]
I'll write about _Re-Rolling!_, my GMTK Jam game that I'm tagged for.

**Comment by Elogain** [comment]
Hello! 

`This is not an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!`

I'd like to write about a small game I'm making called "Galactic Mess", thank you!

**Comment by Ralith** [comment]
Taking hecs.

**Comment by eliotbo** [comment]
I'll write about bevy_shadertoy_wgsl

**Comment by gregstoll** [comment]
I'll take Pathfinding in Rust: A tutorial with examples - thanks!

**Comment by cart** [comment]
I'll take Bevy 0.8

**Comment by tedsteen** [comment]
I did NES Bundler, hope I did it right 😄

**Comment by nicopap** [comment]
I'll be writing a section about `bevy_fbx` (not listed, a new library)

**Comment by TuckerBMorgan** [comment]
I will take Agma!

**Comment by cwfitzgerald** [comment]
I will do my best to take wgpu 0.13/naga 0.9

**Comment by kunos** [comment]
I won't be able to do Hydrofoil Generation this month. Hope to be in next month.

**Comment by hakolao** [comment]
Added #1116 about `Sand Fall With Compute Shaders in Rust`. Hopefully formatted correctly.

**Comment by Bromeon** [comment]
Added #1117 about godot-rust 🤖🦀

**Comment by TuckerBMorgan** [comment]
Added #1118  about agma

**Comment by RobDavenport** [comment]
Added #1119  about Gamercade

**Comment by 64kramsystem** [comment]
I confirm the rust-game-ports section.

**Comment by cdsupina** [comment]
I'll take the arcade cabinet. I'll start writing it tonight after RustConf.

**Comment by Keavon** [comment]
Writing about Graphite today.

**Comment by 64kramsystem** [comment]
> The soft deadline for all section PRs is the 3rd of April.

@ozkriff We need a time machine :smile: Probably the template wording could be changed to "following month" or something similar, in order to avoid having to change the description every month :grin:

**Comment by ozkriff** [comment]
😖 sorry for the late replies! going to finish the reviews and prepare the final draft tomorrow (sunday).

> fdg <...> more in the data visualization space.

@grantshandy yeah, sure, it still fits the newsletter! please send a PR if you have time to write it before the release. btw, I'm not sure if fdg belongs to libraries or if it's more of a tool.

> I'd like to write about a small game I'm making called "Galactic Mess", thank you!

@Elogain sure! same as above, please send a PR if you have time to write it before the release.

> 3rd of April

@lucaspoffo @64kramsystem oh, time-warped it to August

> Probably the template wording could be changed to "following month" or something similar, in order to avoid having to change the description every month

@64kramsystem maybe, but it might confuse people if we post the coordination issue when the month is already over :thinking:

**Comment by ozkriff** [comment]
Better late than never, here's the final PR - https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1060 - everyone is invited to review! Merging in a few hours if there're no objections.

**Comment by ozkriff** [comment]
And it's out! As always, huge thanks to all editors, contributors, and reviewers! :crab: 

https://gamedev.rs/news/036

**Comment by eliotbo** [comment]
added #1120 about bevy_shadertoy_wgsl and GLSL2WGSL
