### ISSUE TITLE
<hr/> tag looks weird with `margin: 0`

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#11]
Minima's `_base.scss` file resets the margin of the `<hr>` tag to zero:

https://github.com/rust-gamedev/rust-gamedev.github.io/blob/8dab245a216cf789c77f33b041f70083a7e3c0ee/_sass/minima/_base.scss#L4-L7

And it results in that Markdown's horizontal line `------` sticks to the next line uncomfortably close:

![image](https://user-images.githubusercontent.com/662976/63459167-c4d77280-c45c-11e9-9193-14cef50f3774.png)

With this brute-force patch:

```diff
$ git diff _sass/
diff --git a/_sass/minima/_base.scss b/_sass/minima/_base.scss
index db7d5a1..cac4ba7 100644
--- a/_sass/minima/_base.scss
+++ b/_sass/minima/_base.scss
@@ -37,6 +37,7 @@ body {
 h1, h2, h3, h4, h5, h6,
 p, blockquote, pre,
 ul, ol, dl, figure,
+hr,
 %vertical-rhythm {
   margin-bottom: $spacing-unit / 2;
 }
```

it looks much better to me:

![image](https://user-images.githubusercontent.com/662976/63459553-6a8ae180-c45d-11e9-8d20-11b17346c2fd.png)

But I'm note sure if that's the correct way of doing it.

**Comment by ozkriff** [comment]
Also, something seems to be wrong with nested lists' margins:

![image](https://user-images.githubusercontent.com/662976/63460096-85aa2100-c45e-11e9-85d5-0f01edaf18ab.png)

**Comment by 17cupsofcoffee** [comment]
The only downside to editing the minima files would be we'd have to diff them if we upgrade to a newer version or risk losing your changes - the alternative would be to add `hr { margin-bottom: $spacing-unit / 2; }` to `extra.scss`, but that would bump the filesize a little. Tradeoffs to both ways :)

The nested list issue is my bad - change this part of `extra.scss`:

```scss
li {
    // For consistency with other elements.
    margin-bottom: 15px;
}
```

To this:

```scss
li {
    // For consistency with other elements.
    margin: 15px 0;
}
```

Might be worth adding these tweaks (and any others) to the newsletter PR if they're in service of making the newsletter look better!
