### ISSUE TITLE
Newsletter 37 - August 2022

### ISSUE THREAD

**Issue by AngelOnFira** [rust-gamedev/rust-gamedev.github.io#1134]
# Newsletter 37: August 2022

###### tags: `newsletter`

**Editors:** @AngelOnFira, @17cupsofcoffee, and @ozkriff

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with August's news!

## Current Schedule

The soft deadline for all section PRs is the 7th of September.

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Announcements

- [ ] Rust Gamedev meetup - 🚧 WIP by @AngelOnFira
- [ ] Arcade Cabinet ([1](https://twitter.com/carlosupina/status/1554135240993640448), [2](https://reddit.com/r/rust/comments/wgiivj/introducing_rust_arcade), [3](https://twitter.com/carlosupina/status/1555601763016658945)) - 🚧 WIP by @cdsupina
- [ ] bevyjam 2 ([1](https://twitter.com/BevyEngine/status/1555325406470803456), [2](https://reddit.com/r/rust/comments/x0ziei/bevy_jam_2_has_ended_play_and_rate_the_93_games), [3](https://twitter.com/BevyEngine/status/1564347571342295041), [4](https://reddit.com/r/bevy/comments/x1d3a5/my_first_impressions_after_bevy_jam_2)) - 🆓 **free** (@cart?)
- [ ] Bombercrab Challenge ([1](https://blog.tonari.no/rust-game-hack-2022)) - 🆓 **free** (@PabloMansanet?)

#### Game Updates

- [x] Country Slice ([1](https://twitter.com/anastasiaopara/status/1560673892574035969), [2](https://twitter.com/anastasiaopara/status/1564188685335232513)) - ✔️ done
- [ ] Veloren ([1](https://veloren.net)) - 🚧 WIP by @AngelOnFira
- [ ] Hydrofoil Generation ([1](https://twitter.com/HydrofoilG)) - 🚧 WIP by @kunos
- [ ] Caveth ([1](https://reddit.com/r/rust_gamedev/comments/wepewq/i_made_a_simple_game_in_rust_using_macroquad_its), [2](https://github.com/Dequog/caveth)) - 🆓 **free** (@Dequog?)
- [ ] Flesh ([1](https://twitter.com/Im_Oab/status/1555684293997113344), [2](https://twitter.com/Im_Oab/status/1557714901434781696), [3](https://twitter.com/Im_Oab/status/1564581193454354432), [4](https://twitter.com/Im_Oab/status/1562015685521604610)) - 🆓 **free** (@Im-Oab?)
- [ ] Punchy ([1](https://reddit.com/r/rust_gamedev/comments/wkf8cj/fighter_state_machine_subset_of_punchy_bevy), [2](https://reddit.com/r/rust_gamedev/comments/x1ekmg/fish_folk_punchy_v004), [3](https://reddit.com/r/rust_gamedev/comments/wf2jri/fish_fight_is_renamed_to_fish_folk_bundle)) - 🆓 **free** (@erlend-sh?)
- [ ] Spherical Go ([1](https://reddit.com/r/rust_gamedev/comments/wmvx92/spherical_go_3d_game_of_go_with_board_without), [2](https://github.com/Dominux/spherical-go)) - 🆓 **free** (@Dominux?)
- [ ] Combine And Conquer ([1](https://buckmartin.de/combine-and-conquer/2022-08-20-v0.0.10.html), [2](https://reddit.com/r/rust_gamedev/comments/wt7w9s/version_0010_of_my_space_automation_game_combine)) - 🆓 **free** (@I3ck?)
- [x] Rusty Aquarium ([1](https://blog.agical.se/en/posts/the-story-behind-rusty-aquarium/), [2](https://github.com/ollej/rusty-aquarium)) - ✔️ done
- [x] Infinite Bunner ([1](https://twitter.com/ollej/status/1560195403387117571), [2](https://twitter.com/ollej/status/1561403544888016899), [3](https://github.com/ollej/rust-bunner-macroquad)) - ✔️ done
- [ ] bevy-cheeseball ([1](https://twitter.com/rustninjasabi/status/1561303217484566529), [2](https://github.com/Rust-Ninja-Sabi/rust-bevy-cheeseball)) -  - 🆓 **free** (@Rust-Ninja-Sabi?)
- [x] Cyber Gate ([1](https://reddit.com/r/rust_gamedev/comments/wu7odt/udp_on_the_browser_wgpu_rapier3d_open_to_play)) - ✔️ done

#### Learning Material Updates

- [ ] Bevy Basics video series ([1](https://youtube.com/playlist?list=PL6uRoaCCw7GN_lJxpKS3j-KXuThRiSXc6)) - 🆓 **free** (@PhaestusFox?)
- [ ] Rust wgpu series ([1](https://youtube.com/playlist?list=PL_UrKDEhALdJS0VrLPn7dqC5A4W1vCAUT)) - 🆓 **free** (@jack1232?)
- [ ] console 118: rend3 ([1](https://console.substack.com/p/console-118)) - 🆓 **free** (@cwfitzgerald?)
- [ ] Integrating Rust code into Unity ([1](https://rjgameiro.medium.com/let-fun-rust-unity-f7f62609ba49), [2](https://twitter.com/fronkongames/status/1560572288508076032)) - 🆓 **free** (@nullvision?)
- [ ] Learn OpenGL with Rust Series ([1](https://dev.to/samkevich/series/19415), [2](https://github.com/samkevich/learn_gl_with_rust)) - 🆓 **free** (@samkevich?)

#### Engine Updates

- [ ] Fyrox v0.27 ([1](https://reddit.com/r/rust_gamedev/comments/wtgjzy/fyrox_book_new_chapter_particle_systems), [2](https://reddit.com/r/rust_gamedev/comments/wtgjzy/fyrox_book_new_chapter_particle_systems), [3](https://twitter.com/DmitryNStepanov/status/1561784796459704320), [4](https://fyrox.rs/blog/post/feature-highlights-0-27), [5](https://reddit.com/r/rust/comments/whxk0c/im_happy_to_announce_that_fyrox_game_engine_027), [6](https://gamefromscratch.com/fyrox-rust-game-engine-0-27-release/)) - 🚧 WIP by @mrdimas
- [ ] Pyxel v0.18 ([1](https://twitter.com/kitao/status/1564234852185960449), [2](https://github.com/kitao/pyxel/blob/main/CHANGELOG.md#180)) - 🆓 **free** (@kitao)
- [x] Gamercade ([1](https://gamercade.io/blog/open-source-announcement), [2](https://gamercade.io/blog/this-week-at-gamercade-8-2022-1), [3](https://gamercade.io/blog/this-week-at-gamercade-8-2022-2), [4](https://gamercade.io/blog/this-week-at-gamercade-8-2022-3), [5](https://gamercade.io/blog/this-week-at-gamercade-8-2022-4), [6](https://reddit.com/r/rust_gamedev/comments/wt6k9u/new_wip_fish_game_in_gamercade_virtual_console/)) - ✔️ done
- [x] runty8 ([1](https://github.com/jjant/runty8), [2](https://reddit.com/r/rust/comments/wt8iue/runty8_a_pico8_clone_in_rust_looking)) - ✔️ done
- [ ] Bevy ([1](https://twitter.com/cart_cart/status/1557475454457499649), [2](https://reddit.com/r/rust/comments/wl93op/bevys_second_birthday), [3](https://reddit.com/r/gamedev/comments/wl9412/bevys_second_birthday)) - 🆓 **free** (@cart?)

#### Tooling Updates

- [ ] Graphite - 🚧 WIP by @Keavon
- [ ] noumenal ([1](https://youtu.be/BanMIX3_GiU)) - 🆓 **free** (@hackerfoo?)
- [ ] nbody-wasm-sim ([1](https://github.com/simbleau/nbody-wasm-sim), [2](https://reddit.com/r/rust_gamedev/comments/wiwj6s/a_webgpu_nbody_astrophysics_simulation_in_rust)) - 🆓 **free** (@simbleau?)
- [ ] WGEN ([1](https://github.com/jice-nospam/wgen), [2](https://reddit.com/r/rust_gamedev/comments/wguv60/heightmap_generator_using_egui_and_three_d)) - 🆓 **free** (@jice-nospam?)
- [ ] Bevy Shell Template ([1](https://reddit.com/r/rust/comments/wnsu3h/bevy_shell_an_opinionated_monolithic_template), [2](https://github.com/kurbos/bevy-shell-template)) - 🆓 **free** (@kurbos?)

#### Library Updates

- [ ] bevy_streamdeck ([1](https://twitter.com/FrancoisMockers/status/1553536956855894017), [2](https://github.com/vleue/bevy_streamdeck)) - 🆓 **free** (@vleue?)
- [x] Shipyard 0.6 ([1](https://reddit.com/r/rust/comments/wi71lu/shipyard_06_release)) - ✔️ done
- [ ] kira 0.7 ([1](https://github.com/tesselode/kira/releases/tag/v0.7.0)) - 🆓 **free** (@tesselode?)
- [x] bevy_kira_audio 0.11 ([1](https://twitter.com/nikl_me/status/1553999681306316800), [2](https://github.com/NiklasEi/bevy_kira_audio)) - ✔️ done
- [ ] edict ([1](https://twitter.com/zakarum4/status/1557415487281192961), [2](https://twitter.com/zakarum4/status/1563508750941503491)) - 🆓 **free** (@zakarumych?)
- [ ] egui 0.19 ([1](https://twitter.com/ernerfeldt/status/1561010036255739904)) - 🆓 **free** (emilk?)
- [ ] Goggles ([1](https://reddit.com/r/rust_gamedev/comments/wkcysc/goggles)) - 🆓 **free** (@erlend-sh?)
- [ ] notan v0.6 ([1](https://reddit.com/r/rust/comments/x0lskg/notan_is_a_simple_and_portable_layer)) - 🆓 **free** (@Nazariglez?)
- [ ] maths ([1](https://github.com/polymonster/maths-rs), [2](https://www.polymonster.co.uk/blog/maths-rs), [3](https://reddit.com/r/rust_gamedev/comments/wztd2m/building_a_gamedev_maths_library_in_rust)) - 🆓 **free** (@polymonster?)
- [ ] FunDSP v0.8 ([1](https://github.com/SamiPerttu/fundsp), [2](https://github.com/SamiPerttu/fundsp/blob/master/CHANGES.md#version-08)) - 🆓 **free** (@SamiPerttu?)
- [x] hot-lib-reloader-rs ([1](https://github.com/rksm/hot-lib-reloader-rs)) - ✔️ done
- [ ] bevy_ecs_tilemap ([1](https://github.com/StarArawn/bevy_ecs_tilemap)) - 🆓 **free** (@StarArawn?)
- [ ] grid_pathfinding ([1](https://github.com/tbvanderwoude/grid_pathfinding)) - 🆓 **free** (@tbvanderwoude?)

## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @AngelOnFira
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @AngelOnFira
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @AngelOnFira
- [ ] Add a draft of next month's newsletter - by @AngelOnFira

**Comment by 64kramsystem** [comment]
I'm adding a `Game Updates` entry for the Catacomb II port :smile:

**Comment by RobDavenport** [comment]
I'll take `Engine Updates - Gamercade` again this week.

**Comment by not-fl3** [comment]
Not listed, but I'll post a miniquad update tomorrow  :)

**Comment by ollej** [comment]
I’ll writw something about Infinite Bunner. And maybe Rusty Aquarium as well.

**Comment by cart** [comment]
I'll take Bevy's update (and Bevy Jam)

**Comment by zakarumych** [comment]
I'll write about Edict

**Comment by jjant** [comment]
Hey there, I just found out about this newsletter. I'll write something about Runty8 (though it's in very early WIP stages).

**Comment by Nazariglez** [comment]
Added Notan v0.6, thanks!

**Comment by RobDavenport** [comment]
PR Up for Gamercade. Thanks!

**Comment by anopara** [comment]
Country Slice -> Tiny Building Game 😅 figured I'd better call it like we do in twitter/newsletter/etc :3
