### ISSUE TITLE
Newsletter 38 - September 2022

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/rust-gamedev.github.io#1157]
# Newsletter 38: September 2022

###### tags: `newsletter`

**Editors:** @17cupsofcoffee, @ozkriff, and @AngelOnFira

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with Septembers's news!

## Current Schedule

**The deadline for all section PRs is the 10th of October.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Rust Gamedev Meetup

- [ ] Rust Gamedev meetup - 🚧 WIP by @AngelOnFira

#### Game Updates

- [x] Ultimechs ([1](https://twitter.com/dimforge/status/1570360587544059906), [2](https://youtube.com/watch?v=nLCNsIs1-ZU), [3](https://www.resolutiongames.com/blog/calling-rust-from-c-in-unity), [4](https://www.resolutiongames.com/blog/programming-a-vr-game-using-rust), [5](https://store.steampowered.com/app/1657780/Ultimechs/)) - ✔️ done
- [x] Veloren ([1](https://veloren.net)) - ✔️ done
- [x] Flesh ([1](https://twitter.com/Im_Oab/status/1567828751966433283), [2](https://twitter.com/GReviewMonster/status/1565280510397628416), [3](https://twitter.com/Im_Oab/status/1571991898893721600), [4](https://twitter.com/Im_Oab/status/1573082223670349824), [5](https://twitter.com/Im_Oab/status/1575261410808180736), [6](https://twitter.com/Im_Oab/status/1573876865491931136)) - ✔️ done
- [ ] disk-0 Madness ([1](https://maxcurzi.itch.io/disk-0-madness), [2](https://github.com/maxcurzi/disk-0-madness)) - 🆓 **free** (@maxcurzi?)
- [ ] Combine And Conquer ([1](https://reddit.com/r/rust_gamedev/comments/x4qyc0/id_like_to_thank_the_rust_community_by_giving/), [2](https://buckmartin.de/combine-and-conquer/2022-09-23-v0.1.0.html)) - 🆓 **free** (@I3ck?)
- [ ] bevy-rapier-car-sim ([1](https://github.com/alexichepura/bevy-rapier-car-sim), [2](https://twitter.com/alexichepura/status/1566281624945410048)) - 🆓 **free** (@alexichepura?)
- [ ] Cyber Gate ([1](https://reddit.com/r/rust_gamedev/comments/x60n9y/cybergate_4_5), [2](https://reddit.com/r/rust_gamedev/comments/xatx9g/implemented_reliability_over_webrtc_browser), [3](https://reddit.com/r/rust_gamedev/comments/xo03s5/cybergate_release_5_webrtc_multiplayer_with)) - 🆓 **free** (@cybersoulK?)
- [x] tiny building game ([1](https://twitter.com/anastasiaopara/status/1565629377823395841), [2](https://twitter.com/anastasiaopara/status/1575049506449563648), [3](https://twitter.com/h3r2tic/status/1573747327751360512?)) - ✔️ done
- [ ] another game of life ([1](https://reddit.com/r/rust/comments/x6w13x/media_conways_game_of_life)) - 🆓 **free** (@Behemoth11?)
- [ ] unbeatable pong ([1](https://reddit.com/r/bevy/comments/xrqywe/i_made_an_unbeatable_pong)) - 🆓 **free** (@larsdu?)
- [ ] ~~Shadow of Ragnarök ([1](https://reddit.com/r/rust_gamedev/comments/xa54yw/no_more_voxels_going_open_soure_game_status_update), [2](https://twitter.com/heavyrain266/status/1569987189412339714))~~
- [x] eo.rs ([1](https://eo-rs.dev/blog/discoveries-and-broken-shit/), [2](https://eo-rs.dev/blog/speech-and-stats/)) - ✔️ done
- [x] Graviton ([1](https://reddit.com/r/rust_gamedev/comments/xfqd2t/graviton_relaxing_sand_art), [2](https://store.steampowered.com/app/2137280/Graviton__A_Relaxing_Sand_Simulation)) - ✔️ done
- [ ] ostwilkens's roguelite ([1](https://twitter.com/ostwilkens/status/1573682944878821377)) - 🆓 **free** (@ostwilkens?)
- [x] Thetawave ([1](https://twitter.com/carlosupina/status/1572976552165474307)) - ✔️ done
- [ ] Life Code ([1](https://youtube.com/watch?v=ftVkklmO1Dk&ab_channel=LifeCode)) - 🆓 **free** (@pinkponk?)
- [ ] Klod ([1](https://devildahu.ch/devlog/making-of-klod-tech/)) - 🆓 **free** (@devildahu?)
- [ ] Subfuse ([1](https://dgriffin.itch.io/subfuse/devlog/422315/subfuse-postmortem)) - 🆓 **free** (@DGriffin91?)

#### Engine Updates

- [x] godot-rust ([1](https://twitter.com/GodotRust/status/1565406286778351616), [2](https://twitter.com/GodotRust/status/1566110873940381696)) - ✔️ done
- [ ] fyrox ([1](https://rustacean-station.org/episode/dmitry-stepanov), [2](https://reddit.com/r/rust_gamedev/comments/x8wv7i/fyrox_book_new_article_property_inheritance)) - 🆓 **free** (@mrdimas?)
- [ ] unreal-rust ([1](https://twitter.com/MaikKlein_DEV/status/1566474392342757377)) - 🆓 **free** (@MaikKlein?)
- [x] Gamercade ([1](https://reddit.com/r/rust_gamedev/comments/x8asrd/audio_synthesis_at_runtime_this_week_at_gamercade), [2](https://reddit.com/r/rust_gamedev/comments/xjcdbd/announcing_gamercade_01), [3](https://gamercade.io/blog)) - ✔️ done
- [x] Dims ([1](https://reddit.com/r/rust_gamedev/comments/xr8fh7/were_working_on_a_new_wasmrust_scripting_system)) - ✔️ done
- [ ] Bevy ([1](https://twitter.com/cart_cart/status/1573411922258857984), [2](https://github.com/bevyengine/rfcs/pull/45)) - 🆓 **free** (@cart?)

#### Learning Material Updates

- [x] Making a turn-based multiplayer game in Rust ([1](https://herluf-ba.github.io/)) - ✔️ done
- [ ] Rust Bevy Entity Component System ([1](https://blog.logrocket.com/rust-bevy-entity-component-system)) - 🆓 **free** (@killercup?)
- [ ] Native iOS Game Development w/ Rust ([1](https://devmap.org/native-ios-game-development-w-rust-a1134887c35f)) - 🆓 **free** (@wadez?)
- [ ] Rust and Tell - Berlin - Hot code reload in Rust by Robert Krahn ([1](https://youtube.com/watch?v=-UUImyqX8j0)) - 🆓 **free** (@rksm?)
- [ ] Bevy Basics video series ([1](https://youtube.com/playlist?list=PL6uRoaCCw7GN_lJxpKS3j-KXuThRiSXc6)) - 🆓 **free** (@PhaestusFox?)
- [x] Chris Biscardi videos ([1](https://twitter.com/chrisbiscardi/status/1575151875241828354)) - ✔️ done
- [ ] Code Asteroids with a First-Time Bevy User ([1](https://reddit.com/r/rust/comments/x9rwrx/lets_code_asteroids_in_rust_with_a_firsttime_bevy)) - 🆓 **free** (@yishn?)

#### Tooling Updates

- [x] Feldversuch ([1](https://siebencorgie.rs/gallery/feldversuch/), [2](https://twitter.com/siebencorgie/status/1568318987234164737)) - ✔️ done
- [ ] ~~Bloom3D ([1](https://twitter.com/kettlecorn/status/1569491858484756481))~~

#### Library Updates

- [ ] egui_dock ([1](https://crates.io/crates/egui_dock)) - 🆓 **free** (@Adanos020?)
- [ ] Valence ([1](https://reddit.com/r/rust/comments/x5941i/valence_a_rust_framework_for_minecraft)) - 🆓 **free** (@rj00a?)
- [ ] particular ([1](https://reddit.com/r/rust/comments/x7uhoq/particular_a_simple_library_for_nbody_grav)) - 🆓 **free** (@Canleskis?)
- [ ] luminance ([1](https://reddit.com/r/rust_gamedev/comments/x785tw/luminance_redesign_part_1_compatible_vertex_types)) - 🆓 **free** (@phaazon?)
- [x] particular ([1](https://github.com/Canleskis/particular), [2](https://reddit.com/r/rust/comments/x7uhoq/media_particular_a_simple_library_for_nbody)) - ✔️ done
- [x] polyanya ([1](https://twitter.com/FrancoisMockers/status/1574437086828134405), [2](https://github.com/vleue/polyanya)) - ✔️ done
- [ ] bevy_ecss ([1](https://github.com/afonsolage/bevy_ecss)) - 🆓 **free** (@afonsolage?)
- [x] bevy_oddio v0.2 ([1](https://github.com/harudagondi/bevy_oddio/blob/main/CHANGELOG.md#020---2022-09-04)) - ✔️ done
- [ ] dtm ([1](https://github.com/Ku95/dtm)) - 🆓 **free** (@Ku95?)
- [x] big-brain v0.14 ([1](https://discord.com/channels/691052431525675048/918591326096850974/1023456718488862770)) - ✔️ done
- [ ] ~~bevy_mod_fbx ([1](https://github.com/HeavyRain266/bevy_mod_fbx))~~

#### Other News

- [ ] Bullet points of any interesting news that doesn't have its own section - 🆓 **free** (@username?)

#### Discussions

- ["Should I use an existing physics engine or implement it myself?"](https://reddit.com/r/rust_gamedev/comments/x8if87/rubber_duck_question_should_i_use_an_existing)
- ["Ecs fundamentally at odds with borrow checker"](https://reddit.com/r/rust_gamedev/comments/xajcgd/ecs_fundamentally_at_odds_with_borrow_checker)
- ["Best Engine for Choice-Driven, Semi-Free-Roam, 2D Gamedev"](https://reddit.com/r/rust_gamedev/comments/xc0fes/best_engine_for_choicedriven_semifreeroam_2d)
- ["Turn-based game - architecture feedback/opinons"](https://reddit.com/r/rust_gamedev/comments/xe1d6p/turnbased_game_architecture_feedbackopinons)

#### Bonus

- [ ] ruffle ([1](https://ruffle.rs)) - 🆓 **free**

## Publishing Steps

- [x] Final review - by everyone
- [x] Publish - by @17cupsofcoffee
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @17cupsofcoffee
- [x] Pin thread on Twitter - by @ozkriff
- [x] Add comment links - by @17cupsofcoffee
- [x] Add a draft of next month's newsletter - by @17cupsofcoffee

**Comment by zkat** [comment]
awesome! This is tempting, and while big-brain 0.14 is significant, I don't think there's anything mind-blowing about it besides a bit of improvement in practicality. Maybe next time I do something big, though ;)

**Comment by HeavyRain266** [comment]
Could we remove my game and fbx plugin for bevy?

I don't really have time to write about the game because I'm currently focused on adding upstream xbox target to the compiler. Also I think, nothing in the plugin changed since last newsletter where it was present.

**Comment by SiebenCorgie** [comment]
*Feldversuch* is technically not a game but a synthesizer. But it uses a lot of game tech and a gamified interaction design. If that's okay for the newsletter I'd be happy to contribute a section about it.

**Comment by ChristopherBiscardi** [comment]
Happy to take on the stuff I'm mentioned on.

**Comment by phaazon** [comment]
I will probably try to get involved more into that newsletter. The link for `luminance` is correct, I will read the contributing guide when I have some time to sketch something up if no one has done it already.

**Comment by Bromeon** [comment]
I can do godot-rust. Since it's already the 4th and I released two versions on 2nd of October, would it be OK to include those?

Otherwise those would likely need to wait ~5 weeks until release of October newsletter, and by that time we hopefully have a first GDExtension around 😉

**Comment by herluf-ba** [comment]
I am happy to write a bit about the article I'm mentioned on

**Comment by harudagondi** [comment]
Hello, I'm open to writing the article I am mentioned on.

**Comment by philpax** [comment]
Yep, happy to claim Dims! Will have that in soon 🙂

**Comment by kettle11** [comment]
I'm going to skip the update for Bloom3D because I don't feel it's substantial enough to merit an inclusion in the newsletter.  But as always I appreciate the inclusion! Thanks!

**Comment by rj00a** [comment]
I'll take Valence :)

**Comment by Ku95** [comment]
My crate dtm is not ready for a showcase yet, but thanks for the inclusion.

**Comment by vilcans** [comment]
I think I can write something about Ultimechs, but not before the deadline of September 10th as I don't have a time machine.

**Comment by 17cupsofcoffee** [comment]
> I think I can write something about Ultimechs, but not before the deadline of September 10th as I don't have a time machine.

whoops, fixed

**Comment by 17cupsofcoffee** [comment]
Lots of stuff to reply to 😅 

@zkat: That's totally fine! We can either include 0.14 in the [link dump at the end of the newsletter](https://gamedev.rs/news/035/#other-news), or if you'd prefer, I can just leave it out this month altogether.

@HeavyRain266: No prob, will remove.

@SiebenCorgie: That's fine - maybe it would make more sense in the 'tooling' section instead of the games section? Up to you :)

@Bromeon: I'm fine with that, given it's only a few days into the month :+1:

@kettle11: No problem, will skip it this month!

**Comment by Canleskis** [comment]
Will write about Particular 🙂

**Comment by cdsupina** [comment]
I will take Thetawave.

**Comment by Nazariglez** [comment]
Hello! Notan is not on the list, but last month we released v0.7 with some improvements, fixes, and a new feature that allow loading HTML image elements easily. I would like to include it in the newsletter if possible, thanks!

**Comment by sorokya** [comment]
I can write about eo.rs :)

**Comment by 17cupsofcoffee** [comment]
Aiming to get the newsletter released tomorrow if I can - last call for submissions :)

**Comment by 17cupsofcoffee** [comment]
Final review PR: https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1178
