### ISSUE TITLE
Newsletter 39: October 2022

### ISSUE THREAD

**Issue by AngelOnFira** [rust-gamedev/rust-gamedev.github.io#1180]
# Newsletter 39: October 2022

###### tags: `newsletter`

**Editors:** @17cupsofcoffee, @ozkriff, and @AngelOnFira

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with TODO's news!

## Current Schedule

**The deadline for all section PRs is 5th of Nov.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Announcements

- [ ] Rust Gamedev meetup - 🚧 WIP by @AngelOnFira
- [ ] Rust GameDev Discord server got #projects forum  - 🆓 **free**

#### Game Updates

- [ ] Veloren ([1](https://veloren.net)) - 🚧 WIP by @AngelOnFira
- [ ] Yomi Hustle (TAS Fighter) ([1](https://twitter.com/ivy_sly_)) - 🆓 **free** (@uzkbwza?)
- [ ] miam LD51 ([1](https://ldjam.com/events/ludum-dare/51/miam)) - 🆓 **free** (@yopox?)
- [ ] ThousandthStar's devlog ([1](https://dev.to/thousandthstar/series/19842), [2](https://twitter.com/fronkongames/status/1576467228446392322)) - 🆓 **free** (@ThousandthStar?)
- [ ] TheGrimsey's deblog ([1](https://twitter.com/TheGrimsey/status/1580616420676628480), [2](https://thegrimsey.net/2022/10/13/Bevy.html), [3](https://thegrimsey.net/2022/10/15/Bevy-Part-Two.html)) - 🆓 **free** (@TheGrimsey?)
- [ ] Tiny building game ([1](https://twitter.com/h3r2tic/status/1578125088280530946))[ - 🆓 **free**](https://youtu.be/GtRo-eF8-TE) (@anopara?)
- [ ] Embark’s Creative Playground ([1](https://medium.com/embarkstudios/embarks-creative-playground-call-for-early-players-2e1d56d21ede), [2](https://twitter.com/EmbarkStudios/status/1585952113917825024)) - 🆓 **free** (@repi?)
- [ ] Combine And Conquer ([1](https://reddit.com/r/rust_gamedev/comments/ycdg06/combine_and_conquer_020_is_now_released), [2](https://martinbucksoftware.itch.io/combine-and-conquer/devlog/443652/version-021-now-with-demo)) - 🆓 free (@I3ck?)
- [ ] r-vust ([1](https://twitter.com/Seth_VII/status/1586779203357315073), [2](https://sethmaddev.itch.io/rvust)) - 🆓 **free**
- [ ] vetovoima ([1](https://twitter.com/MatiasKlemola/status/1584845794427146241)) - 🆓 **free** (@klemola?)
- [ ] Tomb Explorer Game ([1](https://youtube.com/watch?v=z8DCqoxHtDs), [2](https://twitter.com/thlorenz/status/1582383740134645761)) - 🆓 **free** (@thlorenz?)
- [ ] Tantan's Voxel Project (?) ([1](https://youtube.com/watch?v=2-pXntcUWfM)) - 🆓 **free** (@tantandev?)
- [ ] Fish Folk: Punchy ([1](https://reddit.com/r/rust/comments/y21vge/media_fish_folk_punchy_v01_first_mvp)) - 🆓 **free** (@erlend-sh?)
- [ ] Bungo Drifter ([1](https://mungbungo.itch.io/bungo-drifter), [2](https://twitter.com/mungbungo/status/1582319376950505472)) - 🆓 **free**
- [ ] Rusty Vangers ([1](https://reddit.com/r/rust_gamedev/comments/yicr23/driving_through_the_voxel_grid_in_vangers)) - 🆓 **free** (@kvark?)
- [ ] RainyCloud ([1](https://store.steampowered.com/app/1343230/RainyCloud/), [2](https://reddit.com/r/rust/comments/ygim8h/rust_game_dev_a_post_mortem_game)) - 🆓 **free** (@inosms?)
- [ ] Life Code ([1](https://www.youtube.com/watch?v=S2jxKva4n1U)) \- 🆓 **free** (@pinkponk?)

#### Learning Material Updates

- [ ] Rustacean Station: Forest ([1](https://rustacean-station.org/episode/forest-anderson/), [2](https://twitter.com/Plangora/status/1578316727510831105)) - 🆓 **free** (@AngelOnFira @allenwyma?)
- [ ] Building a frame data website in Rust ([1](https://twitter.com/thisIsRukai/status/1580377726925836288), [2](https://youtube.com/watch?v=g4Xqf2MFXpk)) - 🆓 **free** (@rukai?)
- [ ] Learning wgpu wiki page ([1](https://twitter.com/wumpf/status/1581562168629022720)) - 🆓 **free** (@wumpf?)
- [ ] Learn wgpu ([1](https://reddit.com/r/rust_gamedev/comments/y9gaqk/learn_wgpu_updated_to_014)) - 🆓 **free** (@sotrh?)
- [ ] Psycho Pong Tutorial 1 ([1](http://www.littleboxesgames.fr/posts/psycho-pong-part-one/), [2](https://twitter.com/LB0xes/status/1583316988780507136))- 🆓 **free** (@LittleB0xes?)
- [ ] GDC21 Rust for Game Tooling ([1](https://youtu.be/GtRo-eF8-TE)) - 🆓 **free** (@olson-dan?)
- [ ] Making an ECS WebAssembly Game with Bevy ([1](https://dublog.net/blog/rust-2/)) - 🆓 **free** (@LarsDu?)
- [ ] wgpu-openxr-example ([1](https://github.com/philpax/wgpu-openxr-example), [2](https://reddit.com/r/rust_gamedev/comments/ybv5f2/wgpuopenxrexample_a_barebones_example)) - 🆓 **free** (@philpax?)
- [ ] Primitive Geometry in wgpu&Rust ([1](https://dev.to/whoisryosuke/primitive-geometry-in-wgpu-and-rust-1da1), [2](https://twitter.com/whoisryosuke/status/1582031429986406400)) - 🆓 **free** (@stoneddesigner?)
- [ ] Bevy Basics video series ([1](https://youtube.com/playlist?list=PL6uRoaCCw7GN_lJxpKS3j-KXuThRiSXc6)) \- 🆓 **free** (@PhaestusFox?)

#### Engine Updates

- [ ] ggez v0.8.0 ([1](https://reddit.com/r/rust_gamedev/comments/xvm9eb/ggez_080rc1)) - 🆓 **free** (@nobbele?)
- [ ] Fyrox ([1](https://twitter.com/DmitryNStepanov/status/1579523268893380609), [2](https://reddit.com/r/rust/comments/y0kfbf/im_happy_to_announce_that_fyrox_game_engine_028), [3](https://reddit.com/r/rust/comments/y5fea4/media_sprite_sheet_frames_selector_for_fyrox), [4](https://fyrox-book.github.io/fyrox/serialization/index.html)) - 🆓 **free** (@mrdimas?)
- [ ] Pyxel ([1](https://twitter.com/kitao/status/1578669120416993280), [2](https://tkitao.hatenablog.com/entry/2022/10/08/174438)) - 🆓 **free** (@kitao?)
- [ ] miniquad ([1](https://twitter.com/fedor_games/status/1583497785302581249), [2](https://www.patreon.com/posts/73600033))- 🆓 **free** (@not-fl3?)

#### Tooling Updates

- [ ] Blackjack ([1](https://reddit.com/r/rust/comments/xy45qj/blackjack_the_rusty_procedural_3d_modeler), [2](https://twitter.com/PlayTheProcess/status/1580947479876759552)) - 🆓 **free** (@setzer22?)
- [ ] Modmapper ([1](https://www.hallada.net/2022/10/05/modmapper-putting-every-skyrim-mod-on-a-map-with-rust.html)) - 🆓 **free** (@thallada?)
- [ ] 3d Cellular Automata ([1](https://reddit.com/r/rust/comments/y6q98n/media_customizable_3d_cellular_automata), [2](https://github.com/LelsersLasers/3D-Cellular-Automata-WGPU)) - 🆓 **free** (@LelsersLasers?)
- [ ] vismut v0.6 ([1](https://orsvarn.com/vismut-0-6/)) - 🆓 **free** (@lukors?)

#### Library Updates

- [ ] psx-sdk-rs for PS1 ([1](https://github.com/ayrtonm/psx-sdk-rs), [2](https://github.com/rust-lang/rust/pull/102689)) - 🆓 **free** (@ayrtonm?)
- [ ] wgpu v0.14, naga v0.10 ([1](https://github.com/gfx-rs/wgpu/releases/tag/v0.14.0)) - 🆓 **free** (@cwfitzgerald?)
- [ ] gba v0.8, v0.9 ([1](https://github.com/rust-console/gba/blob/main/CHANGELOG.md)) - 🆓 **free** (@Lokathor?)
- [ ] MarpII ([1](https://twitter.com/siebencorgie/status/1576620921464360960), [2](https://siebencorgie.rs/posts/marpii-rmg/)) - 🆓 **free** (@siebencorgie?)
- [ ] Hanabi ([1](https://github.com/djeedai/bevy_hanabi), [2](https://twitter.com/djeedai/status/1576549833694859266), [3](https://twitter.com/djeedai/status/1579954825948958721)) - 🆓 **free** (@djeedai?)
- [ ] presser ([1](https://github.com/EmbarkStudios/presser), [2](https://twitter.com/fu5ha/status/1581705656218062848)) - 🆓 **free** (@fu5ha?)
- [ ] glutin 0.30 ([1](https://github.com/rust-windowing/glutin/releases/tag/v0.30.0)) - 🆓 **free** (@kchibisov?)
- [ ] quinn v0.9 ([1](https://github.com/quinn-rs/quinn/releases/tag/0.9.0)) - 🆓 **free** (@djc?)
- [ ] iyes_loopless v0.8 ([1](https://github.com/IyesGames/iyes_loopless), [2](https://twitter.com/IyesGames/status/1585975134170468352)) - 🆓 **free** (@inodentry?)
- [ ] leafwing_abilities ([1](https://twitter.com/AliceICecile/status/1582169655460114433), [2](https://github.com/leafwing-studios/leafwing_abilities)) - 🆓 **free** (@alice-i-cecile?)
- [ ] dualquat ([1](https://github.com/knickish/dualquat)) - 🆓 **free** (@knickish?)
- [ ] seldom_state ([1](https://twitter.com/Seldom_SE/status/1581696118064177152), [2](https://github.com/Seldom-SE/seldom_state)) - 🆓 **free** (@Seldom-SE?)
- [ ] seed_creator ([1](https://reddit.com/r/rust_gamedev/comments/yaw82r/random_seed_creation_showcase_for_wasm4_fantasy)) - 🆓 **free**
- [ ] bevy-hikari ([1](https://github.com/cryscan/bevy-hikari)) - 🆓 **free** (@cryscan?)
- [ ] bevy_ecs_tilemap v0.8 ([1](https://github.com/StarArawn/bevy_ecs_tilemap/releases/tag/v0.8.0)) - 🆓 **free** (@StarArawn?)
- [ ] bevy_mod_mesh_tools ([1](https://github.com/DGriffin91/bevy_mod_mesh_tools)) - 🆓 **free** (@DGriffin91?)

#### Other News

- [ ] other news - 🚧 WIP by @17cupsofcoffee

#### Discussions

- [ ] ["SDL2 vs Winit/Pixels/CPAL/etc. Is going "native" really worth it?"](https://reddit.com/r/rust_gamedev/comments/xyjdy5/sdl2_vs_winitpixelscpaletc_is_going_native)
- [ ] ["What's the best 2D engine like pygame, but for Rust?"](https://reddit.com/r/rust_gamedev/comments/y72as6/whats_the_best_2d_engine_like_pygame_but_for_rust)
- [ ] ["Best way to draw massive amount of individual pixels every frame"](https://reddit.com/r/rust_gamedev/comments/xz642j/falling_sand_simulation_best_way_to_draw_pixels)

#### Bonus

- [ ] Book: Practical GPU Graphics with wgpu and Rust ([1](https://www.amazon.com/dp/B09QP6Q8QC)) - 🆓 **free** (@17cupsofcoffee?)

## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @17cupsofcoffee
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @17cupsofcoffee
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @17cupsofcoffee
- [ ] Add a draft of next month's newsletter - by @17cupsofcoffee

**Comment by philpax** [comment]
I'll take wgpu-openxr-example :)

**Comment by fu5ha** [comment]
Took `presser` in #1182

**Comment by SiebenCorgie** [comment]
I'll take MarpII :)

**Comment by ThousandthStar** [comment]
Took `ThousandthStar's devlog` in #1184

**Comment by zicklag** [comment]
I'll take [Jumpy](https://github.com/fishfolks/jumpy).

**Comment by kchibisov** [comment]
I'll add notes about the glutin.

**Comment by setzer22** [comment]
I'll take blackjack :+1:

**Comment by Wumpf** [comment]
I'll write a short bit on the `Learning wgpu wiki page ([1](https://twitter.com/wumpf/status/1581562168629022720)) - 🆓 free (@Wumpf?)`

**Comment by djeedai** [comment]
I can take Hanabi, thanks!

**Comment by Indy2222** [comment]
I would like to write an update about Digital Extinction (https://mgn.cz/blog/de01/).

**Comment by sotrh** [comment]
I'll take the Learn Wgpu section

**Comment by ThousandthStar** [comment]
Done. #1193

**Comment by Seldom-SE** [comment]
Took `seldom_state` in #1194

**Comment by Keavon** [comment]
Working on Graphite's section today.

**Comment by klemola** [comment]
vetovoima's done in #1196

**Comment by 17cupsofcoffee** [comment]
Release PR is up: #1200

Apologies for the delay, the entire editorial team is either busy, ill, or busy *and* ill this month... 😅
