### ISSUE TITLE
Main page icons appearance

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#12]
Quoting from https://github.com/rust-gamedev/rust-gamedev.github.io/issues/4:

> @ozkriff:
> Maybe the background shouldn't be blue? Or the emojis should be removed/changed. It looks a little bit weird with red emojis without an outline of my system's font:
>
> ![](https://user-images.githubusercontent.com/662976/63150270-0ad0a880-c00f-11e9-83b8-256bb7845faa.png)
>
> @17cupsofcoffee:
> Hm, yeah, that's unfortunate - on Windows 10 they have nice black borders:
>
> ![](https://user-images.githubusercontent.com/784533/63210397-ad5b5b00-c0e5-11e9-8a24-ee0f3e667718.png)
>
> If we can't rely on them looking vaguely consistent across platforms, they should probably be removed/replaced. I only really put them there because I was jealous of the WASM WG's hard-hat Ferris :p
>
> I'm not particularly attached to the blue either, picking out color schemes has never really been my strong suit. As long as whatever we choose passes the Chrome accessibility audit, I'm happy.
>
> @zicklag:
> I think you should be able to make the display consistant if you provide a downloadable font and set that as the font-family. That way every system uses the same icons instead of each one using its system default.
>
> Also, there might be a way to extract the SVG from a font and put SVG icons in there instead.

**Comment by 17cupsofcoffee** [comment]
I might have a go at sorting this out tonight 🙂 There's several open source emoji projects that would fit with the licenses we're already using, so I should just be able to grab those SVGs and add them to the existing file.

That or I could try to hack together an appropriately themed Ferris along the lines of what the WASM group have - not sure if my artistic talents (or lack thereof) stretch that far, though 😛

**Comment by 17cupsofcoffee** [comment]
Sent a PR to switch to some third party icons in SVG form: #13
