### ISSUE TITLE
The link to Bevy's "good first issue" is broken

### ISSUE THREAD

**Issue by nicopap** [rust-gamedev/rust-gamedev.github.io#1202]
In edition nº39, I found that clicking the link to bevy good first issue led to https://github.com/bevyengine/bevy/labels/E-Good-First-Issue . You may notice there is no open issue. 

This is because the tag bevy uses for good first issues is `D-Good-First-Issue`, not `E-Good-First-Issue`, the link should be replaced by https://github.com/bevyengine/bevy/labels/D-Good-First-Issue

**Comment by 17cupsofcoffee** [comment]
Fixed, thanks!
