### ISSUE TITLE
Newsletter 40: November 2022

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#1203]
# Newsletter 40: November 2022

###### tags: `newsletter`

**Editors:** @ozkriff, @AngelOnFira, and @17cupsofcoffee

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with TODO's news!

## Current Schedule

**The soft deadline for all section PRs is 4 Dec.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Announcements

- [ ] Rust Gamedev meetup - 🚧 WIP by @AngelOnFira

#### Game Updates

- [ ] Veloren ([1](https://veloren.net)) - 🚧 WIP by @AngelOnFira 
- [ ] Yomi Hustle ([1](https://twitter.com/ivy_sly_)) - 🆓 **free** (@uzkbwza?)
- [ ] Tantan’s Voxel Project ([1](https://youtube.com/watch?v=54D6hgui2Kc), [2](https://youtube.com/watch?v=EFzFHrzIiz8)) - 🆓 **free** (@TanTanDev?)
- [ ] Combine And Conquer ([1](https://reddit.com/r/rust_gamedev/comments/yk9onb/the_two_year_development_progress_of_my_cnc), [2](https://youtube.com/watch?v=fpl2W5OXVH8), [3](https://reddit.com/r/rust_gamedev/comments/z1z5j3/i_just_released_version_030_of_cnc), [4](https://youtube.com/watch?v=jWyQrsjTq0g)) - 🆓 **free** (@I3ck?)
- [ ] Crispy's Automation RL ([1](https://youtube.com/watch?v=QvBinznAYqY)) - 🆓 **free** (@0crispy?)
- [ ] Idu ([1](https://twitter.com/epcc10/status/1589809036270403585), [2](https://youtube.com/watch?v=yyicR63hZ0o)) - 🆓 **free** (@johann2?)
- [ ] vange.rs ([1](https://reddit.com/r/rust_gamedev/comments/ypf38k/description_of_the_voxel_tracing_in_rusty_vangers)) - 🆓 **free** (@kvark?)
- [ ] gssa-rs ([1](https://github.com/devildahu/gssa-rs), [2](https://devildahu.ch/devlog/gba-c-to-rust), [3](https://devildahu.ch/devlog/gba-c-to-rust-2)) - 🆓 **free** (@devildahu?)
- [ ] Scummstreets ([1](https://ratwizard.dev/dev-log/scummstreets), [2](https://twitter.com/RatWizardDev/status/1592011864866951169)) - 🆓 **free** (@dooskington?)
- [ ] 8bit-duels ([1](https://github.com/ThousandthStar/8bit-duels), [2](https://dev.to/thousandthstar/start-of-the-game-development-blog-series-p42)) - 🚧 WIP by @ThousandthStar
- [x] Space Frontiers ([1](https://starwolves.io/showthread.php?tid=1), [2](https://github.com/starwolves/space)) - ✔️ done by @starwolfy
- [x] Timely Defuse ([1](https://github.com/Enet4/timely-defuse)) - ✔️ done by @Enet4
- [ ] Jumpy - 🚧 WIP by @zicklag
- [x] Rusty Vangers - ✔️ done by @kvark
- [x] Digital Extinction - ✔️ done by Indy2222

#### Learning Material Updates

- [ ] Render Pipelines in wgpu ([1](https://dev.to/whoisryosuke/render-pipelines-in-wgpu-and-rust-2dh3), [2](https://mastodon.gamedev.place/@whoisryosuke/109368541387510472)) - 🆓 **free** (@whoisryosuke?)
- [ ] Embark: Evaluating health&quality of crates ([1](https://mastodon.gamedev.place/@repi/109376956600948102), [2](https://gist.github.com/repi/d98bf9c202ec567fd67ef9e31152f43f)) - 🆓 **free** (@repi?)
- [ ] bevy+rapier ([1](https://youtube.com/watch?v=GwlZ5EPu8l0)) - 🆓 **free** (@mwbryant?)

#### Engine Updates

- [ ] Bevy v0.9 ([1](https://twitter.com/cart_cart/status/1591543728233385984), [2](https://reddit.com/r/rust/comments/ytiv2a/bevy_09), [3](https://reddit.com/r/gamedev/comments/ytiv4o/bevy_09_data_oriented_game_engine_built_in_rust)) - 🆓 **free** (@cart?)
- [ ] Hotham ([1](https://youtube.com/watch?v=C8XzNnhELtk)) - 🆓 **free** (@leetvr?)
- [ ] emerald ([1](https://mastodon.gamedev.place/@clay/109292627799303779)) - 🆓 **free** (@Bombfuse?)
- [ ] fyrox ([1](https://reddit.com/r/rust/comments/ynq3mq/this_week_in_fyrox_game_engine_1), [2](https://twitter.com/DmitryNStepanov/status/1591817559661314049), [3](https://fyrox.rs/blog/post/twif3/)) - 🆓 **free** (@mrDIMAS?)
- [ ] godot-rust ([1](https://twitter.com/BromeonDev/status/1589279932735057921)) - 🚧 WIP by @Bromeon
- [ ] Alkahest ([1](https://github.com/AlkimiaStudios/alkahest-rs), [2](https://twitter.com/alkimia_studios/status/1595222326177632256), [3](https://reddit.com/r/rust_gamedev/comments/z27hec/i_recently_converted_my_inprogress_c_engine)) - 🆓 **free** (@AnthonyUtt?)
- [x] pixel ([1](https://reddit.com/r/rust_gamedev/comments/z3t6e9/check_out_my_simple_game_engine)) - ✔️ done by @maix0
- [ ] defold-rs ([1](https://forum.defold.com/t/writing-native-extensions-in-rust/71980)) - 🆓 **free** (@JustAPotota?)
- [ ] Eldiron ([1](https://twitter.com/UltimaCodex/status/1587837867052744709), [2](https://ultimacodex.com/2022/11/eldiron-engine-pre-release-version-0-7-now-available/)) - 🆓 **free** (@markusmoenig?)

#### Tooling Updates

- [ ] Blackjack ([1](https://twitter.com/Blackjack3dRust/status/1588247994008145921), [2](https://twitter.com/Blackjack3dRust/status/1588878304530300928)) - 🆓 **free** (@setzer22?)
- [ ] EuriHerasme's Terrain Gen ([1](https://mastodon.gamedev.place/@EuriHerasme/109368645008002886)) - 🆓 **free** (@eurigilberto?)
- [x] boytacean ([1](https://reddit.com/r/rust/comments/ywxugc/game_boy_emulator), [2](https://github.com/joamag/boytacean)) - ✔️ done by @joamag

#### Library Updates

- [ ] Iced ([1](https://reddit.com/r/rust/comments/yr0oe8/iced_gui_lib_new_release)) - 🆓 **free** (@hecrj?)
- [ ] dynec ([1](https://github.com/SOF3/dynec)) - 🆓 **free** (@SOF3?)
- [ ] kopi ([1](https://github.com/hasenbanck/kopi)) - 🆓 **free** (@hasenbanck?)
- [ ] guiedit ([1](https://github.com/aleokdev/guiedit)) - 🆓 **free** (@aleokdev?)
- [ ] Sparsey ([1](https://reddit.com/r/rust/comments/z1vwmp/sparsey_0100_release_gats)) - 🚧 WIP by @LechintanTudor
- [ ] Bevy Tweening ([1](https://twitter.com/djeedai/status/1592656570177163264)) - 🆓 **free** (@djeedai?)
- [ ] dungeon-generator ([1](https://github.com/MoutonSanglant/dungeon-generator), [2](https://twitter.com/vxdcxw/status/1593776255542988801)) - 🆓 **free** (@MoutonSanglant?)
- [ ] seldom_pixel ([1](https://github.com/Seldom-SE/seldom_pixel), [2](https://youtube.com/watch?v=pmTPdGxYVYw)) - 🚧 WIP by @Seldom-SE
- [ ] bevy_quickmenu ([1](https://github.com/terhechte/bevy_quickmenu), [2](https://twitter.com/terhechte/status/1593632564123762689)) - 🆓 **free** (@terhechte?)
- [ ] Notan ([1](https://reddit.com/r/rust_gamedev/comments/z7sr6r/notan_0_8)) - 🆓 **free** (@Nazariglez?)
- [ ] Taffy ([1](https://tech.lgbt/@alice_i_cecile/109399333226449807)) - 🆓 **free** (@alice-i-cecile?)
- [ ] bevy-hikari ([1](https://github.com/cryscan/bevy-hikari/releases/tag/v0.3.0)) - 🆓 **free** (@cryscan?)
- [ ] kayak_ui ([1](https://github.com/StarArawn/kayak_ui)) - 🆓 **free** (@StarArawn?)
- [ ] leafwing_input_playback ([1](https://github.com/Leafwing-Studios/leafwing_input_playback)) - 🆓 **free** (@alice-i-cecile?)
- [x] bevy-sequential-actions ([1](https://github.com/hikikones/bevy-sequential-actions)) - ✔️ done by @hikikones
- [x] bevy_atmosphere ([1](https://github.com/JonahPlusPlus/bevy_atmosphere)) - ✔️ done by @JonahPlusPlus
- [ ] bevy-vfx-bag ([1](https://github.com/torsteingrindvik/bevy-vfx-bag)) - 🚧 WIP by @torsteingrindvik

#### Other News

- [ ] Bullet points of any interesting news that doesn't have its own section - 🆓 **free** (@ozkriff?)

#### Discussions

- [ ] "Which graphics crate do you use?" ([1](https://reddit.com/r/rust_gamedev/comments/z1xy53/which_graphics_crate_do_you_use))
- [ ] "WASM For Core Game Loop & Mods ([1](https://reddit.com/r/rust_gamedev/comments/z5cl93/wasm_for_core_game_loop_mods_jumpy_devtalk))

#### Jobs

- [ ] Dims ([1](https://reddit.com/r/rust/comments/ymepy8/comment/iv9pajs)) - 🆓 **free** (@philpax?)
    
## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @ozkriff
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @ozkriff
- [ ] Add a draft of next month's newsletter - by @ozkriff

**Comment by Bromeon** [comment]
I'll gladly do godot-rust! 🤖🦀

**Comment by JonahPlusPlus** [comment]
I'm releasing bevy_atmosphere 0.5 today. Would it be fine to add it to November's newsletter?

**Comment by ozkriff** [comment]
@JonahPlusPlus sure, added to the plan

**Comment by Enet4** [comment]
I am interested in writing about my GitHub GameOff 2022 submission, [Timely Defuse](https://github.com/Enet4/timely-defuse). If it's OK, I should hopefully send a PR within the soft deadline.

**Comment by Maix0** [comment]
I wrote a little section about my engine (pixel engine) , feel free to add things/change the way it is written.

**Comment by joamag** [comment]
@ozkriff I've just added a small description of [Boytacean](https://github.com/joamag/boytacean) to the tools section.

**Comment by zicklag** [comment]
I'll take Jumpy.

**Comment by ThousandthStar** [comment]
I'll take 8bit-duels

**Comment by hikikones** [comment]
I can do `bevy-sequential-actions` 🙂

**Comment by starwolfy** [comment]
Thank you for the mention. I will get to writing for the section of the monthly letter for Space Frontiers!

**Comment by Seldom-SE** [comment]
I'll do `seldom_pixel`!

**Comment by LechintanTudor** [comment]
I'll take Sparsey 👋

**Comment by zicklag** [comment]
Found https://github.com/torsteingrindvik/bevy-vfx-bag yesterday. Looks pretty neat. Do you want to add a section for that @torsteingrindvik?

**Comment by torsteingrindvik** [comment]
> Found https://github.com/torsteingrindvik/bevy-vfx-bag yesterday. Looks pretty neat. Do you want to add a section for that @torsteingrindvik?

Sure, thanks! I'll do it within a few hours.

**Comment by philpax** [comment]
I'll write up the Dims job ad when I'm at work tomorrow!

**Comment by terhechte** [comment]
I'll do bevy_quickmenu today :)

**Comment by cryscan** [comment]
I'm happy to take `bevy-hikari`.

**Comment by JonahPlusPlus** [comment]
Added a section for bevy: #1224

**Comment by Dooskington** [comment]
I'll do `scummstreets` tomorrow :)

**Comment by Keavon** [comment]
Just saw this thread, beginning work now on the section for Graphite if there's still time. (Don't hold the presses for me though.) Is there any way to get included in the template each month?

**Comment by ozkriff** [comment]
It's out, sorry for another delay!

:tada: https://gamedev.rs/news/040 ([/r/rust_gamedev](https://reddit.com/r/rust_gamedev/comments/zqeq8i/this_month_in_rust_gamedev_40_for_november_2022), [Twitter](https://twitter.com/rust_gamedev/status/1605061212911403008), [Mastodon](https://mastodon.gamedev.place/@rust_gamedev/109544178943651668))

And as always huge thanks to all editors, contributors, and reviewers! :crab::crab:
