### ISSUE TITLE
Newsletter 41: Dec 2022

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#1233]
# Newsletter 41: Dec 2022

###### tags: `newsletter`

**Editors:** @ozkriff, @AngelOnFira, and @17cupsofcoffee

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with December's news!

## Current Schedule

**The soft deadline for all section PRs is 6 Jan 2023.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Rust Gamedev Meetup

- [x] Details of this month's meetup - ✔️ done by @AngelOnFira
- [x] 3rd Rust Graphics Meetup on Jan 28 ([1](https://reddit.com/r/rust_gamedev/comments/zrrp1l/the_third_rust_graphics_meetup_jan_28)) - ✔️ done by @AngelOnFira
- [x] rust_gamedev feed on Mastodon - ✔️ done by @ozkriff

#### Game Updates

- [x] Tiny Glade ([1](https://twitter.com/anastasiaopara/status/1600965331031232512), [2](https://twitter.com/anastasiaopara/status/1608437917537427457)) - ✔️ done by @anopara
- [x] Veloren ([1](https://veloren.net)) - ✔️ done by @AngelOnFira
- [ ] Red Life ([1](https://github.com/red-life-project/red-life), [2](https://reddit.com/r/rust/comments/zgv101/red_life_surviving_on_mars)) - 🆓 **free** (@Nereuxofficial?)
- [ ] flashdark ([1](https://kuviman.itch.io/flashdark), [2](https://twitter.com/kuviman/status/1598410936460738560)) - 🆓 **free** (@kuviman?)
- [ ] Doomé ([1](https://reddit.com/r/rust/comments/zbd8w2/doomé_our_raytracingbased_game), [2](https://reddit.com/r/rust/comments/zsrvss/strolle_raytracing)) - 🆓 **free** (@Dzejkop @Patryk27?)
- [ ] triverse ([1](https://cragwind.itch.io/triverse), [2](https://cragwind.itch.io/triverse/devlog)) - 🆓 **free** (@bcarruthers?)
- [ ] Tantan’s Voxel Project ([1](https://youtube.com/watch?v=PnwhUeyrQ54)) - 🆓 **free** (@TanTanDev?)
- [ ] Fish Folk: Punchy ([1](https://twitter.com/spicylobsterfam/status/1600122907572654080)) - 🆓 **free** (@erlend-sh?)
- [x] Fish Folk: Jumpy ([1](https://reddit.com/r/rust_gamedev/comments/zkqw3w/networking_in_fish_folk_jumpy), [2](https://reddit.com/r/rust/comments/zlxyrh/fish_folk_jumpy_v05_completed_mvp_of_bevy_rewrite)) - ✔️ done by @zicklag
- [ ] Combine And Conquer ([1](https://reddit.com/r/rust_gamedev/comments/zd96f1/my_automation_game_combine_and_conquer_steam), [2](https://buckmartin.de/combine-and-conquer.html)) - 🆓 **free** (@I3ck?)
- [x] Flesh ([1](https://twitter.com/Im_Oab/status/1600251480396926976), [2](https://twitter.com/Im_Oab/status/1607781800998473729)) - ✔️ done by @Im-Oab
- [ ] Paddlepunks ([1](https://twitter.com/sov_gott_games/status/1600958840220299266)) \- 🆓 **free** (@halvnykterist?)
- [x] Cargo Space ([1](https://mastodon.social/@johanhelsing/109592138584978251), [2](https://johanhelsing.studio/posts/cargo-space-devlog-0), [3](https://johanhelsing.studio/posts/cargo-space-devlog-1), [4](https://johanhelsing.studio/posts/cargo-space-devlog-2)) - ✔️ done by @johanhelsing
- [ ] Your Only Move Is Hustle ([1](https://twitter.com/ivy_sly_), [2](https://twitter.com/YourMoveHUSTLE), [3](https://twitter.com/YomiArena), [4](https://ivysly.itch.io/your-only-move-is-hustle/devlog/463593/name-change)) - 🆓 **free** (@uzkbwza?)
- [ ] Infinite Bunner ([1](https://hachyderm.io/@ollej/109506591357987042)) - 🆓 **free** (@ollej?)
- [x] Hydrofoil Generation ([1](https://twitter.com/HydrofoilG)) - ✔️ done by @kunos
- [x] Pirate Annihilation ([1](https://twitter.com/indiedevcasts/status/1605567037316571136)) - ✔️ done by @theredfish
- [ ] Pushin Boxes ([1](https://twitter.com/septum___/status/1606176677540683776)) - 🆓 **free** (@septum?)
- [ ] RetrosicII ([1](https://twitter.com/search?q=%23RetrosicII&src=hashtag_click&f=live), [2](https://enigmanark.blogspot.com/)) - 🆓 **free** (@enigmanark?)
- [x] Temple Knight ([1](https://twitter.com/nilay_savant/status/1607789552621727744)) - ✔️ done by @nilaysavant
- [x] Thetawave ([1](https://twitter.com/carlosupina/status/1609037460167598080), [2](https://twitter.com/carlosupina/status/1607824762721701889)) - ✔️ done by @cdsupina
- [ ] Life Code ([1](https://youtube.com/watch?v=miUD9Ni7LnQ)) \- 🆓 **free** (@pinkponk?)
- [x] Digital Extinction ([1](https://mgn.cz/blog/de03/)) - ✔️ done by @Indy2222
- [ ] A/B Street ([1](https://a-b-street.github.io/docs/project/history/vision_and_validate/index.html#whats-next-for-2023)) - 🆓 **free** (@dabreegster?)
- [x] Open Combat - ✔️ done by @buxx
- [x] 8bit Duels - ✔️ done by @ThousandthStar

#### Learning Material Updates

- [ ] GLTF Animations in wgpu&Rust ([1](https://mastodon.gamedev.place/@whoisryosuke/109508921482392957), [2](https://whoisryosuke.com/blog/2022/importing-gltf-with-wgpu-and-rust/)) - 🆓 **free** (@whoisryosuke?)
- [ ] Rustacean Station: Presser ([1](https://rustacean-station.org/episode/gray-olson/)) - 🆓 **free** (@fu5ha @allenwyma?)
- [ ] Create A Clicker Game With Macroquad ([1](https://dev.to/paper010/rust-create-a-clicker-game-with-macroquad-1820), [2](https://dev.to/paper010/part-2-create-a-clicker-game-with-rust-4nne)) - 🆓 **free** (@Paper010?)
- [ ] Raph: High Performance Rust UI ([1](https://youtube.com/watch?v=zVUTZlNCb8U), [2](https://reddit.com/r/rust/comments/z99nje/high_performance_rust_ui_talk)) - 🆓 **free**
- [ ] Text-based resources in Bevy ([1](https://maciejglowka.com/blog/text-based-json-toml-resources-in-bevy-engine), [2](https://twitter.com/maciek_glowka/status/1600232330874195968)) - 🆓 **free** (@maciekglowka?)
- [ ] Compute Shaders in Bevy ([1](https://youtube.com/watch?v=neyIpnII-WQ)) - 🆓 **free** (@mwbryant?)
- [ ] Pathfinding in Rust ([1](https://blog.logrocket.com/pathfinding-rust-tutorial-examples/)) - 🆓 **free** (@gregstoll?)
- [ ] Bevy Basics video series ([1](https://youtube.com/playlist?list=PL6uRoaCCw7GN_lJxpKS3j-KXuThRiSXc6)) - 🆓 **free** (@PhaestusFox?)

#### Engine Updates

- [x] fyrox ([1](https://fyrox.rs/blog)) - ✔️ done by @MrDimas
- [ ] alkahest-rs ([1](https://github.com/AlkimiaStudios/alkahest-rs), [2](https://youtube.com/@alkimiastudios/videos), [3](https://twitter.com/alkimia_studios))  - 🆓 **free**
- [ ] SquareWheel ([1](https://github.com/Panzerschrek/Square-Wheel), [2](https://reddit.com/r/rust/comments/zd31kv/media_software_renderer)) - 🆓 **free** (@Panzerschrek?)
- [x] runty8 ([1](https://reddit.com/r/rust/comments/zhyzj4/runty8_the_pico8_clone_in_rust_now_supports_wasm)) - ✔️ done by @jjant

#### Tooling Updates

- [x] Graphite - ✔️ done by @Keavon
- [ ] UCrowds real-time crowd sim ([1](https://reddit.com/r/rust_gamedev/comments/zvud5j/we_have_written_a_crowd_simulation_engine), [2](https://youtube.com/watch?v=KRzLaM5oAsg)) - 🆓 **free**

#### Library Updates

- [x] Mun v0.4 ([1](https://reddit.com/r/rust_gamedev/comments/zl1br8/mun_v0_4), [2](https://reddit.com/r/rust/comments/zky7sk/mun_v040)) - ✔️ done by @wodann
- [x] bevy_rapier_collider_gen ([1](https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1230)) - ✔️ done by @shnewto
- [ ] egui & eframe v0.20 ([1](https://twitter.com/ernerfeldt/status/1600869756491673600)) - 🆓 **free** (@emilk?)
- [ ] quad-svg ([1](https://github.com/macnelly/quad-svg)) - 🆓 **free** (@macnelly?)
- [ ] faer v0.4 ([1](https://github.com/sarah-ek/faer-rs), [2](https://users.rust-lang.org/t/release-faer-0-4-a-high-performance-linear-algebra-library/85715)) - 🆓 **free** (@sarah-ek?)
- [ ] durian ([1](https://github.com/spoorn/durian), [2](https://reddit.com/r/rust_gamedev/comments/zfsevq/durian)) - 🆓 **free** (@spoorn?)
- [x] egui_dnd ([1](https://github.com/lucasmerlin/egui_dnd), [2](https://reddit.com/r/rust/comments/zpo4w9/egui_dnd_drag_and_drop_sorting_for_egui)) - ✔️ done by @lucasmerlin
- [ ] mythoji ([1](https://twitter.com/MatanLurey/status/1605328940129624065)) - 🆓 **free** (@matanlurey?)
- [x] rust-gpu ([1](https://mastodon.gamedev.place/@repi/109552524432350838), [2](https://reddit.com/r/rust/comments/zrskiq/rustgpu_v04_released)) - ✔️ done by @oisyn
- [x] bevy_rpg ([1](https://github.com/project-flara/bevy-rpg)) - ✔️ done by @fianathedevgirl
- [ ] google/forma ([1](https://github.com/google/forma), [2](https://reddit.com/r/rust/comments/znhus1/github_googleforma_an_efficient_vectorgraphics)) - 🆓 **free**
- [ ] bevy_adventure ([1](https://github.com/hankjordan/bevy_adventure)) - 🆓 **free** (@hankjordan?)
- [ ] devices ([1](https://github.com/hankjordan/devices)) - 🆓 **free** (@hankjordan?)
- [x] Inox2d - ✔️ done by @fianathedevgirl
- [x] lpcg - ✔️ done by @buxx
- [x] assets_manager - ✔️ done by @a1phyr

#### Other News

- [x] Bullet points of sections that are still unclaimed - ✔️ done by @ozkriff

#### Discussions

- [x] Can a 2D game be made with rust without a game engine? ([1](https://reddit.com/r/rust_gamedev/comments/zrdsts/can_a_2d_game_be_made_with_rust_without_a_game/))
- [x] DataFrames instead of ECS? ([1](https://reddit.com/r/rust_gamedev/comments/zoea0b/what_if_we_use_dataframes_instead_of))

## Publishing Steps

- [x] Final review - ✔️ done by everyone
- [x] Publish - ✔️ done by @ozkriff
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, Twitter, Mastodon - ✔️ done by @ozkriff
- [x] Pin thread on Twitter - ✔️ done by @ozkriff
- [x] Add comment links - ✔️ done by @ozkriff
- [x] Add a draft of next month's newsletter - ✔️ done by @ozkriff

**Comment by Wodann** [comment]
I'll add it for Mun tomorrow 🙂

**Comment by fianathedevgirl** [comment]
Hiii!! Sent my two PRs. 👋

**Comment by buxx** [comment]
Hello, I would like to talk about "Open Combat" game (talked about in [NL 23](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/677)) and [lpcg](https://crates.io/crates/lpcg) crate (its new).

**Comment by ThousandthStar** [comment]
Hello, I'd like to add my game 8bit Duels's devlog https://thousandthstar.github.io/.

**Comment by kunos** [comment]
I will take Hydrofoil Generation

**Comment by cdsupina** [comment]
I'll add an entry for Thetawave, if there is still time.

**Comment by jjant** [comment]
I'll add an entry for Runty8 tomorrow if there's still time!

**Comment by Keavon** [comment]
Starting on Graphite now, should be ready tonight.

**Comment by oisyn** [comment]
I'll add a section on `rust-gpu` today.

**Comment by ozkriff** [comment]
Was going to make the final draft and release today but not feeling well, sorry. The final draft is 80% ready though so I'll post the final draft tomorrow - @jjant feel free to drop a PR with Runty8 meanwhile :)

**Comment by jjant** [comment]
@ozkriff Thank you! I've made a PR: #1260. Get better soon ⭐

**Comment by AngelOnFira** [comment]
I'm taking over the final review, if anyone has time to check out the final release, extra eyes would be appreciated! 🚀 

https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1262

**Comment by ozkriff** [comment]
Sorry for another delay with the release, had a rough couple of weeks, but it's finally out!

https://gamedev.rs/news/041  

As always, thanks to all editors, contributors, and reviewers! :crab::crab:

**Comment by theredfish** [comment]
Thanks @ozkriff !
