### ISSUE TITLE
Newsletter 42: Jan 2023

### ISSUE THREAD

**Issue by AngelOnFira** [rust-gamedev/rust-gamedev.github.io#1267]
# Newsletter 42: Jan 2023

###### tags: `newsletter`

**Editors:** @AngelOnFira, @ozkriff

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with TODO's news!

## Current Schedule

**The soft deadline for all section PRs is 10 Feb 2023.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Rust Gamedev Meetup

- [x] Details of this month's meetup - 🚧 WIP by @AngelOnFira

#### Game Updates

- [x] Veloren ([1](https://veloren.net)) - ✔️ done by @AngelOnFira
- [x] Hydrofoil Generation ([1](https://twitter.com/HydrofoilG)) - 🆓 **free** (@kunos?)
- [x] Tiny Glade ([1](https://twitter.com/anastasiaopara/status/1617925842163863554)) - 🆓 **free** (@anopara?)
- [x] Thetawave ([1](https://twitter.com/carlosupina/status/1611808954455146498)) - 🆓 **free** (@cdsupina?)
- [x] 8bit Duels ([1](https://reddit.com/r/rust_gamedev/comments/102kwgf/8bit_duels_devlog_part_5)) - 🆓 **free** (@ThousandthStar?)
- [x] Cargo Space ([1](https://johanhelsing.studio/posts/cargo-space-devlog-3), [2](https://mastodon.social/@johanhelsing/109756925706514312)) - ✔️ done by @johanhelsing
- [x] Combine And Conquer ([1](https://buckmartin.de/combine-and-conquer/2023-01-14-v0.4.0.html)) - 🆓 **free** (@I3ck?)
- [x] Your Only Move is Hustle ([1](https://store.steampowered.com/news/app/2212330/view/3645136358934530341)) - 🆓 free (@uzkbwza?)
- [x] Digital Extinction ([1](https://mgn.cz/blog/de04)) - ✔️ done by @Indy2222
- [x] TheGrimsey’s devlog ([1](https://twitter.com/TheGrimsey/status/1615788141314510848)) - 🆓 **free** (@TheGrimsey?)
- [x] Flesh ([1](https://twitter.com/Im_Oab/status/1616542479951724546), [2](https://twitter.com/Im_Oab/status/1619230923970736128)) - 🆓 **free** (@Im-Oab?)
- [x] DGS ([1](https://reddit.com/r/rust_gamedev/comments/10ifm62/dgs_the_multiplayer_game_of_go)) - 🆓 **free** (@Dominux?)
- [x] Idu ([1](https://mastodon.gamedev.place/@johann/109735538218868366), [2](https://mastodon.gamedev.place/@eli/109667066661932659), [3](https://mastodon.gamedev.place/@eli/109762347736213560), [4](https://mastodon.gamedev.place/@eli/109767230794849360)) - ✔️ done by @logicsoup
- [x] triverse ([1](https://cragwind.itch.io/triverse/devlog)) - 🆓 **free** (@bcarruthers?)
- [x] Combine And Conquer ([1](https://buckmartin.de/combine-and-conquer.html)) - 🆓 **free** (@I3ck?)
- [x] Fish Folk: Punchy ([1](https://reddit.com/r/rust_gamedev/comments/10qwgcn/fish_folk_punchy_v03)) \- 🆓 **free** (@erlend-sh?)
- [x] Life Code ([1](https://twitter.com/LifeCodeGame/status/1611856359003426816)) - 🆓 **free** (@pinkponk?)
- [x] digg ([1](https://reddit.com/r/rust_gamedev/comments/10of2sz/creating_a_new_game_with_bevy)) - 🆓 **free** (@Defernus?)
- [x] Revolver Time ([1](https://allocatedartist.itch.io/revolver-time), [2](https://youtube.com/watch?v=LNcGzn7ZsNI)) - 🆓 **free**
- [x] canal mania ([1](https://lee-orr.itch.io/canal-mania), [2](https://github.com/lee-orr/CanalMania)) - 🆓 **free** (@lee-orr?)

#### Learning Material Updates

- [x] Native iOS Touch Events w/ Rust ([1](https://itnext.io/rust-native-ios-touch-events-8b01418e0f3b)) - 🆓 **free** (@wadez?)
- [x] Bevy Basics video series ([1](https://youtube.com/playlist?list=PL6uRoaCCw7GN_lJxpKS3j-KXuThRiSXc6)) - 🆓 **free** (@PhaestusFox?)
- [x] Platformer in Bevy video series ([1](https://youtube.com/playlist?list=PL6uRoaCCw7GN_lJxpKS3j-KXuThRiSXc6)) - 🆓 **free** (@PhaestusFox?)
- [x] Introduction to the Entity Component System ([1](https://indiedevcasts.com/posts/ecs-introduction)) - ✔️ done by @theredfish

#### Engine Updates

- [x] fyrox ([1](https://fyrox.rs/blog), [2](https://reddit.com/r/rust/comments/106jh2n/fyrox_game_engine_029), [3](https://reddit.com/r/rust_gamedev/comments/102hunf/fyrox_book_animation_editor_overview), [4](https://reddit.com/r/rust_gamedev/comments/102hv95/fyrox_book_animation_blending_state_machine)) - 🚧 WIP by @MrDimas
- [x] alkahest-rs ([1](https://twitter.com/alkimia_studios/status/1610802953828405248)) - 🆓 **free** (@AnthonyUtt?)
- [x] godot-rust ([1](https://twitter.com/GodotRust/status/1615606253052362752), [2](https://twitter.com/GodotRust/status/1620027366729990149)) - 🆓 **free** (@Bromeon?)
- [x] piston ([1](https://reddit.com/r/rust_gamedev/comments/10hsofw/i_seen_some_people_claim_the_piston_project_is_abandoned)) - 🆓 **free** (@bvssvni?)
- [x] petrichor64 ([1](https://makeavoy.itch.io/petrichor64), [2](https://twitter.com/makeavoy/status/1619214379932880896)) - 🆓 **free** (@Auxnon?)

#### Tooling Updates

- [x] Graphite - ✔️ done by @Keavon
- [x] Foxtrot ([1](https://reddit.com/r/bevy/comments/10nnqoa/foxtrot_the_allinone_bevy_3d_game_template)) - ✔️ done by @janhohenheim
- [x] Ten Minute Physics ([1](https://reddit.com/r/rust/comments/10l4ae5/ten_minute_physics_demos_in_rust_with_wasm_webgl), [2](https://github.com/cerrno/ten-minute-physics-rs)) - 🆓 **free** (@cerrno?)
- [x] rgis ([1](https://github.com/frewsxcv/rgis)) - 🆓 **free** (@frewsxcv?)

#### Library Updates

- [x] wgpu v0.15, naga v0.11 ([1](https://reddit.com/r/rust/comments/10lf10i/wgpu_015_and_naga_011)) - 🆓 free (@cwfitzgerald?)
- [x] raster_fonts ([1](https://reddit.com/r/rust_gamedev/comments/100vmqq/announcing_font2img_and_raster_fonts)) - 🆓 **free** (@teryror?)
- [x] torchbearer ([1](https://reddit.com/r/rust_gamedev/comments/107jozz/updated_torchbearer)) - ✔️ done by @redwarp
- [x] nvtt ([1](https://github.com/mijalk0/nvtt), [2](https://reddit.com/r/rust_gamedev/comments/10eq1uh/nvtt_rs_has_been_updated_to_use_nvidia_texture)) - 🆓 **free** (@mijalk0?)
- [x] oxidized_navigation ([1](https://github.com/TheGrimsey/oxidized_navigation), [2](https://twitter.com/TheGrimsey/status/1615063433367494656)) - 🆓 **free** (@TheGrimsey?)
- [x] Matchbox ([1](https://mastodon.social/@johanhelsing/109681997649114818)) - ✔️ done by @johanhelsing
- [x] VPlugin ([1](https://github.com/VPlugin/VPlugin)) - 🆓 **free** (@AndroGR?)
- [x] egui_glium ([1](https://twitter.com/ernerfeldt/status/1621811309284130816)) - 🆓 **free** (@emilk?)
- [x] tween ([1](https://github.com/sanbox-irl/tween)) - ✔️ done by @sanbox-irl
- [x] scene-graph ([1](https://github.com/sanbox-irl/scene-graph)) - ✔️ done by @sanbox-irl
- [x] direct-storage ([1](https://github.com/Tsukisoft/direct-storage-rs)) - 🆓 **free** (@hasenbanck?)
- [x] rustysynth ([1](https://github.com/sinshu/rustysynth)) - ✔️ done by @sinshu
- [x] big-brain ([1](https://github.com/zkat/big-brain/releases/tag/v0.16.0)) - ✔️ done by @zkat
- [x] bones ([1](https://github.com/fishfolk/bones), [2](https://reddit.com/r/rust_gamedev/comments/10j74lt/bones)) - 🆓 **free** (@elrend-sh @erlend-sh?)
- [x] airsim-client ([1](https://reddit.com/r/rust_gamedev/comments/10ij9lv/airsimclient)) - 🆓 **free** (@Sollimann?)
- [x] Rapier ([1](https://dimforge.com/blog/2023/01/22/the-year-2022-in-dimforge)) - 🆓 **free** (@sebcrozet?)
- [x] miniquad ([1](https://mastodon.gamedev.place/@fedor/109786150254963650)) - ✔️ done by @not-fl3
- [x] bevy-magic-light-2d ([1](https://github.com/zaycev/bevy-magic-light-2d), [2](https://twitter.com/xyzw_io/status/1610083721666875394), [3](https://reddit.com/r/rust_gamedev/comments/10ppemu/working_on_combat_system_for_fantasy_kingdom)) - 🆓 **free** (@zaycev?)
- [x] notan v0.9 ([1](https://reddit.com/r/rust/comments/10pwgka/released_a_new_version_of_notan_a_sdllike_lib)) - 🆓 **free** (@Nazariglez?)

#### Other News

- [x] Bullet points of any interesting news that doesn't have its own section - 🆓 **free** (@AngelOnFira?)

#### Discussions

- [ ] "Is it a good idea to start learning game development with rust?" ([1](https://reddit.com/r/rust_gamedev/comments/107lmra/is_it_a_good_idea_to_start_learning_game))
- [ ] "Tech stack for a turn-based roguelike in Rust" ([1](https://reddit.com/r/rust_gamedev/comments/10npmn6/tech_stack_for_a_turnbased_roguelike_in_rust))
- [ ] "Pain points using Rust for gamedev?" ([1](https://reddit.com/r/rust_gamedev/comments/10qyf0v/pain_points_using_rust_for_game_dev))
- [ ] "I want to make a game that’s compatible with Nintendo switch" ([1](https://reddit.com/r/rust_gamedev/comments/10jh6lt/i_want_to_make_a_game_thats_compatible_with_switch))

## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @AngelOnFira
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @AngelOnFira
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @AngelOnFira
- [ ] Add a draft of next month's newsletter - by @AngelOnFira

**Comment by sinshu** [comment]
Hi, I'm the author of rustysynth. I found out about this newsletter through a GitHub notification that my name was included in this issue. Would it be possible for me to write a description of rustysynth?

**Comment by ozkriff** [comment]
@sinshu of course, we would appreciate a PR! Here are our [contributing guidelines](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md#style-guidelines) but don't worry about them too much, we'll fix all the style/formatting issues during the PRs review. :)

**Comment by redwarp** [comment]
I'll comment on `torchbearer` then 😉

**Comment by sanbox-irl** [comment]
Yeah I'll write something up on tween. I'm also working on a library called `scene-graph` that i'd like to write up as well

**Comment by not-fl3** [comment]
hope its not too late, I'll take miniquad update!

**Comment by johanhelsing** [comment]
I'll take Cargo Space and Matchbox. Cargo space is nearly done, matchbox hopefully within a day.

**Comment by theredfish** [comment]
Is the newsletter a good place for this article I wrote? https://indiedevcasts.com/posts/ecs-introduction . If yes, should I put it in other news?

**Comment by ozkriff** [comment]
@theredfish yes! I've added to the "Learning Material Updates" group - feel free to send a PR with a full section!

**Comment by theredfish** [comment]
Thanks @ozkriff I will send it soon !

**Comment by Auxnon** [comment]
Hi! I'm the developer for Petrichor64. I'm not sure how you figured out my github when the repo is currently private, good sleuthing! I would like to write an article but I'm slammed with dayjob/parent stuff this month. The rust side of project is also unfortunately closed source at this time, so the coding/api layer is entirely in lua. For this reason Im not sure the project belongs here or not, but I'd love to give some insight or tips with wgpu or something next time!

**Comment by AngelOnFira** [comment]
The final review is up! I'll hopefully release it in the next several hours.

https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1284

[Live site](https://agitated-saha-af60ca.netlify.app/news/042/)
