### ISSUE TITLE
Newsletter 43: Feb 2023

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#1287]
# Newsletter 43: Feb 2023

###### tags: `newsletter`

**Editors:** @ozkriff, @AngelOnFira

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with February's news!

## Current Schedule

**The soft deadline for all section PRs is March 4.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Rust Gamedev Meetup

- [x] Details of this month's meetup - ✔️ done by @ozkriff

#### Game Updates

- [x] Veloren ([1](https://veloren.net)) - ✔️ done by @AngelOnFira
- [x] Tiny Glade ([1](https://mastodon.gamedev.place/@h3r2tic/109944570601599189), [2](https://twitter.com/anastasiaopara/status/1626570875842469888)) - ✔️ done by @anopara
- [x] Hydrofoil Generation ([1](https://twitter.com/HydrofoilG/status/1626254651870830592)) - ✔️ done by @kunos
- [x] Cargo Space ([1](https://johanhelsing.studio/posts/cargo-space-devlog-5)) - ✔️ done by @johanhelsing
- [x] triverse ([1](https://cragwind.itch.io/triverse/devlog), [2](https://mastodon.gamedev.place/@bencarru/109815980621802936)) - ✔️ done by @ozkriff
- [x] Open Combat ([1](https://twitter.com/buxofp/status/1621433293328551936)) - ✔️ done by @buxx
- [ ] Hoive ([1](https://reddit.com/r/rust_gamedev/comments/10ypmm3/the_board_game_hive_written_in_rust)) - 🆓 **free** (@cooscoos?)
- [ ] Tigris and Euphrates ([1](https://reddit.com/r/rust_gamedev/comments/111xlv7/tigris_and_euphrates_in_rust)) - 🆓 **free** (@0b01?)
- [x] CootsMania ([1](https://twitter.com/kuviman/status/1629787567603216384)) - ✔️ done by @kuviman
- [x] Idu ([1](https://twitter.com/logicsoup/status/1625584446710726657), [2](https://twitter.com/logicsoup/status/1628910319274807297), [3](https://twitter.com/logicsoup/status/1628765989134270464)) - ✔️ done by @ozkriff
- [ ] Tantan’s Voxel Project ([1](https://youtube.com/watch?v=xQLVYnD43vI)) - 🆓 **free** (@TanTanDev?)
- [ ] Primitive Engineering ([1](https://reddit.com/r/bevy/comments/110pd52/i_am_making_a_game_using_bevy_just_added_a_simple), [2](https://reddit.com/r/bevy/comments/11cpm79/ive_added_a_new_crafting_system_to_my_game_that_i)) - 🆓 **free** (@Defernus?)
- [ ] scalp invaders ([1](https://metalmancy.itch.io/scalp-invaders)) - 🆓 **free** (@cdsupina?)
- [x] Necking ([1](https://devildahu.ch/devlog/necking-1)) - ✔️ done by @ozkriff
- [x] Legend of Worlds ([1](https://legendofworlds.com/dev-log-2)) - ✔️ done by @troyedwardsjr
- [x] Tunnet - ✔️ done by @puzzled-squid
- [x] CyberGate - ✔️ done by @cybersoulK

#### Learning Material Updates

- [x] First Person Game in 2KB ([1](https://reddit.com/r/rust/comments/11bdsys/write_a_first_person_game_in_2kb_with_rust)) - ✔️ done by @grantshandy
- [ ] Exploring Rust for Vulkan drivers ([1](https://www.collabora.com/news-and-blog/blog/2023/02/02/exploring-rust-for-vulkan-drivers-part-1/), [2](https://mastodon.gamedev.place/@gfxstrand/109795901575619071)) - 🆓 **free** (@gfxstrand?)
- [x] Making Galaga in Rust with Bevy ([1](https://whoisryosuke.com/blog/2023/making-galaga-in-rust-with-bevy-part-1/)) - ✔️ done by @ozkriff
- [ ] Learn WGPU ([1](https://reddit.com/r/rust_gamedev/comments/113zlqs/learn_wgpu_updated_to_015)) - 🆓 **free** (@sotrh?)
- [ ] PhaestusFox's Bevy videos ([1](https://youtube.com/@PhaestusFox/videos)) - 🆓 **free** (@PhaestusFox?)
- [ ] FPS Limiter in Rust by Hooking DirectX ([1](https://zazama.de/blog/creating-an-fps-limiter-in-rust-by-hooking-directx)) - 🆓 **free** (@Zazama?)
- [ ] Bevy Cheatbook ([1](https://bevy-cheatbook.github.io/features/camera.html), [2](https://bevy-cheatbook.github.io/features/hdr-tonemap.html)) - 🆓 **free** (@inodentry?)
- [x] Voxel Meshing ([1](https://playspacefarer.com/voxel-meshing/), [2](https://playspacefarer.com/voxel-meshing-performance/)) - ✔️ done by @ozkriff

#### Engine Updates

- [ ] alkahest-rs ([1](https://reddit.com/r/rust_gamedev/comments/10xe3c3/new_episode_out_in_my_rustopengl_game_engine), [2](https://twitter.com/alkimia_studios/status/1626047508462899208)) - 🆓 **free** (@AnthonyUtt?)
- [x] Ambient ([1](https://reddit.com/r/rust/comments/118wlda/introducing_ambient_01)) - ✔️ done by @philpax
- [x] fyrox ([1](https://fyrox.rs/blog), [2](https://reddit.com/r/rust/comments/110hkfu/media_advanced_animation_root_motion)) - ✔️ done by @ozkriff
- [x] godot-rs - ✔️ done by @Bromeon
- [x] Blue - ✔️ done by @ElhamAryanpur
- [x] Geng - ✔️ done by @kuviman

#### Tooling Updates

- [x] Graphite - ✔️ done by @Keavon
- [ ] denog ([1](https://github.com/denogdev/denog). [2](https://reddit.com/r/rust/comments/10tsfry/denox_gamdev_deno_fork)) - 🆓 **free** (@jbatez?)
- [x] yds' sprite & p/art editor ([1](https://reddit.com/r/rust_gamedev/comments/10ttg47/wip_sprite_and_pixel_art_editor)) - ✔️ done by @yds12
- [x] rerun.io ([1](https://reddit.com/r/rust/comments/112unsd/opensourcing_rerun_a_visualization_toolbox)) - ✔️ done by @ozkriff
- [ ] Rust on Nintendo DS ([1](https://reddit.com/r/rust/comments/10yk0kg/media_i_spent_time_porting_rust_to_the_nntendo_ds)) - 🆓 **free** (@SeleDreams?)

#### Library Updates

- [x] cvars ([1](https://reddit.com/r/rust_gamedev/comments/10wfe9p/announcing_cvars)) - ✔️ done by @martin-t
- [x] seldom_state v0.4 ([1](https://mastodon.social/@Seldom_SE/109937285140821063)) - ✔️ done by @Seldom-SE
- [x] blink-alloc ([1](https://github.com/zakarumych/blink-alloc)) - ✔️ done by @zakarumych
- [x] hexx ([1](https://twitter.com/ManevilleF/status/1625159292490854400)) - ✔️ done by @ManevilleF
- [x] Taffy v0.3 ([1](https://tech.lgbt/@alice_i_cecile/109853552897063176), [2](https://reddit.com/r/rust/comments/110ouej/taffy_03_ui_layout_in_rust_now_with_cssgrid)) - ✔️ done by @alice-i-cecile
- [x] pecs ([1](https://github.com/jkb0o/pecs)) - ✔️ done by @jkb0o
- [ ] oxidized_navigation v0.2 ([1](https://github.com/TheGrimsey/oxidized_navigation/blob/master/CHANGELOG.md#020-2023-02-13)) - 🆓 **free** (@TheGrimsey?)
- [x] warbler_grass - ✔️ done by @EmanuelBoehm
- [x] nanoshredder - ✔️ done by @not-fl3

#### Other News

- [x] Bullet points of any interesting news that doesn't have its own section - ✔️ done by @ozkriff

#### Discussions

- [x] "We're not really game yet" ([1](https://reddit.com/r/rust_gamedev/comments/11b0brr/were_not_really_game_yet))
- [x] "Does anyone here work in gamedev with Rust?" ([1](https://reddit.com/r/rust/comments/11bn8f1/does_anyone_here_work_in_gamedev_with_rust))

## Publishing Steps

- [x] Final review - by everyone
- [x] Publish - by @ozkriff
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter, mastodon - by @ozkriff
- [x] Pin thread on Twitter - by @ozkriff
- [x] Add comment links - by @ozkriff
- [x] Add a draft of next month's newsletter - by @ozkriff

**Comment by ozkriff** [comment]
> The soft deadline for all section PRs is March 4.

Ugh, the statistics say that the newsletter will likely be released significantly later :snail: but I'll try hard to prepare the release for Monday.

**Comment by Seldom-SE** [comment]
I'll take `seldom_state`!

**Comment by philpax** [comment]
I'll take Ambient :)

**Comment by kunos** [comment]
I'll do Hydrofoil Generation!

**Comment by alice-i-cecile** [comment]
I'll take taffy, and I'll also do a little blurb for my game Emergence.

**Comment by zakarumych** [comment]
I'll write about `blink-alloc`

**Comment by jkb0o** [comment]
I'll write about `pecs`

**Comment by yds12** [comment]
Hey I'll write about the sprite editor (tooling updates), thanks for including it

**Comment by grantshandy** [comment]
I'll take "Write First Person Game in 2KB"

**Comment by Bromeon** [comment]
godot-rust it is 🤖🦀

**Comment by JMS55** [comment]
Can I ask that a small link to [dlss_wgpu](https://github.com/JMS55/dlss_wgpu) gets included? Nothing to say about it or showoff atm, but I'm writing WIP bindings to NVIDIA's DLSS for usage with wgpu.

**Comment by buxx** [comment]
I take `Open Combat` :)

**Comment by EmanuelBoehm** [comment]
Could I also include a small section about the release of [warbler_grass](https://github.com/EmiOnGit/warbler_grass)?

**Comment by ElhamAryanpur** [comment]
Greetings! Hello Ozkriff,

I was wondering if I can include [blue engine](https://AryanpurTech/BlueEngine) for the newsletter. If this month is full, I can prepare for next month. Thank you.

**Comment by ozkriff** [comment]
@ElhamAryanpur sure, feel free to send a PR!

**Comment by martin-t** [comment]
I'll take cvars

**Comment by johanhelsing** [comment]
I'll write up a section on Cargo Space in a couple of hours :)

**Comment by ozkriff** [comment]
The final draft is ~80% done, going to finish it off tomorrow morning (utc+4 tz).

@AngelOnFira @Keavon ping about WIP sections.

**Comment by AngelOnFira** [comment]
Sorry, I'll try to get the meetup done tomorrow morning :+1:

**Comment by Keavon** [comment]
Working on it now, sorry for the delay during this especially busy week. Should be done in several hours, hopefully before your morning.

**Comment by ozkriff** [comment]
THe final draft is here, everyone is invited to review: https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1313

**Comment by ozkriff** [comment]
:tada: https://gamedev.rs/news/043 :tada:

As always, huge thanks to all contributors and reviewers! :crab: :crab: :crab:
