### ISSUE TITLE
Newsletter 44: March 2023

### ISSUE THREAD

**Issue by AngelOnFira** [rust-gamedev/rust-gamedev.github.io#1317]
# Newsletter 44: March 2023

###### tags: `newsletter`

**Editors:** @AngelOnFira, @ozkriff

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with March's news!

## Current Schedule

**The soft deadline for all section PRs is April 6th.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Announcements

- [ ] Rust GameDev Meetup - 🚧 WIP by @AngelOnFira

#### Game Updates

- [ ] Veloren ([1](https://veloren.net)) - 🚧 WIP by @AngelOnFira
- [ ] Infinilands ([1](https://store.steampowered.com/app/1882900/Infinilands), [2](https://twitter.com/FluffyGameDev)) - 🆓 **free** (@FluffyCreature?)
- [ ] The Beat Of Space ([1](https://reddit.com/r/rust_gamedev/comments/11kcgcj/our_pure_rust_game_the_beat_of_space)) - 🆓 **free**
- [ ] Tiny Glade ([1](https://twitter.com/anastasiaopara/status/1634633463247560704), [2](https://store.steampowered.com/news/app/2198150/view/3681169040455721390), [3](https://twitter.com/anastasiaopara/status/1638200134596018185?t=oZwRIvwE6qpl1ZFIgxrr2g&s=35)) - 🆓 **free** (@anopara?)
- [ ] Combine And Conquer ([1](https://buckmartin.de/combine-and-conquer.html)) - 🆓 **free** (@I3ck?)
- [ ] maginet ([1](https://twitter.com/evrimzone/status/1635798385872584704), [2](https://evrimzone.itch.io/maginet)) - 🆓 **free**
- [ ] vustnexus ([1](https://twitter.com/SethMadDev/status/1631357764495630336)) - 🆓 **free** (@Seth-VII?)
- [x] Zombie Demo Game ([1](https://lpghatguy.itch.io/zombie-demo-game), [2](https://mastodon.gamedev.place/@lpg/110014910979332447)) - ✔️ done by @LPGhatguy
- [ ] BattleBots simulator ([1](https://twitter.com/nilay_savant/status/1632419019914645504)) - 🆓 **free** (@nilaysavant?)
- [ ] bevy-rust-wasm-experiments ([1](https://twitter.com/topheman/status/1632713515462008832?t=P1OOL3qx-j1Mc6802tKSXg&s=35), [2](https://www.reddit.com/r/bevy/comments/11o5pve/bevy_wasm_and_accelerometer/)) - 🆓 **free** (@topheman?)
- [x] Cybergate ([1](https://www.reddit.com/r/rust_gamedev/comments/11soszy/cybergate_game_built_in_rust_releases_7th_major/), [2](https://www.reddit.com/r/programming/comments/11vy7lj/i_built_a_multiplayer_game_engine_in_rust_ask_me/)) - ✔️ done by @cybersoulK
- [ ] Maginet ([1](https://twitter.com/evrimzone/status/1636755433082990593)) - 🆓 **free**
- [x] Shifting chamber ([1](https://mastodon.gamedev.place/@maciekglowka/110040416267455775)) - ✔️ done by @maciekglowka
- [ ] Cargo Space ([1](https://johanhelsing.studio/posts/cargo-space-devlog-6)) - 🆓 **free** (@johanhelsing?)
- [ ] Screen Ball ([1](https://mastodon.world/@lewiszlw/110070425490951392)) - 🚧 WIP by @lewiszlw
- [ ] Battle City Game ([1](https://twitter.com/lewiszlw/status/1638745603818786816)) - 🚧 WIP by @lewiszlw
- [x] tunnet ([1](https://puzzled-squid.itch.io/tunnet/devlog/507508/devlog-0-gameplay-loop-and-subnetworks)) - ✔️ done by@puzzled-squid
- [x] 8bit Duels ([1](https://www.reddit.com/r/rust_gamedev/comments/125y4xn/8bit_duels_devlog_part_6/)) - ✔️ done by @thousandthstar

- [x] Digital Extinction ([1](https://www.reddit.com/r/rust_gamedev/comments/128juyo/monthly_update_6_from_the_development_of_digital/)) - ✔️ done by@Indy2222
- [x] Jumpy - ✔️ done by @zicklag
- [x] Way of Rhea - ✔️ done by @MasonRemaley

#### Learning Material Updates

- [x] Writing NES assembly programs in a Rust DSL ([1](https://youtube.com/watch?v=hs-MrEoOX5Y)) - ✔️ done by @gridbugs
- [ ] PhaestusFox’s Bevy videos ([1](https://youtube.com/@PhaestusFox/videos)) - 🆓 **free** (@PhaestusFox?)
- [ ] Pirate Annihilation Devlog #2 ([1](https://twitter.com/indiedevcasts/status/1630478796997402625?t=_3ViSm_2qMB1odD8zlLWSg&s=35)) - 🆓 **free** (@theredfish?)
- [ ] Transparent Windows ([1](https://twitter.com/s0lly/status/1632513842457485312?t=SCLpSZJLcyqOJZOqUcx5tw&s=35), [2](https://www.reddit.com/r/rust_gamedev/comments/11jh1np/bevys_quite_versatile/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=2&utm_content=share_button)) - 🆓 **free** (@s0lly?)
- [ ] Rendering 5 million pixel updates per second with Rust & wgpu ([1](https://www.reddit.com/r/rust/comments/11o9he6/rendering_5_million_pixel_updates_per_second_with/), [2](https://maxisom.me/posts/applying-5-million-pixel-updates-per-second)) - 🆓 **free** (@codetheweb?)
- [ ] Bestagon Mesh Generation: Waveform Collapse in Bevy ([1](https://www.reddit.com/r/rust_gamedev/comments/11okw9n/im_making_a_hexagon_cell_map_using_bevy/)) - 🆓 **free** (@PhaestusFox?)
- [x] Editors 2/3 + 3/3: Editing entries ([1](https://mastodon.social/@TheGrimsey/110009810807858482), [2](https://twitter.com/TheGrimsey/status/1638240893785239563?t=10H37e1BvX0BsPmsvy0kQA&s=35)) - ✔️ done by @TheGrimsey
- [ ] Foxtrot ([1](https://www.reddit.com/r/rust_gamedev/comments/11wpptk/foxtrot_the_allinone_bevy_3d_template_reaches_020/)) - 🚧 WIP by @janhohenheim - 🆓 **free**
- [ ] Creating a Small Game with WebAssembly and Rust ([1](https://medium.com/comsystoreply/creating-a-small-game-with-webassembly-and-rust-20c6945efa1d)) - 🆓 **free**
- [ ] Still Have A Use For Adobe Flash? Ruffle Is Working To Safely Emulate It In Rust ([1](https://www.phoronix.com/news/Ruffle-Adobe-Flash-Rust)) - 🆓 **free**
- [ ] Paving the Road to Vulkan on Asahi Linux ([1](https://www.reddit.com/r/rust/comments/11wosur/paving_the_road_to_vulkan_on_asahi_linux/)) - 🆓 **free**
- [ ] forerunner - a storytelling platform for composing Souls-like Action-RPGs ([1](https://twitter.com/heavyrain266/status/1638674649889361921?t=iwGm-Kg54iKUHyTqN9Cgsg&s=35)) - 🆓 **free**
- [x] Using the Depth Prepass in Bevy 0.10 ([1](https://hachyderm.io/@chrisbiscardi/110101000132502075)) - ✔️ done by@ChristopherBiscardi
- [ ] Learn Bevy 0.10 Beginner Tutorial ([1](https://www.reddit.com/r/rust_gamedev/comments/125ab0u/learn_bevy_010_beginner_tutorial_ep10_bevy_ui_is/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=2&utm_content=share_button)) - 🆓 **free** (@frederickjjoubert?)
- [ ] Getting started with egui in Rust ([1](https://mastodon.gamedev.place/@whoisryosuke/110103477622463842)) - 🆓 **free** (@whoisryosuke?)
- [ ] My unsorted and unsolicited thoughts on Rust for game development ([1](https://yanchith.github.io/posts/6.html)) - 🆓 **free** (@yanchith?)
- [ ] Overworld and NPCs in Bevy ([1](https://www.youtube.com/watch?v=luyDgccpHgE)) - 🆓 **free** (@mwbryant?)

#### Engine Updates

- [ ] fyrox ([1](https://fyrox.rs/blog), [2](https://www.reddit.com/r/rust_gamedev/comments/11vojtk/media_blend_shapes_an_easy_yet_powerful_way_to/)) - 🚧 WIP by @ozkriff
- [x] Bevy 0.10 ([1](https://www.reddit.com/r/rust/comments/11k8kxd/bevy_010/)) - ✔️ done by @cart
- [x] Hotline ([1](https://mastodon.gamedev.place/@polymonster/109964958214376737)) - ✔️ done by @polymonster
- [ ] Tetra 0.8.0 ([1](https://twitter.com/17cupsofcoffee/status/1613591548616216602), [2](https://twitter.com/17cupsofcoffee/status/1636706157568962563), [3](https://github.com/17cupsofcoffee/tetra/blob/HEAD/CHANGELOG.md#080---2023-03-17)) - 🆓 **free** (@17cupsofcoffee?)

#### Tooling Updates

- [ ] Graphite - 🚧 WIP by @Keavon
- [ ] Epic Asset Manager ([1](https://github.com/AchetaGames/Epic-Asset-Manager)) - 🆓 **free** (@aknarts?)
- [ ] Orlop ([1](https://twitter.com/eskappe/status/1634101196234321920), [2](https://tirch.itch.io/orlop), [3](https://orlop.dev/)) - 🆓 **free** (@timrach?)
- [ ] ruffle ([1](https://discord.com/channels/610531541889581066/778699403577393153/1084270517709705246)) - 🆓 **free** (@adrian17?)
- [x] tarsila ([1](https://www.reddit.com/r/rust/comments/11ulldz/media_announcing_tarsila_010_pixel_art_and/)) - ✔️ done by @yds12
- [x] Tiger ([1](https://mastodon.gamedev.place/@agersant/110001949986421177)) - ✔️ done by @agersant
- [ ] Blackjack ([1](https://mastodon.gamedev.place/@Setzer22/110011331330540420)) - 🆓 **free** (@Setzer22?)
- [ ] Orlop ([1](https://mastodon.gamedev.place/@wetmonkey/110062614206607868)) - 🆓 **free**
- [ ] Rerun ([1](https://mastodon.gamedev.place/@wumpf/110102066834019908)) - 🚧 WIP by @Wumpf

#### Library Updates

- [ ] winit-block-on ([1](https://reddit.com/r/rust/comments/11ngn5x/announcing_winitblockon)) - 🆓 **free** (@notgull?)
- [ ] pixelate_mesh ([1](https://reddit.com/r/bevy/comments/11qenq3/pixelate_mesh)) - 🚧 WIP by @janhohenheim
- [ ] tinyaudio ([1](https://reddit.com/r/rust/comments/11rei24/announcing_tinyaudio)) - 🚧 WIP by @ozkriff
- [x] bevy\_text\_mode ([1](https://github.com/yopox/bevy_text_mode), [2](https://mstdn.social/@yopox/110010264001721310)) - ✔️ done by @yopox
- [x] Bevy Rust-GPU ([1](https://www.reddit.com/r/rust/comments/11hrodt/bevy_rustgpu_joins_the_fray_write_shaders_in/)) - 🚧 WIP by @Shfty
- [ ] Bevy Hanabi ([1](https://twitter.com/djeedai/status/1634129348746772481?t=ckisHsz6FdUcPrHb8y_hag&s=35)) - 🆓 **free** (@djeedai?)
- [ ] faer 0.5.0 ([1](https://www.reddit.com/r/rust/comments/122823y/faer_050_release/)) - 🆓 **free** (@sarah-ek?)
- [x] Matchbox 0.6 ([1](https://www.reddit.com/r/rust_gamedev/comments/127suhc/matchbox_06_released_painless_peertopeer_webrtc/)) - ✔️ done by @johanhelsing?
- [ ] rust-gpu-sdf - 🚧 WIP by @Shfty

#### Other News

- [ ] Bullet points of any interesting news that doesn't have its own section - 🆓 **free**

#### Discussions

- [ ] "Is WGPU actually a good idea yet?" ([1](https://reddit.com/r/rust_gamedev/comments/11f3rjq/is_wgpu_actually_a_good_idea_yet)) - 🆓 **free**

#### Jobs

- [ ] Ambient ([1](https://twitter.com/AmbientRun/status/1641746682206474243?t=2FLsUG0GAcUS03VW99h3eA&s=35)) - 🆓 **free**
    
## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @AngelOnFira
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @AngelOnFira
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @AngelOnFira
- [ ] Add a draft of next month's newsletter - by @AngelOnFira

**Comment by Wumpf** [comment]
I'll take the Rerun update

**Comment by maciekglowka** [comment]
Thanks! I am gonna take the section about my game (Shifting Chamber)

**Comment by lewiszlw** [comment]
Thanks! Happy to take Screen Ball and Battle City Game sections.

**Comment by janhohenheim** [comment]
I'll write about Foxtrot and Pixelate Mesh :)

**Comment by gridbugs** [comment]
I'll take the section about my talk on writing NES programs in a rust DSL

**Comment by puzzled-squid** [comment]
I will write about Tunnet.

**Comment by yds12** [comment]
I'll write about Tarsila

**Comment by ThousandthStar** [comment]
Just did 8bit Duels.

**Comment by Shfty** [comment]
Bevy Rust-GPU is sorted; I need to finish up some abstractions before capturing a visual for `rust-gpu-sdf`, so i'll issue a separate pull for that section once it's ready.

**Comment by scirin** [comment]
Hey!
I would like to help out with editing!

**Comment by Wandalen** [comment]
By the way Irina @scirin, I encourage you to join our community if you are not there yet
https://t.me/rustlang_ua
And join the conference:
https://uarust.com/

**Comment by Shfty** [comment]
I've added a section for `rust-gpu-sdf` :slightly_smiling_face:

**Comment by nilaysavant** [comment]
I have added the section for `BattleBots Simulator` https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1330

Thanks 😊

**Comment by johanhelsing** [comment]
I wrote a section on Matchbox. Will try to get one ready for Cargo Space as well :)

**Comment by gridbugs** [comment]
I'll also write a section about a game jam game I made this month ([Boat Journey](https://gridbugs.itch.io/boat-journey))

**Comment by codetheweb** [comment]
I'll take my article "Rendering 5 million pixel updates per second with Rust & wgpu"

**Comment by cart** [comment]
I just picked up Bevy 0.10

**Comment by cart** [comment]
I think we'll probably want to cover Bevy Jam 3 next newsletter. April 6th is pretty much too late in the jam to join, but still during the duration of the jam so we won't have results yet.

**Comment by buxx** [comment]
Hello, I would like to speak about Open Combat (but not in the list in tjis NL ?)

**Comment by Keavon** [comment]
@cart there's probably still time to cover Bevy Jam 3, I'd think.

**Comment by Wumpf** [comment]
I need to update the Rerun piece again, by now there was a new version release ;)

**Comment by ozkriff** [comment]
Taking all unclaimed engine, tooling, and library sections.

**Comment by janhohenheim** [comment]
Just realized I forgot to write the sections I claimed, will do this later today :)

**Comment by ozkriff** [comment]
I'm taking over the last bits of the newsletter; going to post the final draft in a couple of hrs.

**Comment by Wumpf** [comment]
oh shoot 😳 . forgot about updating the rerun entry. on it now.

**Comment by ozkriff** [comment]
https://gamedev.rs/news/044 - aaand it's out!

Sorry for all the delays. On the positive side, our release timings will hopefully improve in the future since we've just got a new editor: @scirin!

And, as always, huge thanks to all contributors, reviewers, and editors! :crab::crab::crab:
