### ISSUE TITLE
Newsletter 45: April 2023 

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#1358]
# Newsletter 45: April 2023

###### tags: `newsletter`

**Editors:** @ozkriff, @AngelOnFira, @scirin

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with April's news!

## Current Schedule

**The soft deadline for all section PRs is 2023.05.07.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Rust Gamedev Meetup

- [ ] Monthly Meetup - 🚧 WIP by @AngelOnFira
- [ ] Bevy Jam 3 Results ([1](https://reddit.com/r/rust/comments/12wisci/the_results_of_the_latest_bevy_jam), [2](https://reddit.com/r/rust_gamedev/comments/12wmwmk/tried_bevy_for_the_first_time_for_a_game_jam)) - 🆓 **free** (@cart @alice-i-cecile?)

#### Game Updates

- [x] CyberGate - ✔️ done by @cybersoulK
- [ ] Veloren - 🚧 WIP by @AngelOnFira
- [ ] Combine And Conquer ([1](https://buckmartin.de/combine-and-conquer.html)) - 🆓 **free** (@I3ck?)
- [ ] Logic RPG ([1](https://youtube.com/@logicprojects/videos), [2](https://logicprojects.itch.io/logic-rpg)) - 🆓 **free** (@mwbryant?)
- [ ] Digital Extinction ([1](https://reddit.com/r/rust/comments/128jt19/monthly_update_6_digital_ex), [2](https://reddit.com/r/rust/comments/134yjdv/monthly_update_7_digital_ex)) - 🆓 **free** (@Indy2222?)
- [ ] Stellar Cortex ([1](https://bentley.codes/stellar-cortex/foundations-of-a-space-based-economy)) - 🆓 **free** (@atbentley?)
- [ ] Hydrofoil Generation ([1](https://youtube.com/watch?v=qUggXlUfflY), [2](https://steamcommunity.com/app/1448820)) - 🆓 **free** (@kunos?)
- [ ] ~~Blox~~ Stockholm ([1](https://youtube.com/playlist?list=PLsFMLV-H_GYt8KzbJnzrapNkUNtRcBB2n), [2](https://tech.lgbt/@Elttob/110177077768186980)) - 🆓 **free** (@Elttob?)
- [ ] Idu ([1](https://epcc.itch.io/idu/devlog/513652/demo-version-10-flower-tuned-antennas), [2](https://twitter.com/logicsoup/status/1644468645467389952), [3](https://twitter.com/logicsoup/status/1653514108178776064)) - 🆓 **free** (@johann2?)
- [ ] Tiny Glade ([1](https://store.steampowered.com/news/app/2198150?emclan=103582791472800070&emgid=3682298662732600151), [1](https://twitter.com/anastasiaopara), [2](https://t.co/osgYJWUZrT)) - 🆓 **free** (@anopara @h3r2tic?)
- [ ] exocave ([1](https://cragwind.itch.io/exocave/devlog/516142/grappling-hook)) - 🆓 **free** (@bcarruthers?)
- [ ] maginet ([1](https://evrimzone.itch.io/maginet/devlog/519667/grand-ceremony-for-the-beta)) - 🆓 **free** (@evrimoztamur?)
- [ ] Railroad Scheduler ([1](https://coffejunkstudio.itch.io/railroad-scheduler)) - 🆓 **free**
- [ ] l1t ([1](https://reddit.com/r/rust/comments/12yzet7/l1t_a_terminal_strategy_game)) - 🆓 **free** (@alex-laycalvert?)
- [x] Jumpy ([1](https://reddit.com/r/rust_gamedev/comments/131p0md/fish_folks_kickstarter_in_1w)) - ✔️ done by @zicklag
- [x] Thetawave - ✔️ done by @cdsupina
- [x] Way of Rhea - ✔️ done by @MasonRemaley

#### Learning Material Updates

- [x] Bevy <3 GA - ✔️ done by @Leinnan
- [ ] PhaestusFox’s Bevy videos ([1](https://youtube.com/@PhaestusFox/videos)) - 🆓 **free** (@PhaestusFox?)
- [x] Exploring Bevy GoL shader ([1](https://lecoqjacob.github.io/bevy-gol-explore-part-1), [2](https://lecoqjacob.github.io/bevy-gol-explore-part-2), [3](https://lecoqjacob.github.io/bevy-gol-explore-part-3)) - ✔️ done by @lecoqjacob
- [x] Bevy roguelike tutorial ([1](https://mastodon.gamedev.place/@maciekglowka/110131113219998719), [2](https://maciejglowka.com/blog/bevy-roguelike-tutorial-devlog-part-5-more-actions/)) - ✔️ done by @maciekglowka
- [ ] Katamari for the BevyJam3 ([1](https://whoisryosuke.com/blog/2023/making-katamari-for-bevy-game-jam)) - 🆓 **free** (@whoisryosuke?)
- [ ] 3D MIDI Piano Using Bevy ([1](https://whoisryosuke.com/blog/2023/3d-midi-piano-using-rust-and-bevy)) - 🆓 **free** (@whoisryosuke?)
- [x] TDD in Rust GameDev w. Bevy ([1](https://edgardocarreras.com/blog/tdd-in-rust-game-engine-bevy)) - ✔️ done by @donedgardo
- [x] Building scripting solution w. Intuicio ([1](https://reddit.com/r/rust_gamedev/comments/12hqu1q/tutorial_on_building_your_own_scripting_solution)) - 🆓 **free** (@psichix?)
- [ ] DOOM maps to SVG to laser cutter ([1](https://reddit.com/r/rust/comments/12mlsfj/lasercut_doom)) - 🆓 **free** (@theor?)
- [ ] Making A Strategy Game ([1](https://twitter.com/srodrigoDev/status/1646144432163504128)) - 🆓 **free** (@srodrigo?)
- [ ] rs-football-3d ([1](https://github.com/UnravelSports/rs-football-3d), [2](https://twitter.com/unravelsports/status/1644294892674326530)) - 🆓 **free** (@UnravelSports?)
- [ ] rust-flappy-bird-ai ([1](https://www.youtube.com/watch?v=Ea_N1CJwMR8), [2](https://github.com/bones-ai/rust-flappy-bird-ai)) - 🆓 **free** (@bones-ai?)

#### Engine Updates

- [x] godot-rs ([1](https://twitter.com/GodotRust/status/1644263161023823873)) - ✔️ done by @Bromeon
- [ ] alkahest-rs ([1](https://reddit.com/r/rust_gamedev/comments/12auz7o/alkahest_0_2) - 🆓 **free** (@AnthonyUtt?)
- [ ] Strolle ([1](https://reddit.com/r/rust/comments/12u4ovi/strolle_pretty_lightning_global_illumination_6d)) - 🆓 **free** (@Patryk27?)
- [ ] ggez ([1](https://github.com/ggez/ggez/issues/1188)) - 🆓 **free** (@PSteinhaus?)
- [x] ambient - ✔️ done by @philpax

#### Tooling Updates

- [x] rustracer ([1](https://reddit.com/r/rust_gamedev/comments/12w2hbi/rustracer02)) - ✔️ done by @KaminariOS
- [ ] Graphite - 🆓 **free** (@Keavon?)
- [ ] Image Maniac ([1](https://reddit.com/r/rust/comments/133ruqi/introducing_image_maniac)) - 🆓 **free** (@AllenDang?)
- [ ] IronBoy ([1](https://reddit.com/r/rust/comments/12qj2ty/ironboy)) - 🆓 **free** (@nicolas-siplis?)
- [x] Luminol ([1](https://github.com/Astrabit-ST/Luminol)) - ✔️ done by @Speak2Erase

#### Library Updates

- [ ] faer ([1](https://reddit.com/r/rust/comments/12estz9/faer_07_release), [2](https://reddit.com/r/rust/comments/12tw26r/faer_08)) - 🆓 **free** (@sarah-ek?)
- [ ] kayak_ui ([1](https://github.com/StarArawn/kayak_ui/releases/tag/v0.3.0), [2](https://github.com/StarArawn/kayak_ui/releases/tag/v0.4.0)) - 🆓 **free** (@StarArawn?)
- [x] backpack ([1](https://github.com/Vrixyz/backpack)) - ✔️ done by @Vrixyz
- [ ] virtual_joystick ([1](https://github.com/SergioRibera/virtual_joystick)) - 🆓 **free** (@SergioRibera?)
- [ ] png ([1](https://reddit.com/r/rust/comments/12ks0ka/png_crate_gets_an_ultrafast_compression_mode)) - 🆓 **free** (@Shnatsel?)
- [ ] blend ([1](https://reddit.com/r/rust/comments/12sgf2z/blend_08)) - 🆓 **free** (@lukebitts?)
- [ ] bitcode ([1](https://reddit.com/r/rust/comments/12nw1pc/announcing_bitcode_format_for_serde)) - 🆓 **free**
- [ ] wgpu ([1](https://github.com/gfx-rs/wgpu/releases/tag/v0.16.0)) - 🆓 **free** (@cwfitzgerald?)
- [ ] lox ([1](https://reddit.com/r/rust/comments/12teoxi/lox_a_fast_polygon_mesh_library)) - 🆓 **free** (@LukasKalbertodt?)
- [ ] egui_graphs ([1](https://github.com/blitzarx1/egui_graphs)) - 🆓 **free** (@blitzarx1?)

#### Other News

- [ ] Bullet points of any interesting news that doesn't have its own section - by @ozkriff

#### Discussions

- [ ] "Well, we're a little more game" ([1](https://reddit.com/r/rust_gamedev/comments/12mppwb/well_were_a_little_more_game))
- [ ] "Really frustrated" ([1](https://reddit.com/r/rust_gamedev/comments/1302512/really_frustrated_warning_bit_of_a_negative_rant))

## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @ozkriff
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @ozkriff
- [ ] Add a draft of next month's newsletter - by @ozkriff

**Comment by Speak2Erase** [comment]
Can I add [Luminol](https://github.com/Astrabit-ST/Luminol)?

**Comment by ozkriff** [comment]
@Speak2Erase sure! added to the plan

**Comment by philpax** [comment]
We (Ambient) are planning on releasing our next update in the next two days - would we be able to sneak that into the April update, or would we have to wait for next month?

**Comment by Shnatsel** [comment]
FWIW most of the hard work on `png` has been done by @fintelia, I'm mostly just the messenger, with comparatively minor contributions (added roundtrip fuzzing and did lots of testing).

**Comment by Bromeon** [comment]
I could do godot-rust 🙂

**Comment by evrimoztamur** [comment]
Hey there good folks of the Rust GD! I'm [Maginet](https://evrimzone.itch.io/maginet)'s developer indeed and the game is actually open source over at https://github.com/evrimoztamur/maginet if anybody wants to check the setup out. Currently working on release updates and an Electron deployable (for Steam/desktop) over at https://github.com/evrimoztamur/maginet-deploy.

**Comment by Leinnan** [comment]
Back in April, I wrote a small article about using Github Actions to publish games written in bevy on Github Pages. Does it fit into **Learning Material Updates**?  Link to article: http://mevlyshkin.com/blog/bevy-github-actions

**Comment by cdsupina** [comment]
I have some updates for Thetawave. Could I write a section on it?

**Comment by sinshu** [comment]
I'm not sure why I'm assigned to rustracer, but since the author is @KaminariOS, it seems more natural for him to be assigned instead.

**Comment by KaminariOS** [comment]
I can do that.

**Comment by AllenDang** [comment]
Thanks for including Image Maniac

**Comment by PsichiX** [comment]
I'm taking Intuicio tutorial :3

**Comment by maciekglowka** [comment]
Thanks for including my tutorial (Bevy roguelike) - I am gonna take it.

**Comment by zicklag** [comment]
I'm taking Jumpy

**Comment by UnravelSports** [comment]
Thanks for including my attempt at visualizing 3D football data! If you're interested, you can include my PySport talk I gave about the subject too (https://www.youtube.com/watch?v=VwatoPOKIl8). 

Also, yes my twitter handle is correct the way you have it, so you can remove the questionmark :)

**Comment by nicolas-siplis** [comment]
IronBoy dev here, happy to take it!

**Comment by atbentley** [comment]
Thanks for the ping on Stellar Cortex, I didn't quite have time to get around to this but am looking forward to contributing something for later editions

**Comment by Patryk27** [comment]
Same, thanks for pinging - I don't have enough time now to prepare anything, but I'll try to scramble some next time 🙂

**Comment by Elttob** [comment]
Also thanks for the ping, I missed this - have been busy myself. I'm happy to help out next time though :)

**Comment by bones-ai** [comment]
Thanks for ping, 

I'll be sure to keep an eye out for the next newsletter

**Comment by srodrigo** [comment]
Hi! Sorry, I'm a bit late to the party. Is there a chance we could include my article (and another two followups I published this month) on the next newsletter?

**Comment by theor** [comment]
same ! thank you for the ping

**Comment by Keavon** [comment]
I'll finally have time to carve out of my schedule to finish the Graphite entry when I wake up in ~8h. I'll get that done first thing in the morning.

**Comment by theredfish** [comment]
Hey 👋 I see help wanted, is there anything I can do to help?

**Comment by not-fl3** [comment]
Hi, that one is from April, right? I would add a little PR with some *quad updates, but I guess for the next issue, for May, right?

**Comment by Keavon** [comment]
(this can be closed)
