### ISSUE TITLE
Newsletter 46: May 2023

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#1378]
# Newsletter 46: May 2023

###### tags: `newsletter`

**Editors:** @ozkriff, @AngelOnFira, @scirin

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with May's news!

## Current Schedule

**The deadline for all section PRs is 2023.06.10.** _(though statistically we sadly release significantly later then planned)_

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Announcements

- [ ] Rust GameDev Meetup - 🚧 WIP by @AngelOnFira
- [x] Rusty Jam 3 Results - ✔️ done by @Vrixyz

#### Game Updates

- [ ] Veloren - 🚧 WIP by @AngelOnFira
- [ ] Tiny Glade ([1](https://twitter.com/PounceLight/status/1663607000691884032), [2](https://twitter.com/h3r2tic/status/1663264361144565765)) - 🆓 **free** (@anopara @h3r2tic?)
- [ ] Turtle Time ([1](https://universeodon.com/@sqweebking/110310776017693130), [2](https://mikeder.net/blog/turtletime-devlog-1)) - 🆓 **free** (@mikeder?)
- [ ] DAshmoRE ([1](https://reddit.com/r/rust_gamedev/comments/13al7qu/dashmore)) - 🆓 **free**
- [x] Escape AI ([1](https://reddit.com/r/rust_gamedev/comments/13dstir/ai_escape_room), [2](https://twitter.com/BonesaiDev/status/1656317661696114688), [3](https://github.com/bones-ai/rust-escape-ai)) - ✔️ done by @bones-ai
- [x] Tunnet ([1](https://puzzled-squid.itch.io/tunnet/devlog/532388/devlog-1-ghost-in-the-tunnels), [2](https://mastodon.gamedev.place/@puzzled_squid/110322440469696044)) - ✔️ done by @puzzled-squid
- [x] MS80 ([1](https://youtube.com/watch?v=bgmySx_tv1s), [2](https://twitter.com/LPGhatguy/status/1662887019570249731)) - 🆓 ✔️ done by @LPGhatguy
- [ ] maginet ([1](https://twitter.com/evrimzone/status/1658908555582341120)) - 🆓 **free** (@evrimoztamur?)
- [ ] Combine And Conquer ([1](https://buckmartin.de/combine-and-conquer.html)) - 🆓 **free** (@I3ck?)
- [x] Digital Extinction ([1](https://twitter.com/MartinIndra92/status/1664194166576824323), [2](https://reddit.com/r/rust/comments/13xi2pa/monthly_update_8_from_the_development_of_digital)) - ✔️ done by @Indy2222
- [ ] nanovoid ([1](https://reddit.com/r/rust_gamedev/comments/13rgj9t/nanovoid_devlog_1), [2](https://twitter.com/LogLogGames/status/1663134570634461190)) - 🆓 **free** (@darthdeus?)
- [x] Fish Folk ([1](https://reddit.com/r/rust/comments/13qkcv9/fish_folk_bevy_game_in_development_for_4_years), [2](https://twitter.com/spicylobsterfam/status/1661357251573972992), [3](https://mastodon.social/@fishfight/110459745425696257)) - ✔️ done by @erlend-sh
- [ ] nullableengineer's mmo ([1](https://youtube.com/watch?v=rHM-4vj3uyY)) - 🆓 **free**
- [ ] Idu ([1](https://mastodon.gamedev.place/@johann/110440559190280054)) - 🆓 **free**
- [ ] bevy_garage ([1](https://github.com/alexichepura/bevy_garage), [2](https://youtu.be/f6PcaTX58J4), [3](https://discord.com/channels/691052431525675048/692648638823923732/1111360004667232297), [4](https://alexi.chepura.space/bevy-garage)) - 🆓 **free** (@alexichepura?)

#### Learning Material Updates

- [x] Building a platformer with Bevy 1 ([1](https://affanshahid.dev/posts/learning-game-dev-bevy-1/)) - ✔️ done by @affanshahid
- [x] Making A Strategy Game ([1](https://twitter.com/srodrigoDev/status/1658491339619831808), [2](https://srodrigoroyo.com/game-development-in-rust-making-a-strategy-game-2/), [3](https://srodrigoroyo.com/game-development-in-rust-making-a-strategy-game-3/)) - ✔️ done by @srodrigo
- [x] Migrate Bevy Projects with Semi-Automation ([1](https://twitter.com/hd_nvim/status/1659597808092184578)) - ✔️ done by @HerringtonDarkholme
- [ ] PhaestusFox’s Bevy videos ([1](https://youtube.com/@PhaestusFox/videos)) - 🆓 **free** (@PhaestusFox?)

#### Engine Updates

- [ ] godot-rust ([1](https://mastodon.gamedev.place/@GodotRust/110367270830037001)) - 🆓 **free** (@Bromeon?)
- [ ] StereoKit ([1](https://reddit.com/r/rust/comments/138ywxv/introducing_stereokit)) - 🆓 **free** (@MalekiRe?)
- [ ] hotline ([1](https://polymonster.co.uk/blog/building-new-engine-4), [2](https://twitter.com/polymonster/status/1652287818339688449)) - 🆓 **free** (@polymonster?)
- [ ] bevy ([1](https://bevyengine.org/news/bevy-webgpu), [2](https://reddit.com/r/rust/comments/13lb0h8/bevy_webgpu)) - 🆓 **free** (@cart?)

#### Tooling Updates

- [ ] Graphite - 🆓 **free** (@Keavon?)
- [x] Rerun ([1](https://twitter.com/ernerfeldt/status/1661999677045129223), [2](https://twitter.com/ernerfeldt/status/1665635226335182850)) - ✔️ done by @wumpf
- [x] Spicy Launcher ([1](https://fosstodon.org/@orhun/110307685680859480)) - ✔️ done by @orhun
- [x] smashline ([1](https://reddit.com/r/rust/comments/13ozz84/smashline)) - 🆓 **free** (@blu-dev?)
- [x] ruffle ([1](https://ruffle.rs/blog/2023/05/29/progress-report.html)) - 🆓 **free** (@n0samu?)

#### Library Updates

- [ ] grid v0.10 ([1](https://reddit.com/r/rust/comments/134l6mk/grid_v010)) - 🚧 WIP by @becheran
- [ ] hexx v0.6 ([1](https://github.com/ManevilleF/hexx/releases/tag/0.6.0)) - 🆓 **free** (@ManevilleF?)
- [ ] faer ([1](https://www.reddit.com/r/rust/comments/13ggs7k/faer_09)) - 🆓 **free** (@sarah-ek?)
- [x] blit ([1](https://fosstodon.org/@fosk/110294118093896360)) - ✔️ done by @tversteeg
- [x] seldom_state ([1](https://mastodon.social/@Seldom_SE/110330053045044558)) - ✔️ done by @Seldom-SE
- [ ] quinn v0.10 ([1](https://github.com/quinn-rs/quinn/releases/tag/0.10.0)) - 🆓 **free** (@Ralith @djc?)
- [ ] funutd ([1](https://github.com/SamiPerttu/funutd)) - 🆓 **free** (@SamiPerttu?)
- [ ] bevy\_diagnostics\_explorer ([1](https://reddit.com/r/bevy/comments/13hu8zt/simple_plugin_vscode_extension_for_profiling_ecs), [2](https://twitter.com/xyzw_io/status/1657910127511347201), [3](https://github.com/zaycev/bevy-diagnostics-explorer)) - 🆓 **free** (@zaycev?)
- [x] kira 0.8 ([1](https://twitter.com/tesselode/status/1660799031314874370), [2](https://reddit.com/r/rust/comments/13p7x9o/kira_game_audio_library_v08)) - ✔️ done by @tesselode
- [ ] pxo ([1](https://github.com/appybara13/pxo)) - 🆓 **free** (@appybara13?)
- [ ] frug ([1](https://github.com/santyarellano/frug), [2](https://reddit.com/r/rust/comments/13im07r/introducing_frug), [3](https://santyarellano.github.io/frug_book/guide/creating_a_window.html)) - 🆓 **free** (@santyarellano?)
- [ ] egui_tiles ([1](https://twitter.com/ernerfeldt/status/1661274676037918720)) - 🆓 **free** (@emilk?)
- [ ] egui v0.22 ([1](https://reddit.com/r/rust/comments/13px5zb/egui_022), [2](https://twitter.com/ernerfeldt/status/1661081543803060251)) - 🆓 **free** (@emilk?)

#### Other News

- [ ] Bullet points of any interesting news that doesn't have its own section - by @ozkriff

#### Discussions

- [ ] "Is bevy the best option for a Rust based game engine?" ([1](https://reddit.com/r/rust_gamedev/comments/13wteyb/is_bevy_best))
- [ ] "We're not quite game yet" ([1](https://reddit.com/r/rust_gamedev/comments/13qt6rq/were_not_quite_game_yet))
- [ ] "How does Bevy manage to be so loose with signatures?" ([1](https://reddit.com/r/rust/comments/13rcz4v/how_bevy_so_loose))

## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @ozkriff
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @ozkriff
- [ ] Add a draft of next month's newsletter - by @ozkriff

**Comment by scirin** [comment]
Leaving a comment here because I don't get notifications!

**Comment by Seldom-SE** [comment]
I'll take `seldom_state`!

**Comment by HerringtonDarkholme** [comment]
Hi! I will take `Migrate Bevy Projects with Semi-Automation`! Thanks!

**Comment by affanshahid** [comment]
I'll take `Building a platformer with Bevy 1`, thank you!

**Comment by Vrixyz** [comment]
There was the RustyJam 
- [ ] 🥇 [Find Ferris](https://kuviman.itch.io/find-ferris) 🆓 free (@kuviman ?) 
- [ ] 🥈[Tug of Orb](https://anders429.itch.io/tug-of-orb)🆓 free (@Anders429?) 
- [ ] 🥉[The Veiled Path](https://jebik.itch.io/the-veiled-path) 🆓 free (@Jebik ?) 
- [ ] [Boop](https://killercup.itch.io/boop) 🆓 free (@killercup ?) 
- [ ] [Portal Fox](https://vrixyz.itch.io/detective-fox) - by @Vrixyz

**Comment by bones-ai** [comment]
I'll take `Escape AI`, thanks

**Comment by Wumpf** [comment]
I'll write a short Rerun update later today

**Comment by evrimoztamur** [comment]
Maginet now has the level editor live, with an [itch.io devlog over here](https://twitter.com/evrimzone/status/1667486445366304768)!

**Comment by maciekglowka** [comment]
Hi, I think I will skip this issue - as I'd mostly repeat myself from the last part.
I will try to put more tutorial content this month and maybe included in the next one?

**Comment by becheran** [comment]
I will take `grid`

**Comment by h3r2tic** [comment]
I'll take Tiny Glade!
(Thanks for writing about it last time, @ozkriff! 💞)

**Comment by darthdeus** [comment]
I'll take nanovoid :)

**Comment by leod** [comment]
Hey - I'd like to add a library introduction/update for [`posh`](github.com/leod/posh).
