### ISSUE TITLE
N48: July 2023

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#1420]
# Newsletter 48: July 2023

###### tags: `newsletter`

**Editors:** @ozkriff, @AngelOnFira, @scirin

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with July's news!

## Current Schedule

**The deadline for all section PRs is 2023.08.23.** _(though this year we statistically release significantly later, sad)_

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Announcements

- [x] Rust GameDev Meetup - 🚧 WIP by @AngelOnFira

#### Game Updates

- [x] Veloren - 🚧 WIP by @AngelOnFira
- [ ] Idu ([1](https://mastodon.gamedev.place/@eli/110776871627833108), [2](https://epcc.itch.io/idu/devlog/565550/demo-version-11-vines-swimming-and-magic), 3) - 🆓 **free** (@johann2?)
- [ ] MiS80 ([1](https://mastodon.gamedev.place/@lpg/110664424682458232), [2](https://twitter.com/LPGhatguy/status/1681394664681635844), [3](https://twitter.com/LPGhatguy/status/1681753363795279873)) - 🆓 **free** (@LPGhatguy?)
- [ ] Syn9Dev's JRPG ([1](https://twitter.com/Syn9Dev/status/1676082920182755332), [2](https://twitter.com/Syn9Dev/status/1676969827980935172)) - 🆓 **free** (@Syn-Nine?)
- [x] Colony ([1](https://reddit.com/r/rust/comments/14p1fiw/opensourcing_my_rust_game_a_colony_simulator_game)) - ✔️ done by @ryankopf
- [ ] HackeRPG ([1](https://fellow-pablo.itch.io/hackerpg), [2](https://fellow-pablo.itch.io/hackerpg/devlog), [3](https://reddit.com/r/hackerpg/comments/1580run/game_for_coders_hackerpg_devlog_1)) - 🆓 **free**
- [ ] xyzw's colony sim ([1](https://reddit.com/r/rust_gamedev/comments/14t8xgw/working_on_a_colonysim), [2](https://twitter.com/xyzw_io/status/1677340923292786689), [3](https://twitter.com/xyzw_io/status/1610083721666875394)) - 🆓 **free** (@zaycev?)
- [x] Cargo Space ([1](https://mastodon.social/@johanhelsing/110682668951960151)) - 🆓 **free** (@johanhelsing?)
- [ ] PatchGames' city builder ([1](https://twitter.com/PatchGamesStdio/status/1677369018225680397), [2](https://youtube.com/@patchgamesstudio/videos)) - 🆓 **free**
- [ ] snaked ([1](https://twitter.com/kuviman/status/1678085582461841412)) - 🆓 **free** (@kuviman?)
- [ ] rust shooter ([1](https://reddit.com/r/rust_gamedev/comments/14wsnhx/rust_shooter_update_lighting_tweaks_and_vehicle)) - 🆓 **free** (@dobkeratops?)
- [ ] Flesh ([1](https://twitter.com/Im_Oab/status/1680027059509407745), [2](https://reddit.com/r/rust_gamedev/comments/15g1aw1/flesh_on_steam)) - 🆓 free (@Im-Oab?)
- [ ] maginet ([1](https://twitter.com/evrimzone/status/1681623714683662336), [2](https://twitter.com/evrimzone/status/1681302065069559812)) - 🆓 **free** (@evrimoztamur?)
- [ ] Robo Instructus 4y ([1](https://twitter.com/bigabgames/status/1680521753653661697)) - 🆓 **free**
- [ ] mochia.net ([1](https://reddit.com/r/rust/comments/15c0j97/a_virtual_pet_site)) - 🆓 **free**
- [ ] Sulis ([1](https://reddit.com/r/rust_gamedev/comments/15754yt/sulis_v100_released_turn_based_tactical_rpg), [2](https://github.com/Grokmoo/sulis/releases)) - 🆓 **free**
- [x] tiny-snake.rs ([1](https://reddit.com/r/rust/comments/15d89s5/tinysnakers)) - ✔️ done by @Rodrigodd
- [x] 8bit Duels ([1](https://thousandthstar.github.io/posts/8bd/8bd-part7)) - ✔️ done by @thousandthstar
- [ ] RecWars ([1](https://reddit.com/r/rust_gamedev/comments/1548teg/resumed_development_on_recwars)) - 🆓 **free**
- [x] Space Kitty ([1](https://reddit.com/r/rust_gamedev/comments/14vormz/small_opensource_game_written_in_rust)) - 🆓 **free** (@ghashy?)
- [x] Cyber Gate 7.5 ([1](https://discord.com/channels/676678179678715904/1023711201886212167/1129721723147784222), [2](https://youtube.com/watch?v=snCBjrPUM5U), [3](https://www.youtube.com/watch?v=dX21NfBmuV0)) - ✔️ done by @cybersoulK
- [x] Ant Colony Sim ([1](https://youtube.com/watch?v=98pUSZAM_7M), [2](https://github.com/bones-ai/rust-ants-colony-simulation)) - ✔️ done by @bones-ai
- [x] Open Combat - ✔️ done by @buxx
- [x] Way of Rhea - ✔️ done by @MasonRemaley

#### Learning Material Updates

- [ ] Gentle intro to GPUs for backend devs pt1 ([1](https://www.xyzw.io/posts/backend-gpu-p1)) - 🆓 **free** (@zaycev?)
- [x] Bevy's Android dev notes + iOS GH ([1](https://mastodon.online/@nikl_me/110679395102169525), [2](https://nikl.me/blog/2023/notes_on_android_development_using_bevy), [3](https://nikl.me/blog/2023/github_workflow_to_publish_ios_app)) - ✔️ done by @NiklasEi
- [ ] Blender to Bevy workflow ([1](https://itch.io/blog/564971/blender-to-bevy-workflow-physics-props)) - 🆓 **free**
- [ ] PhaestusFox’s Bevy videos ([1](https://youtube.com/@PhaestusFox/videos)) - 🆓 **free** (@PhaestusFox?)

#### Engine Updates

- [x] Bevy ([1](https://bevyengine.org/news/bevy-0-11), [2](https://mastodon.social/@bevy/110685755721601977), 3) - ✔️ done by @cart
- [ ] godot-rs ([1](https://twitter.com/GodotRust/status/1677068270644363264), [2](https://mastodon.gamedev.place/@GodotRust/110669301088668526)) - 🆓 **free** (@Bromeon?)
- [ ] Fyrox ([1](https://reddit.com/r/rust/comments/156pq0g/fyrox_0_31)) - 🚧 WIP by @ozkriff
- [ ] ggez ([1](https://reddit.com/r/rust_gamedev/comments/14v6x3z/ggez_news_090_released_and_more)) - 🆓 **free** (@Vixeliz?)

#### Tooling Updates

- [ ] Graphite - 🆓 **free** (@Keavon?)
- [ ] glTF IBL Sampler UI ([1](https://github.com/pcwalton/gltf-ibl-sampler-egui), [2](https://twitter.com/pcwalton/status/1676655721818259456)) - 🆓 **free** (@pcwalton?)
- [ ] ruffle ([1](https://mastodon.archive.org/@textfiles/110697893762381822), [2](https://reddit.com/r/rust/comments/14zvk2l/internet_archive_expands_flash_support_using)) - 🆓 **free**
- [x] Rerun ([1](https://reddit.✔️ done by @Wumpf

#### Library Updates

- [x] bevy_xpbd ([1](https://github.com/Jondolf/bevy_xpbd), [2](https://taintedcoders.com/bevy/xpbd/), [3](https://reddit.com/r/rust_gamedev/comments/14q9j9n/bevy_xpbd_a_physics_engine_for_the_bevy_game/), [4](https://reddit.com/r/rust_gamedev/comments/14zr5i5/bevy_xpbd_02)) - ✔️ done by @Jondolf
- [x] Sparsey ([1](https://reddit.com/r/rust_gamedev/comments/151aov9/sparsey_011)) - ✔️ done by @LechintanTudor
- [ ] Iced ([1](https://reddit.com/r/rust/comments/15e82lr/iced_0_10)) - 🆓 **free** (@hecrj?)
- [ ] bevy_vello ([1](https://github.com/vectorgameexperts/bevy_vello)) - 🆓 **free**
- [ ] cuicui_layout ([1](https://github.com/nicopap/cuicui_layout)) - 🆓 **free**
- [ ] renet ([1](https://github.com/lucaspoffo/renet/releases/tag/0.0.13)) - 🆓 **free** (@lucaspoffo?)
- [x] hanabi ([1](https://github.com/djeedai/bevy_hanabi/blob/v0.7.0/CHANGELOG.md)) - ✔️ done by @djeedai
- [ ] hexx ([1](https://github.com/ManevilleF/hexx/releases/tag/0.8.0), [2](https://github.com/ManevilleF/hexx/releases/tag/0.9.0)) - 🆓 **free** (@ManevilleF?)

#### Other News

- [ ] Bullet points of any interesting news that doesn't have its own section - by @ozkriff

#### Discussions

- [ ] "Data Oriented architectures other than ECS?" ([1](https://reddit.com/r/rust_gamedev/comments/159zfye/data_oriented_architectures_other_than_ecs))

## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @ozkriff
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @ozkriff
- [ ] Add a draft of next month's newsletter - by @ozkriff

**Comment by ozkriff** [comment]
Sorry for starting the July newsletter especially late this time, there were some unfortunate family circumstances. Since the issue is so behind schedule, I've set the contributions deadline to a couple of days - I hope to publish the N48 issue by the end of the week and start N49 for August next week.

**Comment by h3r2tic** [comment]
Thank you, @ozkriff 💞 We're gonna skip July, but we'll have some Tiny Glade stuff to show in the August newsletter!

**Comment by Jondolf** [comment]
I can write a section for bevy_xpbd tomorrow if I have time. Thanks for including it in the list :)

**Comment by Rodrigodd** [comment]
Hello! I see that my project [tiny-snake.rs](https://reddit.com/r/rust/comments/15d89s5/tinysnakers) is included here.

I can gladly write the description for my own project, but that project is more like a demo for a very low level Rust programming (executing syscall's with inline assembly and such) than a actual game. Are you sure it fits in this Newsletter?

**Comment by Indy2222** [comment]
I'll skip this month. If things go smooth, we will have a bigger update next month.

**Comment by Syn-Nine** [comment]
I'll throw something together for my JRPG. Thanks for the tag!

**Comment by scirin** [comment]
leaving a message for notifications

**Comment by ozkriff** [comment]
@Rodrigodd while tiny-snake isn't a mainstream gamedev thing, I think it still fits here, yeah :)

**Comment by Syn-Nine** [comment]
Looks like I won't have time to put something together before the deadline
tomorrow. I'll try again next month. Thanks for asking though! -Syn9Dev

**Comment by bones-ai** [comment]
Just made a PR for Ant colony simulation, Thanks for the ping :)

**Comment by scirin** [comment]
@ozkriff  Let's close this task?
