### ISSUE TITLE
 N49: August 2023

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#1440]
# Newsletter 49: August 2023

###### tags: `newsletter`

**Editors:** @ozkriff, @scirin, @AngelOnFira

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with August's news!

## Current Schedule

**The deadline for all section PRs is 2023.09.15.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Rust Gamedev Meetup

- [ ] Details of this month's meetup - 🆓 **free** (@AngelOnFira @ozkriff?)

#### Game Updates

- [x] Veloren - ✔️ done by @AngelOnFira
- [x] Tiny Glade ([1](https://twitter.com/h3r2tic/status/1677385971061620738), [2](https://twitter.com/anastasiaopara/status/1682762738710241281), [3](https://store.steampowered.com/app/2198150/Tiny_Glade), [4](https://twitter.com/h3r2tic/status/1694441464808300912)) - ✔️ done by by @h3r2tic
- [x] Tunnet ([1](https://puzzled-squid.itch.io/tunnet/devlog/580255/devlog-2-optimizations), [2](https://mastodon.gamedev.place/@puzzled_squid/110957629906247197)) - ✔️ done by @puzzled-squid
- [ ] HackeRPG ([1](https://reddit.com/r/rust_gamedev/comments/15tjrub/road_to_steam_hackerpg_devlog_3), [2](https://reddit.com/r/hackerpg/comments/15gxjqu/cancel_hackerpg_devlog_2), [3](https://reddit.com/r/rust_gamedev/comments/165bmcc/a_new_upgrade_system_hackerpg_devlog_4), [4](https://reddit.com/r/rust_gamedev/comments/167y0qh/the_hacking_system_hackerpg_devlog_5)) - 🆓 **free** (@username?)
- [ ] Mage Rush ([1](https://reddit.com/r/rust_gamedev/comments/15s1i28/a_tiny_vampiresurvivors_like_game)) - 🆓 **free** (@schweller?)
- [ ] Combine And Conquer ([1](https://buckmartin.de/combine-and-conquer/2023-08-18-v0.6.0.html), [2](https://buckmartin.de/combine-and-conquer/2023-08-31-v0.6.2.html)) - 🆓 **free** (@I3ck?)
- [ ] exocave ([1](https://twitter.com/bencarru/status/1692948311383138492)) - 🆓 **free** (@bcarruthers?)
- [x] Tribes ([1](https://uvizhe.im/posts/tribes-p2/)) - ✔️ done by @uvizhe
- [ ] nullableengineer’s mmo ([1](https://youtube.com/watch?v=CT3CXsWZCB4)) - 🆓 **free**
- [ ] terrybrash's top-down arena shooter ([1](https://twitter.com/terrybrash)) - 🆓 **free** (@terrybrash?)
- [x] Ars Militaris ([1](https://arsmilitaris.com/#this-week-in-ars-militaris-vi), [2](https://arsmilitaris.com/#this-week-in-ars-militaris-vii), [3](https://arsmilitaris.com/#this-week-in-ars-militaris-viii)) - ✔️ done by @arsmilitaris
- [ ] Digital Extinction ([1](https://mgn.cz/blog/de10), [2](https://reddit.com/r/rust/comments/1684yi/udigital_extinction_11)) - 🆓 **free** (@Indy2222?)
- [ ] 8bit Duels ([1](https://reddit.com/r/rust_gamedev/comments/165z8a1/i_finished_my_multiplayer_strategy_game_8bit_duels), [2](https://www.youtube.com/watch?v=maKARl89Qos)) - 🆓 **free** (@thousandthstar?)
- [ ] Bare Metal Space Invaders ([1](https://discuss.systems/@federicoponzi/110894964259131323)) - 🆓 **free** (@FedericoPonzi?)
- [x] Graviton ([1](https://reddit.com/r/rust_gamedev/comments/164dyq9/i_recently_added_mirror_draw_mode_shapes)) - ✔️ done by @hakolao
- [x] oort - ✔️ done by @rlane
- [x] CyberGate - ✔️ done by @cybersoulK

#### Learning Material Updates

- [ ] faking pixel art ([1](https://davjcosby.github.io/all-published/miscellaneous-tech/faux-pixel-art-with-blender,-rust,-fancy-color-spaces-and-'borrowed'-algorithms.html), [2](https://twitter.com/cosbdev/status/1688622771973267456)) - 🆓 **free** (@davjcosby?)
- [ ] PhaestusFox’s Bevy videos ([1](https://youtube.com/@PhaestusFox/videos)) - 🆓 **free** (@PhaestusFox?)
- [x] Failed to build multiplayer pong ([1](https://youtube.com/watch?v=wpx9qhKEuP8)) - ✔️ done by @ChristopherBiscardi
- [x] Bevy's android GH ([1](https://nikl.me/blog/2023/github_workflow_to_publish_android_app)) - ✔️ done by @NiklasEi
- [ ] Bevy game in SvelteKit ([1](https://sneakycrow.dev/blog/2023-07-30-bevy-game-in-svelte-kit)) - 🆓 **free** (@sneakycrow?)
 
#### Engine Updates

- [ ] Bevy ([1](https://reddit.com/r/rust/comments/15nnsba/bevys_third_birthday)) - 🆓 **free** (@cart?)
- [x] goku ([1](https://reddit.com/r/rust/comments/165luwu/introducing_goku_engine)) - ✔️ done by @ladroid
- [ ] Rezcraft ([1](https://users.rust-lang.org/t/rezcraft-web-and-native-voxel-engine/99173)) - 🆓 **free**

#### Tooling Updates

- [ ] mimiron ([1](https://reddit.com/r/rust/comments/15jqgmf/cli_app_to_look_up_hearthstone_cards)) - 🆓 **free** (@asibahi?)
- [x] space_editor ([1](https://github.com/rewin123/space_editor)) - ✔️ done by @rewin123
- [ ] Bevy + Overture Maps ([1](https://github.com/alexichepura/bevy_overture_maps), [2](https://youtube.com/watch?v=nnRdNHLJxXs)) - 🆓 **free** (@alexichepura?)

#### Library Updates

- [ ] rivet ([1](https://reddit.com/r/rust/comments/15vgx1u/rivet_opensource_game_server_management)) - 🆓 **free** (@NathanFlurry?)
- [ ] Oceanman ([1](https://tech0tron.net/oceanman-v0.4/)) - 🆓 **free** (@tech0tron?)
- [x] dexterous_developer ([1](https://github.com/lee-orr/dexterous_developer)) - ✔️ done by @lee-orr
- [ ] unrust ([1](https://reddit.com/r/rust_gamedev/comments/164e5ka/rust_unity_bevy_for_games), [2](https://twitter.com/_sandeepnambiar/status/1696467708693324189)) - 🆓 **free** (@gamedolphin?)
- [ ] bevy_mod_raycast ([1](https://github.com/aevyrie/bevy_mod_raycast)) - 🆓 **free** (@aevyrie?)
- [x] nanogltf - ✔️ done by @not-fl3

#### Other News

- [ ] Bullet points of any interesting news that doesn't have its own section - by @ozkrif

#### Discussions

- [ ] "Someday, maybe, we will be game" ([1](https://reddit.com/r/rust_gamedev/comments/15w2ir8/someday_maybe_we_will_be_game_i_hope))
- [ ] "Do you wirte performance tests" ([1](https://reddit.com/r/rust_gamedev/comments/161eaoc/do_you_wirte_performance_tests_for_your_game))

## Publishing Steps

- [ ] Final review - by everyone
- [ ] Publish - by @ozkriff
- [ ] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff
- [ ] Pin thread on Twitter - by @ozkriff
- [ ] Add comment links - by @ozkriff
- [ ] Add a draft of next month's newsletter - by @ozkriff

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

**Comment by NathanFlurry** [comment]
Just got a ping about this -- do you need anything from me on this? Would love to contribute!

**Comment by lee-orr** [comment]
Thanks for the interest in dexterous developer! I gave writing the section a try here: https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1441 - any feedback is welcome :)

**Comment by ChristopherBiscardi** [comment]
dropped a PR for my video 👍 thanks for the ping

**Comment by rewin123** [comment]
Thanks for the mention! I will write a section about space_editor:)

**Comment by ozkriff** [comment]
> <...> do you need anything from me on this? Would love to contribute!

@NathanFlurry I'd appreciate it if you could submit a section about rivet - something similar to https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1408 or any other library/tool description from https://gamedev.rs/news issues. :)

**Comment by hakolao** [comment]
Thanks, added mine!
