### ISSUE TITLE
Newsletter: Create template and document workflow

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#15]
I propose publishing the first newsletter on September 2. After its release, I'm going to strip it down to a bare-bones template (like [it's done in embedded WG](https://raw.githubusercontent.com/rust-embedded/blog/4070de3d5/newsletter-template.md), for example) and add it to the repo so we can start working in the second newsletter.

In https://github.com/rust-gamedev/rust-gamedev.github.io/pull/9#issuecomment-525951305 I've partly mentioned how the collective newsletter creation process could be organized, at what publishing dates we are aiming, etc. This workflow question is closely linked to the creation of the next newsletter and it needs to be discussed and documented (in README, I guess), so I'm going add this to the PR too.

_Related to #2 ("Newsletter")_

**Comment by 17cupsofcoffee** [comment]
I think the workflow you described in the link sounds good, if no one has any objections.
