### ISSUE TITLE
Jobs Section

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#150]
We don't have a policy regarding job offer posts yet and there was some negative feedback about the [job ads in previous newsletter issues](https://rust-gamedev.github.io/posts/newsletter-009/#dungeonfog-is-hiring). 

_from the WG channel on Discord:_

> **aclysma**: I have mixed feelings about a hiring post being the first thing on the newsletter
> **ozkriff**: why? seems like important information to me: opportunities to work on graphics stuff using Rust/wgpu are quite rare atm
> **aclysma**: commercial entities have a natural advantage over non-commercial in marketing.. and the focus being on their company hiring someone instead of how their company is pushing rust game development forward seems more to serve their company's interests than the communities interest
> I'm certainly not saying a hiring post has no value to the community or that it shouldn't be included,  I'd just rather see the top spot go to something that's in service to the community rather than the other way around
> If it was a video of some cool new features with an oh-btw-we're-hiring blurb at the end (i.e. the focus being on showing something new and interesting) then my opinion would probably be different
> **ozkriff**: Will it be better if i swap the hiring section with london talks?
> **aclysma**: I think it would
> or pick a game update to move up
> **XAMPPRocky**: I also agree with moving the job offer down, reading it, it felt like a ad to me.

So I propose adding an optional first-level "Jobs" section (between "Requests for Contribution" and "Bonus"). Any thoughts/opinions/objections? :)

**Comment by ozkriff** [comment]
(Asking because I'd like to add https://www.elektron.se/rust-graphics-engineer/ to May's newsletter issue.)

**Comment by 17cupsofcoffee** [comment]
I'm definitely in favour of having jobs in the newsletter, I think the only part people took issue with last time was putting it above the actual ecosystem news. Sticking it before the bonus section sounds good to me 👍 

Prior art - TWIR also puts the job listings at the end, right before the quote of the week.

**Comment by AlexEne** [comment]
+1 for having them towards the end like on TWIR posts.

**Comment by ozkriff** [comment]
> Embark is also hiring

Those were highlighted in previous newsletter issues, right?

Btw, do we want to only show new openings or list all the actual ones?

I guess we can highlight new openings with a logo/summary and list already highlighted openings as one-liners.

**Comment by datalus** [comment]
I also think having them towards the end is better.

**Comment by AlexEne** [comment]
> Those were highlighted in previous newsletter issues, right?

I probably have missed it. Yes, only new ones makes sense.

**Comment by AlexEne** [comment]
Should we resolve this as it seems we have an agreement on how to add the job listings (at the end of the newsletter) ?
