### ISSUE TITLE
Discussion: Newsletter's Title

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#16]
(Bikeshedding time)

The current draft of the newsletter is titled as "This Month in Rust GameDev #1 - August 2019". At least @Lokathor (and @AlexEne?) aren't happy with this, so I'm creating this issue to document the discussion and decide if we want to change the title.

Discussion so far (from [the newsletter PR](https://github.com/rust-gamedev/rust-gamedev.github.io/pull/9)):

@Lokathor:
> <...> Let's call it the September issue, just being released a _little_ early this time around since it's the first one.

@ozkriff: 
> Why? I've called it "This Month in Rust GameDev \#1 - August 2019" because it describes what happened during August.
>
> Isn't that how newsletters are named usually? https://amethyst.rs/posts/activity-report-july-2019 by @erlend-sh, for example, is called "Activity Report - July 2019" and tells about July's events but is released at the beginning of the next month.

@Lokathor:
> I suppose, in publishing "the Tuesday paper" is the newspaper that was released Tuesday morning, not that's released after Tuesday describing Tuesday.

@ozkriff:
> ([another monthly newsletter naming precedent from TiKV](https://tikv.org/blog/monthly-july-19/) and [from rustsim](https://www.rustsim.org/blog/2019/04/01/this-month-in-rustsim/))
>
> @Lokathor Hmm, calling it a September newsletter still feels a little bit wrong to me, but I'm not a native speaker, so I've I created a small poll in Discourse `wg-gamedev` channel and will change the naming scheme if an alternative will be chosen:
![image](https://user-images.githubusercontent.com/662976/63941086-86047680-ca73-11e9-9de6-12a202c185ea.png)
>
> ^ Btw, the third option is to not mention a month in the title at all (like embedded, CLI, and some other WGs do), but it has its own cons.

@ozkriff:
> Poll results so far are
![image](https://user-images.githubusercontent.com/662976/64011130-c3c0d800-cb23-11e9-8935-6dec3183ea96.png)
and this question doesn't look like a PR blocker to me (because it's a draft and can be renamed before publishing), which is why I propose merging this PR (so other people can send PRs with content) and creating a separate issue about the title.
> <...>

------

From and "gamedev-wg" Discord chat:

@Lokathor:
> Here's the thing: it's not a newsletter that's purely about august events
like, a lot of events will happen and then only sometimes you'll get updates about "what's been happening recently"
like, if an event was in July but didn't get attention, would you deny it a place in a newsletter issue once the article did get written? that's silly

@ozkriff:
> hmm, that's what the "Bonus" section is for

@Lokathor:
> I guess really it's just how normal publishing works for newspapers and magazines and things like that: you call the September Issue the one that comes out at the start of September, you call the Thursday Paper the one that you get Thursday morning, and so on
And then usually you talk about what's happening recently but sometimes you talk about older stuff too
it's not a critical issue
so once we have a newsletter we can just put it out

_Related to #2 ("Newsletter")_

**Comment by ozkriff** [comment]
I think that my problem with using the "next" month in the title is that the title is "_This Month_ in Rust GameDev - {Month} {Year}" and not something more abstract like "Rust GameDev News - {Month} {Year}". And naming newsletters using "This {X} in Rust {Y}" is a tradition of Rust ecosystem that I wouldn't want to break.

**Comment by Lokathor** [comment]
interesting bikeshed to keep going with, the vote seemed clear to me XD

If we named the issue after the time period it comes out near the start of we just also change the title. Instead of "This Month In Rust Gamedev", perhaps something like "The Gamedev WG Newsletter - (MONTH) Edition"

**Comment by AlexEne** [comment]
I am happy :) I just wanted September in the title but that's a tiny detail

**Comment by 17cupsofcoffee** [comment]
I think this issue can be closed now that the first issue is out - would be a bit weird if we changed naming schemes now :p
