### ISSUE TITLE
Newsletter 10 typo: Library & Tooling Updates link

### ISSUE THREAD

**Issue by leudz** [rust-gamedev/rust-gamedev.github.io#170]
Hi, I think there is a typo in the link to the "Library & Tooling Updates" section of the table of contents.

https://rust-gamedev.github.io/posts/newsletter-010/#library--tooling-updates
Where it should be:
https://rust-gamedev.github.io/posts/newsletter-010/#library-tooling-updates

**Comment by ozkriff** [comment]
Thanks! Fixed by ba71c5e6edeffeed68a713ad4c7bca0e77830fe8
