### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#2]
It would be great to start a (monthly?) newsletter for summarizing what interesting stuff happens in the rust gamedev ecosystem.

Examples of newsletters from other rust WGs:

- https://rust-embedded.github.io/blog
- https://rustwasm.github.io

Related to rust-gamedev/wg#10 (_"Create a rust-gamedev.github.io site"_)

**Comment by ozkriff** [comment]
I finally finished a draft/"vertical slice" of a newsletter as I see it (based on @aclysma's template). What do you think about the structure and presentation?

https://gist.github.com/ozkriff/9383de161eb2455cf7d1fda65cdc3696

If nobody objects I'll make a WIP PR tomorrow (or in a few days).

> So the site is on another repo. You can open PRs directly for the website repo.

Hmm, yep, notification noise isn't an issue because of the separate repo so, yeah, it's better to stick to PRs workflow then.

**Comment by jeffvandyke** [comment]
I just came from [Newsletter #1](https://rust-gamedev.github.io/2019/09/02/newsletter-001.html) - very nice! I think some folks (including me) would appreciate a email subscription option like This Week In Rust does (twitter and reddit updates don't show up in my inbox). Perhaps whatever email service they use could be adopted for rust-gamedev?

**Comment by 17cupsofcoffee** [comment]
[They apparently use MailChimp for this](https://github.com/cmr/this-week-in-rust#to-build-the-newsletter) - their free plan only allows up to 2000 subscribers, however, and [they already surpassed that in 2016](https://github.com/cmr/this-week-in-rust/issues/327), so they must be on one of the paid ones.

I think this is definitely a good idea, but we'd need to either find a service with a more generous free plan or figure out a plan for how it'd be paid for.

**Comment by phaazon** [comment]
That makes me think I should really have an RSS stream on my website… I need to check how to do that.

**Comment by ozkriff** [comment]
Created a separate issue for email subscription: #24 (_"Email Subscription"_).

------

The first newsletter is out and the second is in the works - I guess this issue can be closed as completed now?

**Comment by 17cupsofcoffee** [comment]
Yep, don't think there's anything left to do here 👍
