### ISSUE TITLE
Consider for next news letter:  Rust gamedev interviews

### ISSUE THREAD

**Issue by icefoxen** [rust-gamedev/rust-gamedev.github.io#231]
https://rustgamedev.com/episodes  Saw this and was surprised that it wasn't included in the newsletter already, then realized it was brand new.  Haven't actually listened to it yet though, so maybe it's not good.  XD  Will listen to it and see how it is.

**Comment by ozkriff** [comment]
Moving to the next newsletter's coordination issue.
