### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#233]
The newsletter survived its first year so I hope this site is here to stay. it's time to finally rent a "real" domain, I guess.
This question has been raised a few times on WG's discord, but I don't recall any specific decisions/conclusions from them. 
The best free URL that comes to my mind is https://game-dev.rs - what do you think?

_Somewhat related to https://github.com/rust-gamedev/arewegameyet/issues/261 ("Make .rs domain primary?")_

**Comment by zicklag** [comment]
I like game-dev.rs :+1:.

**Comment by AlexEne** [comment]
Sounds good to me. One thing to consider maybe would be setting up some kind of opencollective so we can share the cost of these things as they add up.

**Comment by icefoxen** [comment]
If we're bikeshedding, I'd like to put forward `gamedev.rs`, without the hyphen, though that's purely to make my OCD happy.  Official WG might also be able to help with coordinating funding and stuff, I'd happily donate for a domain.

**Comment by 17cupsofcoffee** [comment]
I believe `gamedev.rs` is [taken](https://who.is/whois/gamedev.rs), unfortunately 😢 

Some other free .rs URLs:

* `rustgamedev.rs` and `rust-gamedev.rs` (bit redundant, but the latter matches the GitHub org name)
* `gamedevelopment.rs` (bit too long...)

I'd also be willing to chip in towards a domain, whether that's by OpenCollective or just a PayPal pool or whatever.

**Comment by ozkriff** [comment]
> ... I'd like to put forward gamedev.rs, without the hyphen ...

@icefoxen I'd prefer gamedev.rs too, but it seems to be already taken by someone. Though, the variant with dash looks not that bad to me. And we have a dash in out current url anyway)

> One thing to consider maybe would be setting up some kind of opencollective so we can share the cost of these things as they add up.

It'd be great, but I'm not sure that I want to volunteer to do this atm. Also, [my humble personal patreon](https://patreon.com/ozkriff) covers current domain expenses.

**Comment by ozkriff** [comment]
Another interestig free(?) URL is `rustgame.dev`, but I'm not sure how I feel about it)

**Comment by kvark** [comment]
I'm strongly in favor of `gamedev.rs` followed by `game-dev.rs`. Looking at `rustgame.dev` it's not consistent with other rusty sites, and it may easily read as "development of Rust game", which is what we want to avoid :)

**Comment by kettle11** [comment]
I've had some luck in the past emailing people to see if they're up for selling their domain to a small developer. If they aren't a monolithic soulless entity maybe the owner would be willing to sell for a reasonable price.

Of course it's a long shot, it's not worth entirely ruling out registered Urls like `gamedev.rs`

**Comment by ozkriff** [comment]
Emailed the owner of gamedev.rs. Most likely they will either ignore or decline the request but let's try.

**Comment by adv0cat** [comment]
devgame.rs
Your domain is available!

**Comment by adv0cat** [comment]
`rustgame.dev`
Your domain is available!

**Comment by zicklag** [comment]
> `devgame.rs`

Sounds a little too much like its a *game* about *development*, not that it's about *game development*.

**Comment by ozkriff** [comment]
> Emailed the owner of gamedev.rs. Most likely they will either ignore or decline the request but let's try.

Yep, they're silent so far. :(

Ok, so I'm buying game-dev.rs and moving the site to it this weekend if there're no objections or better ideas, ok?

**Comment by ozkriff** [comment]
:thinking: https://gdev.rs ?

**Comment by Wodann** [comment]
game-dev.rs sounds good to me. So far it seems like the best alternative to gamedev.rs

**Comment by Friz64** [comment]
As @dasifefe suggested on the Rust Gamedev discord, there's also https://gamedevelopment.rs, which i quite like. Otherwise i would prefer https://game-dev.rs too.

**Comment by ozkriff** [comment]
https://gamedevelopment.rs in my opinion is so long that it defeats the purpose of migrating from the current address

**Comment by Friz64** [comment]
Fair enough :thinking:

**Comment by ozkriff** [comment]
> Ok, so I'm buying https://game-dev.rs and moving the site to it this weekend if there're no objections or better ideas, ok?

Judging by today's feedback on the Discord chats there're quite a few people who really don't like this damn hyphen))

Well, another option is to just postpone all this custom domain stuff and live with our current https://rust-gamedev.github.io URL until a really cool domain name idea comes along that we all agree upon.

**Comment by 17cupsofcoffee** [comment]
Worst comes to worst, we can try to grab `gamedev.rs` on 15th July 2021, assuming they let it expire 😛 

![image](https://user-images.githubusercontent.com/784533/92271788-525af880-eee0-11ea-9e19-f3e372226dbe.png)

**Comment by ozkriff** [comment]
> Emailed the owner of gamedev.rs. Most likely they will either ignore or decline the request but let's try.

Surprise! juratech.rs answered: they actually don't plan to use the gamedev.rs domain now and like what we're doing, so they've transferred the domain as a gift! Preparing for the migration! :smiley:

**Comment by ozkriff** [comment]
:tada: 
https://gamedev.rs
:tada: 

(DNS updates may take a few hours to propagate through the internet)
