### ISSUE TITLE
Introduction post

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/rust-gamedev.github.io#3]
It was mentioned on https://github.com/rust-gamedev/wg/issues/10 that we might want to have  an introduction post talking about what the WG has been up to so far. Figured it might be a good idea to start a discussion on what that might look like 😄 

Some ideas/thoughts:

* We probably want to sum up the goals/charter - if this is going to get posted on URLO/Reddit/etc as people's first introduction to the WG, they'll likely want to know why it exists in the first place 😛 
* What are the big things the WG has done so far that we'd want to highlight? Off the top of my head, I can think of a few:
    * The survey (https://github.com/rust-gamedev/wg/issues/21)
    * Working towards a pure Rust SPIR-V generator (https://github.com/rust-gamedev/wg/issues/23) 
* Should this be a seperate post, or should it be rolled into the first issue of the newsletter (#2)?

**Comment by AlexEne** [comment]
My vote is to not worry too much about how the newsletter should look as we write this one and do this as a first post.

**Comment by Lokathor** [comment]
the `raw-window-handle` thing is our most practical and immediate success i think

**Comment by 17cupsofcoffee** [comment]
Oh wow, I hadn't been keeping up with that but it seems like a really big win to have gotten winit/gfx/etc on board with a shared interface. Definitely need to call that out in the post/newsletter 🙏

**Comment by Lokathor** [comment]
https://github.com/rust-gamedev/wg/issues/26

**Comment by 17cupsofcoffee** [comment]
Posted a first draft for review: #5
