### ISSUE TITLE
Add table of contents

### ISSUE THREAD

**Issue by remram44** [rust-gamedev/rust-gamedev.github.io#38]
The articles are getting long and are organized in multiple sections. It is probably worth having a table of contents at the top or on the side. Example for this week:

* Game Updates
  * Sulis - a Turn-Based RPG
  * Veloren
  * PF Sandbox
  * Antorum
  * Ferris Fencing
  * Tennis Academy v0.03 &amp; v0.0.4
  * piano-rs
  * Will it dissolve?
  * Garden Devlog: October
  * EVE Aether Wars Backend Optimization
  * Robo Instructus
  * Godot and Rust
  * Ludum Dare 45
  * Amethyst Games
* Library &amp; Tooling updates
  * Dev Time Optimization – Part 1 (1.9x speedup, 65% less disk usage)
  * 🛈 Tip: Speed Up Iteration Time By Using LLD Linker
  * RLSL: a Rust to SPIR-V Compiler
  * gfx-rs v0.4
  * Vulkano: Why Command Buffers Are So Complicated?
  * splines v3.0
  * This Month in Mun - October 2019
  * ultraviolet
  * This month in rustsim #8 (Aug - Sep - Oct 2019)
  * cyclone-physics-rs
  * Cynic64’s WIP Rendering Engine
  * Rust Roguelike Tutorial
  * Nannou awarded Mozilla grant for foundational audio development
  * Amethyst
* Popular Workgroup Issues in Github
* Meeting Minutes
* Requests for Contribution
* Bonus

**Comment by ozkriff** [comment]
Hmm, I don't think that ToC would improve the newsletter.

The newsletter has a pretty flat structure, so (as demonstrated in the PRs screenshots) we can't really show the full headers hierarchy, because it's just too big and can take more than a screen (especially on mobile devices). Alternative ToC that is limited to h2 headers just doesn't provide much useful information.

**Comment by 17cupsofcoffee** [comment]
@ozkriff I will take no offense if my PR gets rejected, just wanted to provide an example of what it might look like :) Agree that it doesn't provide a ton of value if we can't show the the individual sections.

I'd like to extract the anchor links bit out into a separate PR though, as that seems more useful.
