### ISSUE TITLE
New game : Le Train Dispatcher 

### ISSUE THREAD

**Issue by Athorus** [rust-gamedev/rust-gamedev.github.io#40]
I've published my game : Le Train Dispatcher
http://athorus.itch.io/ltd

I would be glad and proud if you could talk about this game in your next newsletter. I did not yet promote it. I'm looking for contributors.
If you need some information or materials, let me know if I can help you.

Feel free to comment my work, even though it is not nice, I need that to improve the game. 

Thanks for your works.

**Comment by Lokathor** [comment]
I'm moving this over to the `rust-gamedev.github.io` repository since that's where the newsletter is stored.

**Comment by Lokathor** [comment]
Also, i'm the most interested in your deployment process with building a binary for each of the OSes. Did you do anything special to make sure that the binaries are as portable as possible? Do you have three machines or did you get a CI server to build and store some artifacts for you? How did that all work.

**Comment by ozkriff** [comment]
@Athorus sure, I'll add your game! But if you have time, please send a PR to the current draft file: https://github.com/rust-gamedev/rust-gamedev.github.io/blob/master/_drafts/newsletter-004.md

**Comment by phaazon** [comment]
![](https://phaazon.net/media/uploads/bateman_very_nice.gif)

**Comment by Athorus** [comment]
@Lokathor, first of all, I do not know if the OsX binary works, if someone can test, it will help me.
It was a lot of work to build all the binaries on one computer with one script. If it worth to write something about it, I can help. 

Windows binaries : very easy, as I work with Windows 10
Linux binary : You can use WSL, but you will have to use a Docker image in order to build the binary with an older glibc version (debian jessie in my case)
OsX : I build with WSL and osxcross
Scripts : the building script works on WSL
Crates : I use ggez and imgui which work under Linux, Windows and OsX. 
Resources and files : ggez manages itself files location according to os host. As my resources are small, they are all integrated in the binary thanks to the include_bytes macro.

**Comment by Athorus** [comment]
@ozkriff, i will take a look.

**Comment by Athorus** [comment]
@ozkriff as a game designer with Zemeroth, do you have some tips to give? It seems very difficult to create a small community and to interest some players. I know I will not be rich! :D

**Comment by Athorus** [comment]
Sorry @ozkriff I've never done that before on github, so what should I do ?
Clone the repo on my computer ?
Then create a branch ?
Then what ?

Thanks.

**Comment by zicklag** [comment]
@Athorus You can just click the little pencil icon at the top right of the rendered page on the link that @ozkriff posted above.

GitHub will create a fork and let you edit the file right on the website.

**Comment by Athorus** [comment]
@ozkriff @zicklag I've just created a pull request for Le Train Dispatcher.

I forked, I changed files on my computer, I pushed and then I ask for a PR. Thanks for your help. :)

**Comment by ozkriff** [comment]
Closed by #41

**Comment by ozkriff** [comment]
> @ozkriff as a game designer with Zemeroth, do you have some tips to give? It seems very difficult to create a small community and to interest some players. I know I will not be rich! :D

@Athorus community-building? Ha, I wish I could tell you, but I'm not that experienced myself)

I dunno, start a public devlog and post smaller stuff to twitter (with `#rustlang #gamedev` tags, so it'd be easy to find and RT from twitter.com/rust_gamedev)? Also, your game feels nice in dynamics, so use more GIFs/videos :)
