### ISSUE TITLE
Separate category for engines vs libraries/tools

### ISSUE THREAD

**Issue by martin-t** [rust-gamedev/rust-gamedev.github.io#406]
There are more and more rust engines popping up and the Library & Tooling Updates category is getting quite full, mixing big fully-featured engines with small purpose-build libraries. Have you considered splitting it into 2 categories - one for engines, another for tools and small libraries?

**Comment by ozkriff** [comment]
If there're no objections, we may try it in the next newsletter.

**Comment by ozkriff** [comment]
@martin-t what do you think about the structure of the current draft in this regard?

**Comment by martin-t** [comment]
I like it. Only issue i noticed is that rg3d is in the wrong section - it's an engine, though admittedly this month's update focuses heavily on the editor.

**Comment by ozkriff** [comment]
Fixed in the final draft!
