### ISSUE TITLE
Newsletter 19

### ISSUE THREAD

**Issue by AngelOnFira** [rust-gamedev/rust-gamedev.github.io#496]
### Note from the editor:

Hey everyone! We're starting to change out the lead editor of the newsletter each month, so that the workload isn't so much each month. This month, it's me! I'm Forest, or AngelOnFira. I also edit the weekly blogs for Veloren, co-host the Rust Gamedev Podcast, and run the monthly Rust Gamedev meetup.

We're also going to be transitioning to having authors or volunteers write about their own content, rather than the editing team doing it all at the end :100: This means if you want to see your work in the newsletter, you have to write it yourself! If you're not able to write about your work, feel free to comment and I can assign it 🆓 **free**. We're working on taking some of the load off the editing team where we can with this. Best to keep this sustainable!

Also, we want to make sure contributing to the newsletter feels open to anyone who wants to write a section about their project. If you have anything you can write about, just add a comment to this issue and I'll add it to the todo list :smile:

### Newsletter 19

Feel free to suggest sections!

If you want to help writing the newsletter:

- Read **[CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md)**.
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just an invitation to write the corresponding section if you want, but anyone is free to take it.
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

### Schedule
The deadline for all section PRs is ~~2021.03.04~~ 2021.03.06.
Review will take place on 2021.03.07
Release will be done on 2021.03.08

------

⚠️ [It was decided to try a shorter and more limited section format](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/454): ⚠️

- Only one image (<300kb) or GIF (<2.5mb) before the text. With an optional caption and a mandatory alt text.
- All the (rendered) text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section.
- Third-person perspective.
- 80 chars per MD line and no other markdownlint warnings on CI.
- Only the following simple templates are allowed:

  <details>
   <summary>See the templates</summary>

   For games/apps/libs:

   ```md
   # [Gamename]

   ![alt text](img)
   _optional image label_

   [Gamename] ([GitHub], [Discord], [Twitter]) by [@nickname]
   is ... {short project description in one sentence}.

   {An overview of the recent updates with links to more details}.

   _Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

   {md links block}
   ```

   For articles/videos/etc:

   ```md
   # [Articlename]

   ![alt text](img)
   _optional image label_

   [@nickname] published an [article] about ...
   {overview what the resource is about}.

   _Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

   {md links block}
   ```

  </details>

_`CONTRIBUTING.md` isn't updated for this yet_.

## Current Structure & Status

(_I'll try to keep this updated_)

If you have your own project that you want to write about, just make a comment on this issue!

- [x] Meetup - @AngelOnFira
- [ ] ~~Rust GameDev Podcast Update~~
- [x] Game Updates
  - [x] Station Iapetus - ✔️ done by @mrDIMAS
  - [x] teki - ✔️ done  by @o2sh
  - [x] Flesh - ✔️ done by @Im-Oab
  - [x] Stellary 2 - ✔️ done by @dezajno
  - [x] A/B Street - ✔️ done by @dabreegster
  - [x] dwarf.world - @AlexEne
  - [x] Way of Rhea - ✔️ done by @MasonRemaley
  - [x] Paddlers - ✔️ done by @jakmeier
  - [x] Theta Wave - ✔️ done  by @cdsupina
  - [x] Veloren - ✔️ done by @AngelOnFira
  - [x] Project YAWC - ✔️ done by @junkmail22 
  - [x] Harvest Hero - ✔️ done by @Bombfuse
  - [x] Fishgame - ✔️ done by @not-fl3 
  - [x] SeniorSKY - ✔️ done by @pmathia0
  - [x] Antorum - ✔️ done by @Dooskington 
  - [ ] ~~Rusty Bomber~~
  - [ ] ~~oicana - (@NiklasEi?)~~
  - [ ] ~~Shotcaller - (@erlend-sh?)~~
  - [ ] ~~Bounty Bros - @zicklag~~
  - [ ] ~~Zemeroth - @ozkriff~~
- [x] Learning Material Updates
  - [x] fs exclusive is a lie - ✔️ done by @MasonRemaley
  - [x] Bevy rhythm game tutorial - ✔️ done by @guimcaballero
  - [x] Godot vs Rapier ([1](https://www.reddit.com/r/godot/comments/lauj7e/godot_physics_vs_gdnative_physics_using_rust/)) - ✔️ done by @ozkriff 
- [x] Engine Updates
  - [x] Tetra - @17cupsofcoffee
  - [x] rg3d & rusty-editor - ✔️ done by @mrDIMAS
  - [x] macroquad - ✔️ done by @not-fl3 
  - [x] Dotrix - ✔️ done by @Lowentwickler
  - [ ] ~~ggez - (@icefoxen)~~
- [x] Library & Tooling Updates
  - [x] rkyv v0.3 - ✔️ done by @djkoloski
  - [x] Mun - ✔️ done by @Wodann
  - [x] ldtk-rs - @zicklag
  - [x] bevy_ldtk - @zicklag
  - [x] gfx/wgpunaga - ✔️ done by @kvark
  - [x] egui - ✔️ done by @emilk
  - [x] rafx - ✔️ done by @aclysma
  - [x] basic-universal-rs - ✔️ done by @aclysma
  - [x] Distill - ✔️ done by kabergstrom
  - [ ] ~~Graphite - 🚧 WIP by Keavon~~
  - [ ] ~~Speedy2D ([1](https://www.reddit.com/r/rust_gamedev/comments/lugn7n/speedy2d_easytouse_library_for_graphics_text_and/))~~
  - [ ] ~~gfx-rs ecosystem releases v0.7 ([1](https://www.reddit.com/r/rust/comments/lb46pq/gfxrs_ecosystem_releases_v07/))~~
  - [ ] ~~kira - (@tesselode)~~
  - [ ] ~~gl33 - [1](https://docs.rs/gl33)~~
  - [ ] ~~Dimforge~~
  - [ ] ~~Legion ECS v0.4.0 ([1](https://www.reddit.com/r/rust_gamedev/comments/ls3phh/legion_ecs_v040/))~~
  - [ ] ~~bevy_egui - @mvlabat~~
  - [ ] ~~imgui-rs - @sanbox-irl~~

Final steps:

- [x] final review
- [x] publish
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev
- [x] add comment links
- [x] add a draft of the 20 newsletter

_Editors_: @ozkriff @17cupsofcoffee @AngelOnFira

**Comment by djkoloski** [comment]
I'd like to write about rkyv v0.4 (v0.3 was last newsletter).

**Comment by dabreegster** [comment]
I'll write about A/B Street

**Comment by cdsupina** [comment]
I'll write about Theta Waves. 👍

**Comment by jakmeier** [comment]
I'm happy to write about Paddlers

**Comment by sanbox-irl** [comment]
Unfortunately, no imgui-rs update this month. It's a biggie, and we won't have a release out till next newsletter

**Comment by dezajno** [comment]
I'll give some updates on Stellary 2 :)

**Comment by Lowentwickler** [comment]
I take dotrix of course :)

**Comment by pmathia0** [comment]
I take SeniorSKY

**Comment by AlexEne** [comment]
There's no dwarf.world update this week as I've been busy with other stuff since the last one. Will probably do something for the next one

**Comment by zicklag** [comment]
Man, it's already been a month! :wink: 

No updates yet on Bevy LDtk, ldtk-rs, or Bounty Bros this month.

**Comment by 17cupsofcoffee** [comment]
I'll pick up the Tetra section today (was 0.6 really this month??? what is time any more)

**Comment by o2sh** [comment]
I'll take teki

**Comment by ozkriff** [comment]
No Zemeroth updates this month

**Comment by AngelOnFira** [comment]
Taking Veloren :100:

**Comment by Wodann** [comment]
I'll do the Mun update

**Comment by junkmail22** [comment]
Project YAWC actually got a release this month, so I'd love to report on in this newsletter.

**Comment by Bombfuse** [comment]
Can pick up Harvest Hero for a quick update

**Comment by Dooskington** [comment]
Will write about Antorum

**Comment by not-fl3** [comment]
I will write about macroquad and fishgame

**Comment by Keavon** [comment]
I'll write about Graphite.

**Comment by kabergstrom** [comment]
I'd like to write something about Distill.

**Comment by guimcaballero** [comment]
I'd like to write about my [Bevy rhythm game tutorial](https://caballerocoll.com/blog/bevy-rhythm-game/)

**Comment by Lokathor** [comment]
Library:
```
[gl33](https://docs.rs/gl33) has a 0.2 version out! It's the latest and greatest way to use OpenGL 3.3.
```

**Comment by MasonRemaley** [comment]
Whoops just saw this! I'll submit a PR in a few minutes. :)

**Comment by AngelOnFira** [comment]
@Keavon @kabergstrom @Lowentwickler @Dooskington a ping for sections that still need PRs! Today is the last day for sections to be added, make sure you get them done :smiley: 

There are still several free sections if anyone would like to volunteer and take some of them. Feel free to comment any that you'd like to take :100:

**Comment by Lowentwickler** [comment]
Hey Forest, @AngelOnFira!
Thanks for the reminder!
The week was tough... Did it just now.

**Comment by Keavon** [comment]
Thanks for the reminder @AngelOnFira, I've been traveling the past two days and I'm getting home later today. Is there a specific time of day that'd be the latest you can get it in? I'll probably be back within 8 hours from now, will that be too late?

**Comment by AngelOnFira** [comment]
@Keavon that should be ok, as long as I wake up tomorrow and everything is ready to go :smile: (I'm EST)

**Comment by Dooskington** [comment]
Sorry for the delay. Busy times 😓

**Comment by ozkriff** [comment]
We don't have many learning material updates this month so I'll write a few words about "Godot vs Rapier"

**Comment by AngelOnFira** [comment]
Everyone is invited to review the newsletter (#525)! We're almost done another month's newsletter :smile:

**Comment by ozkriff** [comment]
Woo-hoo! Congrats on the first released newsletter, @AngelOnFira!

**Comment by ozkriff** [comment]
March coordination issue: https://github.com/rust-gamedev/rust-gamedev.github.io/issues/531
