### ISSUE TITLE
Newsletter 21

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/rust-gamedev.github.io#589]
# Newsletter 21

**Editors**: @17cupsofcoffee, @ozkriff and @AngelOnFira

Another month has gone by, so it's time to put together the Rust Gamedev newsletter for April!

If you want to help writing the newsletter:

- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
  - The links in brackets (like "1, 2, 3") are suggestions of links to include in the section. Feel free to add more!
  - Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just a suggestion of who could pick the work up - it's not an obligation, and other people are welcome to take those sections.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint (lint errors will fail the CI build).
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Leave a comment or DM me on Discord if you have any issues.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

------

As with the last few newsletters, we're trying to delegate the writing workload where we can - to quote @AngelOnFira from a few months ago:

> We're also going to be transitioning to having authors or volunteers write about their own content, rather than the editing team doing it all at the end 💯 This means if you want to see your work in the newsletter, you have to write it yourself! If you're not able to write about your work, feel free to comment and I can assign it 🆓 free. We're working on taking some of the load off the editing team where we can with this. Best to keep this sustainable!
>
> Also, we want to make sure contributing to the newsletter feels open to anyone who wants to write a section about their project. If you have anything you can write about, just add a comment to this issue and I'll add it to the todo list 😄

------

## Current Schedule

The soft deadline for all section PRs is the **6th of May**. PRs will usually be accepted as long as they are ready before the newsletter's release, but the earlier the better :)

Review and release will take place around the **8th of May**.

------

⚠️ [We have decided to try a shorter and more limited section format](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/454): ⚠️

- Only one image (<300kb) or GIF (<2.5mb) before the text, with an optional caption and mandatory alt text for accessibility.
- All the rendered text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section (multiple lists are allowed if your project consists of multiple parts that aren't independent enough for their own sections).
- Third-person perspective.
- 80 characters per line and no other markdownlint warnings on CI.

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

_`CONTRIBUTING.md` isn't updated for this yet_.

## Current Structure & Status

Below is a list of our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhastive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

- [x] **Meetup #4** ([1](https://twitter.com/rust_gamedev/status/1381646225448050695)) - ✔️ done by @AngelOnFira
- [x] **Gamedev.rs** ([1](https://reddit.com/r/rust_gamedev/comments/mq6mmj/rustgamedevgithubio_is_now_gamedevrs)) - ✔️ done by @ozkriff
- [ ] **Game Updates**
    - [ ] LD48: Excavation Site Alpha ([1](https://ldjam.com/events/ludum-dare/48/excavation-site-alpha), [2](https://github.com/gamma-delta/ludum-dare-48), [3](https://gamma-delta.itch.io/excavation-site-alpha)) - 🆓 **free** (@gamma-delta?)
    - [x] LD48: Micronaut ([1](https://ldjam.com/events/ludum-dare/48/$242669), [2](https://github.com/Healthire/ld48), [3](https://healthire.itch.io/micronaut)) - ✔️ done by @Healthire
    - [x] LD48: The Submariner ([1](https://ldjam.com/events/ludum-dare/48/the-submariner), [2](https://kettlecorn.itch.io/submariner), [3](https://github.com/kettle11/LD48)) - ✔️ done by @kettle11
    - [x] LD48: Depth First Search ([1](https://ldjam.com/events/ludum-dare/48/depth-first-search), [2](https://github.com/LPGhatguy/ld48-depth-first-search)) - ✔️ done by @LPGhatguy
    - [x] Veloren ([1](https://veloren.net/devblog-116/), [2](https://www.reddit.com/r/rust_gamedev/comments/mur4x2/this_week_in_veloren_116_server_physics/)) - ✔️ done by @AngelOnFira
    - [x] Way of Rhea ([1](https://store.steampowered.com/app/1110620/Way_of_Rhea/)) - ✔️ done by @MasonRemaley
    - [x] The Process ([1](https://twitter.com/PlayTheProcess), [2](https://www.reddit.com/r/rust_gamedev/comments/mopoxk/showcasing_my_game_the_process_built_with_rust/)) - ✔️ done by @setzer22
    - [x] A/B Street ([1](https://twitter.com/CarlinoDustin)) - ✔️ done by @dabreegster
    - [x] Station Iapetus ([1](https://www.reddit.com/r/rust/comments/mkwd7i/station_iapetus_3d_thirdperson_shooter_written_in/)) - ✔️ done by @mrDIMAS
    - [x] MineWars ([1](https://minewars.cc/), [2](https://twitter.com/MineWarsGame), [3](https://reddit.com/r/minewars)) - ✔️ done by @jamadazi
    - [x] Taipo ([1](https://euclidean-whale.itch.io/taipo), [2](https://github.com/rparrett/taipo)) - ✔️ done by @rparrett
    - [x] Project YAWC ([1](https://twitter.com/ProjectYawc/status/1382574412252073984)) - ✔️ done by @junkmail22
    - [ ] Dwarf World ([1](https://dwarf.world/)) - 🆓 **free** (@AlexEne?)
    - [x] Fish Game ([1](https://fedorgames.itch.io/fish-game)) - ✔️ done by @not-fl3
    - [x] Outer Wonders ([1](https://utopixel.itch.io/outer-wonders)) -✔️ done by @utoalex
    - [ ] Rampage ([1](https://thewordnerd.itch.io/rampage), [2](https://github.com/ndarilek/rampage)) - 🆓 **free** (@ndarilek?)
    - [ ] Quadronaut 2000 ([1](https://gibbertonstudios.itch.io/quatronaut2020), [2](https://github.com/ericrasmussen/quatronaut2020), [3](https://twitter.com/AmethystEngine/status/1383122798932074499)) - 🆓 **free** (@ericrasmussen?)
    - [x] Theta Wave ([1](https://twitter.com/carlosupina/status/1382721628610600962), [2](https://github.com/amethyst/theta-wave/releases/tag/v0.1.5)) - ✔️ done by @cdsupina
    - [x] pGLOWrpg ([1](https://twitter.com/pglowrpg/status/1378082402967379972?s=19)) - ✔️ done by @roalyr
    - [ ] fiiish-rs ([1](https://github.com/AndreasOM/fiiish-rs), [2](https://www.reddit.com/r/rust_gamedev/comments/minl71/fiiish_rs_recreating_fiiish_in_rust/)) - 🆓 **free** (@AndreasOM?)
- [x] **Learning Material Updates**
    - [x] Rust Linz: Learning Rust with Game Development ([1](https://www.youtube.com/watch?v=79GyLlXAk-0), [2](https://twitter.com/herberticus/status/1387090355250675716)) - ✔️ done by @17cupsofcoffee 
    - [x] Rust LA: Happiness in Rust ([1](https://www.youtube.com/watch?v=TJ3w-pZ7FMI)) - ✔️ done by @17cupsofcoffee
    - [x] awesome-quads ([1](https://github.com/ozkriff/awesome-quads)) - ✔️ done by @ozkriff
    - [x] Learning OpenGL in 7 days using Rust ([1](https://www.youtube.com/watch?v=KEQIWqSq42k), [2](https://www.reddit.com/r/rust_gamedev/comments/mjhsri/tantan_learns_graphics_programming_with_glium)) - ✔️ done by @ozkriff
    - [x] Shooting Gallery Game in Rust and Bevy in 5 Hours ([1](https://www.youtube.com/watch?v=T1ZT0Ekzvg), [2](https://www.reddit.com/r/rust_gamedev/comments/mx33ag/how_i_made_a_2d_shooting_gallery_game_using_rust/)) - ✔️ done by @ozkriff
    - [x] ~~Fish Game/Nakama tutorial ([1](https://heroiclabs.com/blog/tutorials/rust-fishgame/))~~ - covered in game updates section
    - [x] How to Write a Crash Reporter ([1](https://www.anthropicstudios.com/2021/03/05/crash-reporter/)) - ✔️ done by @MasonRemaley
- [x] **Engine Updates**
    - [x] ~~Bevy 0.5 ([1](https://bevyengine.org/news/bevy-0-5/), [2](https://www.reddit.com/r/rust_gamedev/comments/mljkbk/bevy_05/))~~ - covered in last month's newsletter
    - [x] Macroquad ([1](https://github.com/not-fl3/macroquad)) - ✔️ done by @not-fl3
    - [x] Tetra 0.6.3 and new website ([1](https://github.com/17cupsofcoffee/tetra/blob/main/CHANGELOG.md#063---2021-04-09), [2](https://twitter.com/17cupsofcoffee/status/1380605634828247041), [3](https://twitter.com/17cupsofcoffee/status/1386384569251864586)) - ✔️ done by @17cupsofcoffee
    - [x] Oxygengine ([1](https://github.com/PsichiX/Oxygengine)) - ✔️ done by  @PsichiX
    - [x] rg3d ([1](https://twitter.com/DmitryNStepanov/status/1371825442978693124?s=20)) - ✔️ done by @mrDIMAS
- [ ] **Library & Tooling Updates**
    - [x] wgpu 0.8 ([1](https://github.com/gfx-rs/wgpu/blob/master/CHANGELOG.md)) - ✔️ done by @kvark
    - [x] nalgebra 0.26 ([1](https://www.dimforge.com/blog/2021/04/12/integrating-const-generics-to-nalgebra)) - ✔️ done by @sebcrozet
    - [ ] Mun ([1](https://mun-lang.org/blog/2021/04/11/release-mun-v0-3-0/), [2](https://www.reddit.com/r/rust/comments/mp1p2x/mun_v030_released/)) - 🆓 **free** (@Wodann?)
    - [ ] big-brain ([1](https://twitter.com/zkat__/status/1382169290028285952), [2](https://github.com/zkat/big-brain/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)) - 🆓 **free** (@zkat?)
    - [ ] Bitmapflow ([1](https://github.com/Bauxitedev/bitmapflow)) - 🆓 **free** (@Bauxitedev?)
    - [x] RAUI ([1](https://github.com/PsichiX/raui)) - ✔️ done by @PsichiX
    - [x] profiling ([1](https://twitter.com/aclysma/status/1380877223624912905)) - ✔️ done by @aclysma
    - [x] bevy_egui ([1](https://twitter.com/mvlabat/status/1380906679706001418)) - ✔️ done by @mvlabat
    - [x] opensubdiv-petite ([1](https://crates.io/crates/opensubdiv-petite)) - ✔️ done by @virtualritz
    - [ ] nakama-rs ([1](https://github.com/heroiclabs/nakama-rs)) - 🆓 **free** (@not-fl3?)
    - [x] KindNES ([1](https://github.com/henryksloan/kind-nes/releases/tag/v0.9.1-beta)) - ✔️ done by @henryksloan
    - [x] chip-8-rs ([1](https://github.com/JonathanMurray/chip-8-rs), [2](https://www.reddit.com/comments/mi2r4v), [3](https://www.youtube.com/watch?v=nVDJ5PZpPfI)) - ✔️ done by @JonathanMurray

Final steps:

- [x] Final review - by everyone
- [x] Publish - by @17cupsofcoffee
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff and @17cupsofcoffee
- [x] Add comment links - by @17cupsofcoffee
- [x] Add a draft of the 22nd newsletter - by @17cupsofcoffee

**Comment by ozkriff** [comment]
I'm definitely taking "gamedev.rs" and "awesome-quads" sections.

**Comment by PsichiX** [comment]
taking oxygengine and raui :D

**Comment by virtualritz** [comment]
Taking `opensubdiv-petite`.

**Comment by roalyr** [comment]
pGLOWrpg: #590

**Comment by setzer22** [comment]
I'm taking `The Process` :+1:

**Comment by henryksloan** [comment]
Taking KindNES

**Comment by rparrett** [comment]
Taking `Taipo`

**Comment by aclysma** [comment]
I will write something for profiling and rafx

**Comment by Healthire** [comment]
I'll take LD 48: Micronaut

**Comment by not-fl3** [comment]
Will do macroquad and fishgame

**Comment by cdsupina** [comment]
Update for Theta Wave is in progress.

**Comment by stephanemagnenat** [comment]
I'll like to mention [simple-async-local-executor](https://crates.io/crates/simple-async-local-executor) in libraries.

**Comment by mrDIMAS** [comment]
I'll take rg3d

**Comment by utoalex** [comment]
Would like to write about [Outer Wonders](https://utopixel.itch.io/outer-wonders) (my GitHub handle is this one, not _peacebringer_ 😅)

**Comment by 17cupsofcoffee** [comment]
@utoalex Whoops, think I got mixed up between Discord and GitHub handles, sorry about that 😅

**Comment by utoalex** [comment]
@17cupsofcoffee No problem! Not sure I had given my GitHub handle before anyway 🙂

**Comment by AngelOnFira** [comment]
Taking Veloren, the Rust Game dev meetup, and Bevy 0.5 :smiley:

**Comment by AngelOnFira** [comment]
@17cupsofcoffee I think we can remove bevy, the 0.5 updates were added to last month's newsletter :)

**Comment by JonathanMurray** [comment]
Heya! I'll write something for chip-8-rs! :-)

**Comment by LPGhatguy** [comment]
I'll be doing the write-up for "LD48: Depth First Search", our game jam game! :D

**Comment by sebcrozet** [comment]
Hey! I'll take nalgebra.

**Comment by mrDIMAS** [comment]
Also taking Station Iapetus

**Comment by jamadazi** [comment]
Taking MineWars (Game) and Bevy Cheatbook (Learning).

**Comment by 17cupsofcoffee** [comment]
Picking up "Rust Linz: Learning Rust with Game Development"

**Comment by ozkriff** [comment]
So many cool sections are still unclaimed :( Will try to squeeze out a few PRs before the final draft is ready. Grabbing:
- Learning OpenGL in 7 days using Rust
- Shooting Gallery Game in Rust and Bevy in 5 Hours

**Comment by 17cupsofcoffee** [comment]
⏰ **Last call for submissions** - as soon as @Keavon and @ozkriff's sections are done I'll probably be raising the release PR.

**Comment by Keavon** [comment]
Sorry to hold up the newsletter, crazy crazy week!

**Comment by 17cupsofcoffee** [comment]
🚂 The release PR is ready: #631

Everyone is invited to review, hoping to merge this afternoon!

**Comment by 17cupsofcoffee** [comment]
And it's live! https://gamedev.rs/news/021/

Thank you for everyone's contributions!

**Comment by ozkriff** [comment]
Yay! Congrats on the first released newsletter, @17cupsofcoffee!

**Comment by ZackGabri** [comment]
On the "How To Write a Crash Reporter" section, clicking the section's header redirects correctly to the article, but on the part where it says "@masonremaley wrote an article walking through" clicking on "an article" redirects to [this page](https://gamedev.rs/news/021/crash-reporter) which is just a 404 page

**Comment by 17cupsofcoffee** [comment]
@ZackGabri Good spot, have included a fix in #633.

**Comment by virtualritz** [comment]
I just got https://github.com/virtualritz/libfive-rs in a shape that it may be useful to people. I could do a write up in the next 30 mins. Let me know.

**Comment by PsichiX** [comment]
@virtualritz well, newsletter is actually public now so maybe next issue?

**Comment by virtualritz** [comment]
No wuckers; didn't see it was published. 😄
