### ISSUE TITLE
Newsletter 24

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/rust-gamedev.github.io#719]
# Newsletter 24: July 2021

**Editors**: @17cupsofcoffee, @AngelOnFira, and @ozkriff

Another month has gone by, so it's time to put together the Rust Gamedev newsletter for July! *(hey that kinda rhymed this month)*

If you want to help writing the newsletter:

- Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
  - The links in brackets (like "1, 2, 3") are suggestions of links to include in the section. Feel free to add more!
  - Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just a suggestion of who could pick the work up - it's not an obligation, and other people are welcome to take those sections.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint (lint errors will fail the CI build).
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Leave a comment or DM me on Discord if you have any issues.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

------

As with the last few newsletters, we're trying to delegate the writing workload where we can - to quote @AngelOnFira from a few months ago:

> We're also going to be transitioning to having authors or volunteers write about their own content, rather than the editing team doing it all at the end 💯 This means if you want to see your work in the newsletter, you have to write it yourself! If you're not able to write about your work, feel free to comment and I can assign it 🆓 free. We're working on taking some of the load off the editing team where we can with this. Best to keep this sustainable!
>
> Also, we want to make sure contributing to the newsletter feels open to anyone who wants to write a section about their project. If you have anything you can write about, just add a comment to this issue and I'll add it to the todo list 😄

------

## Current Schedule

The soft deadline for all section PRs is the **7th of August**. PRs will usually be accepted as long as they are ready before the newsletter's release, but the earlier the better :)

------

⚠️ The most important formatting/style rules from [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md):

- Only one image (<300kb) or GIF (<2.5mb) before the text, with an optional caption and mandatory alt text for accessibility.
- All the rendered text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section (multiple lists are allowed if your project consists of multiple parts that aren't independent enough for their own sections).
- Third-person perspective.
- 80 characters per line and no other markdownlint warnings on CI.

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is a list of our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhastive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

- [x] Rust GameDev Meetup - ✔️ done by @AngelOnFira
- [ ] Game Updates
    - [x] Veloren ([1](https://veloren.net/devblog-127/)) - ✔️ done by @AngelOnFira
    - [ ] Zemeroth on Google Play ([1](https://twitter.com/ozkriff/status/1412826788720427018), [2](https://play.google.com/store/apps/details?id=rust.zemeroth)) - 🆓 **free** (@ozkriff?)
    - [ ] Flesh ([1](https://twitter.com/Im_Oab/status/1414866744150171651), [2](https://store.steampowered.com/app/1660850/Flesh/)) - 🆓 **free** (@im-oab?)
    - [ ] A/B Street ([1](https://twitter.com/CarlinoDustin/status/1412907928676311044)) - 🆓 **free**
    - [x] The Process ([1](https://twitter.com/PlayTheProcess/status/1413081233396011012)) - ✔️ done by @setzer22
    - [x] Harvest Hero Origins ([1](https://twitter.com/GemdropGames/status/1414335583078387713), [2](https://twitter.com/GemdropGames/status/1415332132122025988)) - ✔️ done by @Bombfuse
    - [ ] Recall Singularity ([1](https://twitter.com/RecallSingular1/status/1414549318611079173)) - 🆓 **free** 
    - [x] Robo Instructus ([1](https://blog.roboinstruct.us/2021/07/16/2-years-later.html)) - ✔️ done by @alexheretic
    - [x] Fish Fight (fka. Fish Game) ([1](https://twitter.com/fishfightgame/status/1416084939121045507), [2](https://twitter.com/fishfightgame/status/1416491845333536768)) - ✔️ done by @saveriomiroddi
    - [x] Theta Wave ([1](https://github.com/amethyst/theta-wave/releases/tag/v0.1.7)) - ✔️ done by @cdsupina
    - [ ] Stellary 2 ([1](https://twitter.com/CoffeJunkStudio/status/1416329328288227332)) - 🆓 **free** (@dezajno?)
    - [x] Wicked Potions ([1](https://niklme.itch.io/wicked-potions), [2](https://github.com/NiklasEi/wicked_potions)) - ✔️ done by @NiklasEi
- [ ] Learning Material Updates
    - [x] Hands On Rust - in print! ([1](https://pragprog.com/titles/hwrust/hands-on-rust), [2](https://twitter.com/herberticus/status/1418640530125299713)) - ✔️ done by @TheBracket
    - [ ] Rust Bevy Tutorial ([1](https://youtube.com/watch?v=Dl4PJG0eRhg), [2](https://github.com/jeremychone-channel/rust-invaders)) - 🆓 **free** (@jeremychone-channel?)
    - [ ] Rust Roguelike Devlog ([1](https://www.youtube.com/watch?v=VATO_dHFznE), [2](https://github.com/ShaneM123/rogueliketutorial2021)) - 🆓 **free** (@ShaneM123?)
    - [x] Writing an RPG with rg3d ([1](https://rg3d.rs/tutorials/2021/07/09/rpg-tutorial1.html)) - ✔️ done by @MrDIMAS
- [ ] Engine Updates
    - [x] GGEZ 0.6 ([1](https://reddit.com/r/rust_gamedev/comments/oo2uhw/ggez_060_released), [2](https://github.com/ggez/ggez/blob/master/CHANGELOG.md)) - ✔️ done by @icefoxen
    - [ ] Macroquad ([1](https://macroquad.rs/tutorials/android/), [2](https://twitter.com/fedor_games/status/1413594460408139786)) - 🆓 **free** (@not-fl3?)
    - [ ] Oxygengine ([1](https://github.com/PsichiX/Oxygengine)) - 🆓 **free** (@PsichiX?)
    - [x] Emerald ([1](https://github.com/Bombfuse/emerald)) - ✔️ done by @Bombfuse
- [ ] Tooling Updates
    - [x] Graphite ([1](https://github.com/GraphiteEditor/Graphite)) - ✔️ done by @henryksloan
- [ ] Library Updates
    - [ ] forsyth ([1](https://crates.io/crates/forsyth), [2](https://gitlab.com/kento_asashima/forsyth)) - 🆓 **free** (@KentoAsashima?) 
    - [ ] Crevice ([1](https://github.com/LPGhatguy/crevice/blob/main/CHANGELOG.md)) - 🆓 **free** (@LPGhatguy?)
    - [x] Quilkin ([1](https://medium.com/embarkstudios/say-hi-to-quilkin-an-open-source-udp-proxy-88577c795204), [2](https://cloud.google.com/blog/products/gaming/introducing-quilkin)) - ✔️ done by @markmandel
    - [ ] convo ([1](https://crates.io/crates/convo), [2](https://github.com/simbleau/convo)) - 🆓 **free** (@simbleau?)
    - [x] throne ([1](https://github.com/t-mw/throne)) - ✔️ done by @t-mw
    - [x] discord-sdk ([1](https://github.com/EmbarkStudios/discord-sdk)) - ✔️ done by @Jake-Shadle
    - [ ] quad-snd ([1](https://github.com/not-fl3/quad-snd)) - 🆓 **free** (@not-fl3?)
    - [x] godot-egui ([1](https://github.com/setzer22/godot-egui)) - ✔️ done by @setzer22
    - [ ] imgui-wgpu-rs ([1](https://github.com/Yatekii/imgui-wgpu-rs/releases/tag/v0.16.0)) - 🆓 **free** (@Yatekii?)
    - [x] WGPU ([1](https://gfx-rs.github.io/2021/07/16/release-0.9-future.html), [2](https://gfx-rs.github.io/stories/franzplot)) - ✔️ done by @kvark

Final steps:

- [x] Final review - by everyone
- [x] Publish - by @17cupsofcoffee
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @17cupsofcoffee & @ozkriff
- [x] Add comment links - by @17cupsofcoffee
- [x] Add a draft of the 25th newsletter - by @17cupsofcoffee

**Comment by icefoxen** [comment]
ggez 0.6.0 has been released, this is a note to myself to make sure it gets included here~

**Comment by 17cupsofcoffee** [comment]
@icefoxen Have added it to our draft of the plan :+1:

**Comment by t-mw** [comment]
I'll work on the PR for throne

**Comment by djkoloski** [comment]
I'd like to write about [rkyv](https://github.com/rkyv/rkyv) if there's room!

**Comment by Bombfuse** [comment]
Will take Emerald and HHO

**Comment by dabreegster** [comment]
Sorry, once again I'm overloaded, no A/B Street update this month

**Comment by Jake-Shadle** [comment]
Yah, I can take [discord-sdk](https://github.com/EmbarkStudios/discord-sdk).

**Comment by Tarnadas** [comment]
I’d like to write about [Shroom Kingdom](https://shroomkingdom.net/)

See this [blog post](https://net64-mod.github.io/blog/shroom-kingdom/)

**Comment by NiklasEi** [comment]
I'll write something about Wicked Potions

**Comment by setzer22** [comment]
I'll take `godot-egui` and also work in a short piece for _The Process_ if that's okay :+1:

**Comment by setzer22** [comment]
By the way, I think there's a typo in the issue text:
> The soft deadline for all section PRs is the **7th of July**.

Shouldn't it be August?

**Comment by erlend-sh** [comment]
Would someone be so kind as to bundle this post here into a PR of their own? I always goof something up with this PR process.

### Fish Fight

https://user-images.githubusercontent.com/583842/127763195-dd3d2f10-d3a9-498b-b6b9-6c4944589c4e.mp4

Fish Fight [[Twitter](https://twitter.com/fishfightgame)] by @not-fl3 & @erlend-sh 

- Reintroduced the game as the [independent Fish Fight](https://twitter.com/fishfightgame/status/1416084939121045507).
- Team of 10+ collaborators. More later on our practice of 'open hiring'.
- Loads of new weapons added and soon to be introduced:
  - Mind-controlled Jellyfish
  - Kick-bombs (bomberman-style)
  - Cursed Skull
  - Handcannon
  - Gatling gun
  - Sproingers
  - Pirate Boots
  - ..and more!
- Whole new *Environmentals* system added for map-wide events (mass-shark attack incoming! 🦈 )
- Physics doc & improvements

Hoping to go public with the open source repo within a month or so.

**Comment by gschup** [comment]
I'll write a short update on my rollback netcode library GGRS

**Comment by MoleTrooper** [comment]
I'll add a bit about Starframe's new rope physics :wave:

**Comment by saveriomiroddi** [comment]
I'm adding a `Game Updates` subsection for updates about the Fish Game; see https://github.com/rust-gamedev/rust-gamedev.github.io/issues/719#issuecomment-890470297.

**Comment by AngelOnFira** [comment]
> Would someone be so kind as to bundle this post here into a PR of their own? I always goof something up with this PR process.

I'll take care of this @erlend-sh :)

**Comment by thebracket** [comment]
I'll get something about Hands-on Rust for you either later today or in the morning. Thanks!

**Comment by zicklag** [comment]
I'll do an update on Bounty Bros. and Bevy Retrograde.

**Comment by x-52** [comment]
I'll take the RG3D RPG tutorial!

**Comment by markmandel** [comment]
I'll get something to you for Quilkin - probably tomorrow (US/Wed)!

**Comment by 17cupsofcoffee** [comment]
⏰ Reminder that we're aiming to get the newsletter released this weekend - soft deadline for PRs is tomorrow.

**Comment by NiklasEi** [comment]
Would my blog post about asset handling in Bevy apps fit into the newsletter somewhere? https://www.nikl.me/blog/2021/asset-handling-in-bevy-apps/
It's not really a learning material/tooling update

**Comment by 17cupsofcoffee** [comment]
@NiklasEi I think this could fit into a Library Updates section for `bevy_asset_loader`, since it's justifying why that library exists and talking about the future development direction for it :)

**Comment by Keavon** [comment]
Thanks @henryksloan for helping with the Graphite submission!

**Comment by 17cupsofcoffee** [comment]
Going to write a section on Zemeroth, Flesh and Macroquad, and then if there's no more PRs, I'll get the final publication PR ready to go :)

**Comment by 17cupsofcoffee** [comment]
Final review PR is up: #745

**Comment by 17cupsofcoffee** [comment]
...and it's published! Thanks for everyone's contributions 😄
