### ISSUE TITLE
Newsletter 25 - August 2021

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/rust-gamedev.github.io#751]
# Newsletter 25: August 2021

**Editors**: @AngelOnFira, @17cupsofcoffee, and @ozkriff

Another month has gone by, so it's time to put together the Rust Gamedev newsletter for August!

If you want to help writing the newsletter:

- Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
  - The links in brackets (like "1, 2, 3") are suggestions of links to include in the section. Feel free to add more!
  - Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just a suggestion of who could pick the work up - it's not an obligation, and other people are welcome to take those sections.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint (lint errors will fail the CI build).
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Leave a comment or DM me on Discord if you have any issues.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

------

As with the last few newsletters, we're trying to delegate the writing workload where we can - to quote @AngelOnFira from a few months ago:

> We're also going to be transitioning to having authors or volunteers write about their own content, rather than the editing team doing it all at the end 💯 This means if you want to see your work in the newsletter, you have to write it yourself! If you're not able to write about your work, feel free to comment and I can assign it 🆓 free. We're working on taking some of the load off the editing team where we can with this. Best to keep this sustainable!
>
> Also, we want to make sure contributing to the newsletter feels open to anyone who wants to write a section about their project. If you have anything you can write about, just add a comment to this issue and I'll add it to the todo list 😄

------

## Current Schedule

The soft deadline for all section PRs is the **5th of September**. PRs will usually be accepted as long as they are ready before the newsletter's release, but the earlier the better :)

------

⚠️ The most important formatting/style rules from [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md):

- Only one image (<300kb) or GIF (<2.5mb) before the text, with an optional caption and mandatory alt text for accessibility.
- All the rendered text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section (multiple lists are allowed if your project consists of multiple parts that aren't independent enough for their own sections).
- Third-person perspective.
- 80 characters per line and no other markdownlint warnings on CI.

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is a list of our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhastive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

- [x] Rusty Jam ([1](https://itch.io/jam/rusty-jam)) - ✔️ done by @AngelOnFira
- [x] Rust GameDev Meetup - ✔️ done by @AngelOnFira
- [x] Game Updates
    - [x] Pixie Wrangler - ✔️ done by @rparrett
    - [x] vange-rs ([1](https://reddit.com/r/rust_gamedev/comments/pb4hyg/vangers_switched_to_wgsl)) - ✔️ done by @kvark
    - [x] RecWars ([1](https://reddit.com/r/rust_gamedev/comments/oum1ay/recwars)) -  ✔️ done by @martin-t
    - [x] Vehicle Evolver Deluxe ([1](https://reddit.com/r/rust/comments/ozpa6q/i_made_a_web_app_that_learns_to_build_vehicles)) -  ✔️ done by @Bauxitedev
    - [x] Liminal Lab ([1](https://reddit.com/r/rust_gamedev/comments/ouu7xk/liminal_lab_000_my_first_ever_3d_game)) - ✔️ done by @Pebaz
    - [x] Not Snake ([1](https://reddit.com/r/rust_gamedev/comments/p8fdfn/not_snake_my_first_game_released_made_with_bevy)) - ✔️ done by @ramirezmike
    - [x] A Day at the Movies - ✔️ done by @ramirezmike
    - [x] Veloren ([1](https://veloren.net/devblog-127/)) - ✔️ done by @AngelOnFira
    - [x] Shroom Kingdom - ✔️ done by @Tarnadas
    - [x] What's the Word - ✔️ done by @Vrixyz
    - [x] Sombervale - ✔️ done by @parasyte
    - [x] Shattersong Online - ✔️ done by @Healthire
    - [x] The Process ([1](https://twitter.com/PlayTheProcess)) - ✔️ done by @setzer22
    - [x] Fish Fight - ✔️ done by @erland-sh
    - [x] ~~Themengi - 🚧 WIP by @vgel~~
    - [x] ~~A/B Street ([1](https://twitter.com/CarlinoDustin)) - 🆓 **free** (@dabreegster?)~~
    - [x] ~~lowrezjam: Pixel Airplane ([1](https://itch.io/jam/lowrezjam-2021/rate/1158561)) - 🆓 **free** (@not-fl3?)~~
    - [x] ~~olefasting/capstone ([1](https://reddit.com/r/rust_gamedev/comments/p4bo5a/capstone_twilight_of_the_archons), [2](https://reddit.com/r/rust_gamedev/comments/paz35s/capstone_update)) - 🆓 **free** (@olefasting?)~~
    - [x] ~~Totally Relaxing Golf ([1](https://r3s.itch.io/totally-relaxing-golf)) - 🆓 **free** (@r3sgame?)~~
    - [x] Humankind Encyclopedia ([1](https://twitter.com/SobertKaos/status/1429812457820786694)) - ✔️ done by @ozkriff
- [x] Learning Material Updates
    - [x] "Rewriting my mobile game in Rust targeting WASM" ([1](https://reddit.com/r/rust/comments/oxqofv/show_rrust_rewriting_my_mobile_game_in_rust)) - ✔️ done by @lucamoller
- [x] Engine Updates
    - [x] rg3d overview by GFS ([1](https://gamefromscratch.com/rg3d-open-source-rust-3d-game-engine/), [2](https://youtube.com/watch?v=mzshg_0ZvLk)) - ✔️ done by @mrDIMAS
    - [x] ~~Rust RPG Toolkit ([1](https://www.reddit.com/r/rust_gamedev/comments/pcrddz/rust_rpg_toolkit)) - 🚧 WIP by @olefasting~~
    - [x] ~~Macroquad - 🆓 **free** (@not-fl3?)~~
- [x] Tooling Updates
    - [x] Graphite ([1](https://github.com/GraphiteEditor/Graphite)) - ✔️ done by @Keavon
    - [x] rx v0.5 ([1](https://reddit.com/r/rust/comments/p5380p/rx_v05_released_a_modern_and_minimalist_pixel)) - ✔️ done by @cloudhead
- [x] Library Updates
    - [x] GGRS - ✔️ done @gschup
    - [x] wgpu/gfx-rs ([1](https://reddit.com/r/rust/comments/p6z1i3/release_of_a_purerust_wgpu_v010_and_a_call_for)) - ✔️ done by @kvark
    - [x] godot-egui backend as a Godot Editor plugin ([1](https://reddit.com/r/rust_gamedev/comments/pddmk2/egui_running_inside_the_godot_editor_as_a_plugin)) - 🆓 **free** ✔️ done by @setzer22
    - [x] ~~sierra - ✔️ done by @zakarumych~~
    - [x] dimforge ([1](https://www.dimforge.com/blog/2021/08/15/the-last-two-months-in-dimforge)) - ✔️ done by @ozkriff

Final steps:

- [x] Final review - by everyone
- [x] Publish - by @AngelOnFira
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @AngelOnFira & @ozkriff
- [x] Add comment links - by @AngelOnFira
- [x] Add a draft of the 26th newsletter - by @ozkriff

**Comment by gschup** [comment]
I wrote a small bit about GGRS and it's freshly released accompanying bevy plugin! (#753)

**Comment by rparrett** [comment]
I'll write something about

https://github.com/rparrett/pixie_wrangler
https://euclidean-whale.itch.io/pixie-wrangler

**Comment by vgel** [comment]
I'll write an update on Themengi.

**Comment by olefasting** [comment]
I can write something about rust_rpg_toolkit

**Comment by Vrixyz** [comment]
In context of the rusty game jam I’ll write about [what’s the word](https://vrixyz.itch.io/whats-the-word).

**Comment by parasyte** [comment]
Likewise, I have a Rusty Jam entry that I will contribute a section for: [Sombervale](https://github.com/blipjoy/sombervale).

**Comment by martin-t** [comment]
I wrote a bit about RecWars: #757

**Comment by Bauxitedev** [comment]
I'd love to write something, unfortunately I keep running into this issue when trying to build the newsletter with Zola: https://github.com/getzola/zola/issues/1442#issuecomment-912368126

Anyone else with the same issue?

**Comment by Bauxitedev** [comment]
I'll write a bit about Vehicle Evolver Deluxe.

**Comment by olefasting** [comment]
I'm sorry, turns out I am going away on some family business this weekend, so I will have to delay this to next months issue

**Comment by Healthire** [comment]
Would it be okay to add a section on Shattersong Online, or are you keeping the newsletter to non-commercial or open source projects? It's being made entirely in rust. We announced it on July 31 but forgot to mention it for the july newsletter. https://triplehex.dev/shattersong-online/

If I can add it, where should the section go, is there some specific ordering?

**Comment by ramirezmike** [comment]
I'll write about [Not Snake](https://ramirezmike2.itch.io/not-snake) and also my Rusty Jam entry [A Day at the Movies](https://ramirezmike2.itch.io/a-day-at-the-movies)

**Comment by Pebaz** [comment]
I'd like to work on Liminal Lab 000!

**Comment by mrDIMAS** [comment]
I'll write about rg3d.

**Comment by zakarumych** [comment]
I'd write about Sierra update.

**Comment by AngelOnFira** [comment]
A reminder for the WIP items, the soft deadline is tomorrow! (@zakarumych @cloudhead @Keavon @mrDIMAS @Healthire @parasyte @Vrixyz @vgel @Tarnadas)

Also want to ping those who haven't checked in about their projects (@dabreegster @setzer22 @erlend-sh @not-fl3 @olefasting @r3sgame @lucamoller)

**Comment by setzer22** [comment]
Will send my parts tomorrow, thanks for the reminder @AngelOnFira! :)

**Comment by dabreegster** [comment]
No A/B Street update this month, sorry

**Comment by martin-t** [comment]
I fixed my links: #765

**Comment by lucamoller** [comment]
Added "Rewriting my mobile game in Rust targeting WASM" to Learning Material Updates: #766

**Comment by Keavon** [comment]
Sorry to be late, I'm going to finish writing the Graphite post as soon as I wake up in the morning.

**Comment by septum** [comment]
Sorry for submitting after the soft deadline, couldn't work on it then. 

A PR for TO BE DIRE is ready: #774.

**Comment by Keavon** [comment]
Done, sorry for the delay!

**Comment by AngelOnFira** [comment]
As always, inviting everyone to check out the final review #779 :smiley:

**Comment by AngelOnFira** [comment]
And that's that, we're live! Thanks everyone for another great month, see you next time!

https://gamedev.rs/news/025/

(Will post to social media in a few minutes)
