### ISSUE TITLE
Site fails to build: Variable `config.default_language` not found in context while rendering 'index.html'

### ISSUE THREAD

**Issue by Bauxitedev** [rust-gamedev/rust-gamedev.github.io#758]
See https://github.com/getzola/zola/issues/1442#issuecomment-912368126

Basically I get this error when trying to build with Zola 0.14.1 on both Windows 10 and WSL2:
```
Error: Failed to render section '[...]\rust-gamedev.github.io\content\_index.md'
Reason: Failed to render 'index.html'
Reason: Variable `config.default_language` not found in context while rendering 'index.html'
```

Even though the "default_language" is clearly present in config.toml:
```
title = "Rust GameDev WG"
description = "Stay up to date with the progress and recent developments in the Rust Game Development Working Group."
base_url = "https://gamedev.rs/"
default_language = "en"
compile_sass = true
highlight_code = true
generate_feed = true
feed_filename = "rss.xml"
...
```

I'm not sure if this is a Zola issue, or an issue with the newsletter, so I'm opening it on both issue trackers.

Update: changing `config.default_language` to `lang` in index.html seems to fixes the issue.

**Comment by 17cupsofcoffee** [comment]
Our CI is currently pinned to Zola 0.12 - we haven't updated to 0.14 yet (but we should!)
