### ISSUE TITLE
Media formatting

### ISSUE THREAD

**Issue by AngelOnFira** [rust-gamedev/rust-gamedev.github.io#76]
While trying to make a better way to show youtube videos, there was a discussion in #71. It was discussed that it is ideal to stay purely with markdown so that we can see what files look like directly from Github.

It would be nice to have content such as images and gifs be displayed in a bit of a cleaner way in the end product. A big one is centering images, as well as spacing around content. I think this can be done purely through CSS. I think it will really make the newsletter more presentable. I would love to hear other opinions!

![image](https://user-images.githubusercontent.com/14791619/75721294-1ed7b100-5ca6-11ea-8fad-1b5899d4e94e.png)

**Comment by 17cupsofcoffee** [comment]
![image](https://user-images.githubusercontent.com/784533/75722979-46913e00-5cd3-11ea-8e18-86d19dc704b2.png)

How does this look?

**Comment by AngelOnFira** [comment]
@17cupsofcoffee Looks great! tbh wasn't 100% sure how I would execute, so :pray:

**Comment by ozkriff** [comment]
Images look to be slightly off to the right now on mobile:

![image](https://user-images.githubusercontent.com/662976/76096447-2b764500-5fd7-11ea-8911-61e96a97f97a.png)

**Comment by 17cupsofcoffee** [comment]
![image](https://user-images.githubusercontent.com/784533/76120004-79e00f80-5fe8-11ea-94b5-efdb1d684dc2.png)

Looks okay now :)
