### ISSUE TITLE
Discussions section

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#785]
i've been considering for some time to introduce a new "discussions" section into the newsletter for links to handpicked reddit/twitter/urlo/etc threads that provide useful information. should we try it?

> ## Discussions
> 
> - /r/rust_gamedev:
>     - ["Is WGSL a good choice?"](https://reddit.com/r/rust_gamedev/comments/pvbv50/is_wgsl_a_good_choice).
>     - ["Unity files patent for ECS in game engines that would probably affect many Rust ECS crates, including Bevy's"](https://reddit.com/r/rust/comments/pjtpkj/unity_files_patent_for_ecs_in_game_engines_that).

**Comment by AngelOnFira** [comment]
I think this is a good idea. The sections at the bottom are quite cookie-cut from the previous month's newsletter whenever I'm the lead editor. This will also be a good opportunity to add content that might not have had sections written about it?

**Comment by ozkriff** [comment]
I guess it's done.
