### ISSUE TITLE
Explain how to run lints locally on command line

### ISSUE THREAD

**Issue by Bromeon** [rust-gamedev/rust-gamedev.github.io#797]
The [Style Guidelines](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md#style-guidelines) mention:

> * Run MarkdownLint against your changes with our config.
>      * Most editors have a MarkdownLint plugin available (e.g. VS Code, Sublime Text, Vim).

For those who don't have an IDE/editor with the plugin, would it be possible to list the commands necessary to install and run MarkdownLint againt the project's config? For example, something like
```bash
npm install markdownlint # or:
npm install markdownlint --save-dev
# then, explain how to run
```

This is less of an issue if the CI runs automatically on PRs -- which it seems to do for people who have contributed in the past.

Maybe this could also be wrapped in a .sh or .bash script (many Windows users have something like [cmder](https://cmder.net/) or WSL2). As a bonus, in the future there could even be some custom automated checks for rules like "don't use bold/italics", "don't nest bullet points" or "use 3rd person instead of we/our/I/my".

Just writing down some thoughts, even the automated CI is already great 🙂

**Comment by janhohenheim** [comment]
I think we could close this once #1480 is merged, since the checks are so relaxed now
