### ISSUE TITLE
Newsletter 27 - October 2021

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/rust-gamedev.github.io#818]
# Newsletter 27: October 2021

###### tags: `newsletter`

**Editors**: @17cupsofcoffee, @ozkriff, and @AngelOnFira

Another month has gone by, so it's time to put together the Rust Gamedev newsletter for October!

If you want to help writing the newsletter:

- **Please read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
  - The links in brackets (like "1, 2, 3") are suggestions of links to include in the section. Feel free to add more!
  - Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just a suggestion of who could pick the work up - it's not an obligation, and other people are welcome to take those sections.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint (lint errors will fail the CI build).
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Leave a comment or DM me on Discord if you have any issues.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

------

As with the last few newsletters, we're trying to delegate the writing workload where we can - to quote @AngelOnFira from a few months ago:

> We're also going to be transitioning to having authors or volunteers write about their own content, rather than the editing team doing it all at the end 💯 This means if you want to see your work in the newsletter, you have to write it yourself! If you're not able to write about your work, feel free to comment and I can assign it 🆓 free. We're working on taking some of the load off the editing team where we can with this. Best to keep this sustainable!
>
> Also, we want to make sure contributing to the newsletter feels open to anyone who wants to write a section about their project. If you have anything you can write about, just add a comment to this issue and I'll add it to the todo list 😄

------

## Current Schedule

The soft deadline for all section PRs is the **6th of November**. PRs will usually be accepted as long as they are ready before the newsletter's release, but the earlier the better :)

------

⚠️ The most important formatting/style rules from [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md):

- Only one image (<300kb) or GIF (<2.5mb) before the text, with an optional caption and mandatory alt text for accessibility.
- All the rendered text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section (multiple lists are allowed if your project consists of multiple parts that aren't independent enough for their own sections).
- Third-person perspective.
- 80 characters per line and no other markdownlint warnings on CI.

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is a list of our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhastive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

- [x] Rust GameDev Meetup - ✔️ done by @AngelOnFira 
- [x] ~~Rust Graphics Meetup~~ (already covered last month)
- [ ] Game Updates
    - [x] Soldank ([1](https://github.com/smokku/soldank), [2](https://abadcafe.wordpress.com/), [3](https://twitter.com/smokkku)) - ✔️ done by @smokku
    - [x] Veloren ([1](https://veloren.net/devblog-139/)) - ✔️ done by @AngelOnFira
    - [ ] Bitgun ([1](https://twitter.com/LogLogGames), [2](https://store.steampowered.com/app/1673940/BITGUN/)) - 🆓 **free** (@darthdeus?)
    - [x] Way of Rhea ([1](https://twitter.com/AnthropicSt)) - ✔️ done by @MasonRemaley
    - [ ] Nox Futura ([1](https://reddit.com/user/thebracket)) - 🆓 **free** (@thebracket?)
    - [x] Hydrofoil Generation Sailing ([1](https://twitter.com/KunosStefano), [2](https://reddit.com/r/rust_gamedev/comments/qdmeya/hydrofoil_generation_sailing_a_indie_made), [3](https://reddit.com/r/rust_gamedev/comments/qdmeya/hydrofoil_generation_sailing)) - ✔️ done by @kunos
    - [ ] mk48.io ([1](https://mk48.io), [2](https://github.com/SoftbearStudios/mk48)) - 🆓 **free** (@finnbear?)
    - [x] The Process ([1](https://twitter.com/PlayTheProcess/status/1445098719326658562)) - ✔️ done by @setzer22
    - [ ] Recall Singularity ([1](https://youtube.com/watch?v=nsjnCZslNdg), [2](https://twitter.com/RecallSingular1)) - 🆓 **free** (@tom-leys?)
    - [ ] Fish Fight and Fish Fight Prequel ([1](https://twitter.com/fedor_games/status/1447697111001227270), [2](https://github.com/not-fl3/FishFight-The-Prequel/tree/main/fishsteam)) - 🆓 **free** (@not-fl3?)
    - [x] Berry Run ([1](https://bombfuse.itch.io/berry-run)) - ✔️ done by @Bombfuse
    - [x] Lonely Star ([1](https://twitter.com/17cupsofcoffee/status/1452711549802618887)) - ✔️ done by @17cupsofcoffee 
    - [x] LD49 LibraCity ([1](https://github.com/djeedai/libracity), [2](https://twitter.com/djeedai/status/1444784232006623236)) - ✔️ done by @djeedai
    - [ ] LD49 Unbalanced Brawl ([1](https://ldjam.com/events/ludum-dare/49/unbalanced-brawl), [2](https://github.com/yopox/LD49)) - 🆓 **free** (@yopox?)
    - [x] LD49 Me And My Unicycle ([1](https://niklme.itch.io/me-and-my-unicycle), [2](https://twitter.com/nikl_me/status/1445385965619515403)) - ✔️ done by @NiklasEi
    - [ ] LD49 Chevalchemy ([1](https://ldjam.com/events/ludum-dare/49/chevalchemy-a-hoof-of-concept), [2](https://github.com/xlambein/ldjam49), [3](https://twitter.com/xlambein/status/1445005189115748352)) - 🆓 **free** (@xlambein?)
    - [ ] LD49 Proc Spider ([1](https://ldjam.com/events/ludum-dare/49/procedural-spider), [2](https://github.com/darthdeus/procedural-spider)) -  🆓 **free** (@darthdeus?)
    - [x] LD49 Chaos Theory ([1](https://ldjam.com/events/ludum-dare/49/chaos-theory-1), [2](https://github.com/necauqua/chaos-theory)) - ✔️ done by @necauqua
    - [x] LD49 Crunda ([1](https://ldjam.com/events/ludum-dare/49/crunda)) - ✔️ done by @danslocombe
- [ ] Learning Material Updates
    - [x] Herbert's Talk at GameDev Mini-Symposium ([1](https://twitter.com/pragprog/status/1435256552567422979)) - ✔️ done by @17cupsofcoffee 
    - [ ] TanTan's video about voxel game ([1](https://youtube.com/watch?v=G-IuH6R-yD8)) -  🆓 **free** (@TanTanDev?)
- [ ] Engine Updates
    - [x] Amethyst ([1](https://amethyst.rs/posts/amethyst--starting-fresh), [2](https://twitter.com/AmethystEngine/status/1444671106389057536), [3](https://www.reddit.com/r/rust/comments/q0imyn/amethyst_starting_fresh_we_are_officially_halting)) - ✔️ done by @17cupsofcoffee 
    - [x] godot-rust ([1](https://www.youtube.com/watch?v=dTD-_pQ9Vl4)) - ✔️ done by @Bromeon
    - [ ] rg3d 0.23 ([1](https://reddit.com/r/rust/comments/pnhbe4/media_rg3d_023_game_engine_custom_shaders)) - 🆓 **free** (@mrDIMAS?)
    - [ ] macroquad - 🆓 **free** (@not-fl3)
    - [ ] VNgine ([1](https://reddit.com/r/rust/comments/pyvcen/introducing_the_first_prototype_of_vngine), [2](https://gitlab.com/porky11/vngine-rs)) - 🆓 **free** (@porky11?)
    - [ ] Blue Engine ([1](https://github.com/ElhamAryanpur/BlueEngine), [2](https://reddit.com/r/rust_gamedev/comments/q4rana/introducing_blue_engine) - 🆓 **free** (@ElhamAryanpur?)
    - [ ] ~~GGEZ 0.6.1 and good-web-game 0.3.0 ([1](https://psteinhaus.github.io/ggez/web-examples/))~~ covered last month
    - [x] Tetra v0.6.6 - ✔️ done by @17cupsofcoffee 
    - [x] All is Cubes ([1](https://crates.io/crates/all-is-cubes), [2](https://github.com/kpreid/all-is-cubes/blob/main/CHANGELOG.md)) - ✔️ done by @kpreid
- [ ] Tooling Updates
    - [ ] Fearless-NES ([1](https://reddit.com/r/rust/comments/q875p0/fearlessnes_a_nes_emulator_in_rust_using_egui), [2](https://github.com/TomasKralCZ/Fearless-NES)) - 🆓 **free** (@TomasKralCZ?)
- [ ] Library Updates
    - [x] wgpu ([1](https://reddit.com/r/rust_gamedev/comments/q3lfew/wgpu011), [2](https://reddit.com/r/rust/comments/q8e1ex/processing_shaders_talk_from_rust_la_meetup)) - ✔️ done by @kvark
    - [x] bevy_kira_audio v0.6 ([1](https://twitter.com/nikl_me/status/1443965740512591872)) - ✔️ done by @NiklasEi
    - [x] bevy_pen_tool v0.2 ([1](https://github.com/eliotbo/bevy_pen_tool)) - ✔️ done by @eliotbo
    - [x] bevy_verlet ([1](https://twitter.com/ManevilleF/status/1449332859886518275)) - ✔️ done by @ManevilleF
    - [x] bevy_atmosphere ([1](https://crates.io/crates/bevy_atmosphere), [2](https://discord.com/channels/691052431525675048/692648638823923732/901601725071360020)) - ✔️ done by @JonahPlusPlus
    - [ ] Crevice 0.8 ([1](https://github.com/LPGhatguy/crevice/blob/main/CHANGELOG.md#080---2021-10-26)) - 🆓 **free** (@LPGhatguy?)
    - [x] hecs-rapier ([1](https://github.com/smokku/hecs_rapier)) - ✔️ done by @smokku
    - [ ] SPV ([1](https://github.com/AlbinSjoegren/SPV/tree/0.0.6)) - 🆓 **free** (@AlbinSjoegren?)
    - [x] rend3 v0.2 - ✔️ done by @cwfitzgerald
    - [ ] Thunderdome v0.5 ([1](https://github.com/LPGhatguy/thunderdome/blob/main/CHANGELOG.md)) - 🆓 **free** (@LPGhatguy?)
    - [x] Sparsey 0.4 ([1](https://reddit.com/r/rust/comments/q9xix2/sparsey_04)) - ✔️ done by @LechintanTudor
    - [ ] egui 0.15 ([1](https://reddit.com/r/rust/comments/qeue67/announcing_egui_015)) - 🆓 **free** (@emilk?)
    - [ ] puffin-egui/puffin-viewer ([1](https://twitter.com/ernerfeldt/status/1447961523696066564)) - 🆓 **free** (@emilk?)
    - [ ] Shalrath ([1](https://reddit.com/r/rust/comments/qeumo7/announcing_shalrath_a_quake_map_parsing_lib)) - 🆓 **free** (@Shfty?)
- [x] Meeting Minutes - ✔️ done by @17cupsofcoffee 
- [x] Discussions
    - [x] Async Game Server Design ([1](https://users.rust-lang.org/t/tokio-tungstenite-async-game-server-design/65996)) - ✔️ done by @17cupsofcoffee

Final steps:

- [x] Final review - by everyone
- [x] Publish - by @17cupsofcoffee
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @17cupsofcoffee & @ozkriff
- [x] Add comment links - by @17cupsofcoffee
- [x] Add a draft of the 28th newsletter - by @17cupsofcoffee

**Comment by AlbinSjoegren** [comment]
Hey!

I could write something about **SPV**, also please refer to [new](https://github.com/AlbinSjoegren/SPV/tree/main) instead of [1](https://github.com/AlbinSjoegren/SPV/tree/0.0.6).

/Albin Sjögren

**Comment by AngelOnFira** [comment]
We should be able to remove the section about the Rust Graphics Meetup, since although it happened in October, we already discussed it in the [September newsletter](https://gamedev.rs/news/026/#rust-graphics-meetup-1) (unless @kvark has any new plans :+1:)

**Comment by Vrixyz** [comment]
I'll make an entry about https://github.com/Vrixyz/graph_nav

**Comment by 17cupsofcoffee** [comment]
@AngelOnFira Ah, I added it because I thought it was a monthly thing - if not, I'll remove it :)

**Comment by ElhamAryanpur** [comment]
heya, I'd love to write about Blue Engine, however not much changed this month due to exams. next month and a half is expected to be spent towards exam too. Thanks!

**Comment by kunos** [comment]
Will take the Hydrofoil Generation Sailing part.

**Comment by cwfitzgerald** [comment]
I'll pick up rend3

**Comment by djeedai** [comment]
Picking LD49 LibraCity via #822, thanks!

**Comment by kpreid** [comment]
Since you asked me, I wrote a section on All is Cubes in #823.

**Comment by eliotbo** [comment]
I'll introduce bevy_pen_tool.

Eliot

**Comment by smokku** [comment]
Picking Soldank and hecs_rapier

**Comment by setzer22** [comment]
I'll take _The Process_

**Comment by danslocombe** [comment]
Hey I can write about Crunda :)

**Comment by AngelOnFira** [comment]
Just sending out a ping in case you haven't seen this issue yet! (Sorry if you're already working on it :sweat_smile:) This month's "soft" deadline is the 6th :calendar: 

@darthdeus @thebracket @tom-leys @not-fl3 @Bombfuse @NiklasEi @yopox @xlambein @necauqua @TanTanDev @tomaskralcz @ManevilleF @jonahplusplus @LPGhatguy @LechintanTudor @emilk @Shfty

**Comment by LechintanTudor** [comment]
I'll take Sparsey :)

**Comment by Bombfuse** [comment]
keep getting busy and forgetting, but I can throw a small snippet together for Berry Run tonight

**Comment by halvnykterist** [comment]
I'd like to add a section for the game I've been working on, PaddlePunks.

**Comment by PSteinhaus** [comment]
ggez 0.6.1 and gwg 0.3.0 were already covered in last months issue, so they can be removed from the list

**Comment by 17cupsofcoffee** [comment]
Last call for sections! I will be posting the final PR later today.

**Comment by 17cupsofcoffee** [comment]
I will pick up Amethyst, the gamedev mini symposium, and the meeting minutes/discussions section.

**Comment by 17cupsofcoffee** [comment]
The release PR is now up at #846 - everyone is invited to review 🙂 

Aiming to publish the newsletter later this evening all being well.
