### ISSUE TITLE
Newsletter 28 - November 2021

### ISSUE THREAD

**Issue by AngelOnFira** [rust-gamedev/rust-gamedev.github.io#852]
# Newsletter 28: November 2021

###### tags: `newsletter`

**Editors**: @AngelOnFira, @17cupsofcoffee, and @ozkriff

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with November news!

If you want to help writing the newsletter:

- Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
  - The links in brackets (like "1, 2, 3") are suggestions of links to include in the section. Feel free to add more!
  - Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just a suggestion of who could pick the work up - it's not an obligation, and other people are welcome to take those sections.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint (lint errors will fail the CI build).
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Leave a comment or DM me on Discord if you have any issues.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

------

As with the last few newsletters, we're trying to delegate the writing workload where we can - to quote @AngelOnFira from a few months ago:

> We're also going to be transitioning to having authors or volunteers write about their own content, rather than the editing team doing it all at the end 💯 This means if you want to see your work in the newsletter, you have to write it yourself! If you're not able to write about your work, feel free to comment and I can assign it 🆓 free. We're working on taking some of the load off the editing team where we can with this. Best to keep this sustainable!
>
> Also, we want to make sure contributing to the newsletter feels open to anyone who wants to write a section about their project. If you have anything you can write about, just add a comment to this issue and I'll add it to the todo list 😄

------

## Current Schedule

The soft deadline for all section PRs is the **5th of December**. PRs will usually be accepted as long as they are ready before the newsletter's release, but the earlier the better :)

------

⚠️ The most important formatting/style rules from [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md):

- Only one image (<300kb) or GIF (<2.5mb) before the text, with an optional caption and mandatory alt text for accessibility.
- All the rendered text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section (multiple lists are allowed if your project consists of multiple parts that aren't independent enough for their own sections).
- Third-person perspective.
- 80 characters per line and no other markdownlint warnings on CI.

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is a list of our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhastive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

- [x] Rust GameDev Meetup - ✔️ done by @AngelOnFira
- [x] Game Updates
    - [x] Flesh ([1](https://twitter.com/Im_Oab/status/1460457473395986434)) - @Im-Oab
    - [x] One click ninja ([1](https://github.com/fluffysquirrels/one-click-ninja)) - ✔️ done by @fluffysquirrels
    - [x] Fish Fight: Prequel ([1](https://twitter.com/fedor_games/status/1447697111001227270), [2](https://github.com/not-fl3/FishFight-The-Prequel/tree/main/fishsteam), [3](https://reddit.com/r/rust_gamedev/comments/qqvzys/fish_fight_the_prequel_got_a_trailer_and_a_steam)) - ✔️ done by @not-fl3
    - [x] Bitgun ([1](https://twitter.com/LogLogGames), [2](https://twitter.com/LogLogGames/status/1459303436055453701), [3](https://twitter.com/LogLogGames/status/1464009563976392713), [4](https://twitter.com/LogLogGames/status/1463516823605886988)) - ✔️ done by @darthdeus
    - [x] country-slice ([1](https://github.com/anopara/country-slice), [2](https://twitter.com/anastasiaopara/status/1454793167530778628), [3](https://twitter.com/anastasiaopara/status/1464304076074672144)) - ✔️ done @anopara
    - [x] Veloren ([1](https://veloren.net/devblog-139/)) - ✔️ done by AngelOnFira
    - [x] Bendyworm ([1](https://twitter.com/bauxitedev/status/1456931708469719041), [2](https://twitter.com/bauxitedev/status/1462009716914143233)) - ✔️ done @Bauxitedev
    - [x] Halloween Mahjong Solitaire ([1](https://github.com/Syn-Nine/rust-mini-games/tree/main/2d-games/mahjong)) - ✔️ done by @Syn-Nine
    - [x] Molecoole ([1](https://twitter.com/kiss_mrton/status/1459567092995403776)) - ✔️ done @Hilku
    - [x] Hydrofoil Generation Sailing ([1](https://twitter.com/KunosStefano), [2](https://twitter.com/KunosStefano/status/1459187915024748545), [3](https://twitter.com/KunosStefano/status/1461354652209856518), [4](https://reddit.com/r/rust_gamedev/comments/qxid53/hydrofoil_generation_sailing_indie_gamesimulator), [5](https://twitter.com/KunosStefano/status/1461713579946790924), [6](https://twitter.com/KunosStefano/status/1462780294822514689), [7](https://twitter.com/KunosStefano/status/1464257890735304711)) - ✔️ done @kunos
    - [x] Idu ([1](https://twitter.com/epcc10/status/1457521605911871493), [2](https://twitter.com/epcc10/status/1462190818765193230), [3](https://twitter.com/epcc10/status/1463840672335777792)) - ✔️ done (@johann2?)
    - [x] Shroom Kingdom - ✔️ done @Tarnadas
    - [x] Combine&Conquer ([1](https://buckmartin.de/combine-and-conquer.html), [2](https://reddit.com/r/rust_gamedev/comments/qj03ji/i_just_finished_writing_a_detailed_devlog)) - ✔️ done @ozkriff
    - [x] Rust Shooter ([1](https://reddit.com/r/rust_gamedev/comments/r06n8o/rust_shooter_another_update)) - ✔️ done in #other-news
    - [x] Way of Rhea ([1](https://twitter.com/AnthropicSt)) - ✔️ done in #other-news
    - [x] Necrophaser ([1](https://reddit.com/r/rust_gamedev/comments/ql65sw/alpha_release_of_necrophaser)) - ✔️ done in #other-news
    - [x] Soldank ([1](https://twitter.com/smokkku/status/e5bba9b1458971918934159363), [2](https://youtube.com/watch?v=TpnW-nt3q1M)) - ✔️ done in #other-news
    - [x] Stellary 2 ([1](https://twitter.com/CoffeJunkStudio/status/1459493244648280071)) - ✔️ done in #other-news
    - [x] Endless Trial ([1](https://reddit.com/r/rust_gamedev/comments/qw5e36/endless_trial_simple_2d_bullethell_game), [2](https://github.com/vrmiguel/endless-trial)) - ✔️ done in #other-news
    - [x] ~~The Process ([1](https://twitter.com/PlayTheProcess/status/1445098719326658562)) - 🆓 **free** (@setzer22?)~~
    - [x] ~~A/B Street ([1](https://a-b-street.github.io/docs/project/history/retrospective/index.html), [2](https://twitter.com/CarlinoDustin/status/1460064119193620483) - 🆓 **free** (@dabreegster?)~~
- [x] Learning Material Updates
    - [x] Ray Tracer From Scratch ([1](https://github.com/jakobwesthoff/the_ray_tracer_challenge_in_rust), [2](https://youtube.com/watch?v=1l54RUGigtk), [3](https://youtube.com/watch?v=4y1aRPiH9Ko)) - ✔️ done by @jakobwesthoff
    - [x] Rustacean Station 48 ([1](https://rustacean-station.org/episode/048-herbert-wolverson/)) - ✔️ done  by @AngelOnFira
    - [x] Ralph's Posts ([1](https://raphlinus.github.io/ui/graphics/gpu/2021/10/22/swapchain-frame-pacing.html), [2](https://raphlinus.github.io/gpu/2021/11/17/prefix-sum-portable.html)) - ✔️ done @AngelOnFira
    - [x] Hands-on Rust Bonus Content ([1](https://twitter.com/herberticus/status/1457110272515186693)) - ✔️ done @ozkriff
    - [x] Rust Roguelike Tutorial ([1](http://bfnightly.bracketproductions.com/rustbook/chapter_75.html), [2](https://twitter.com/herberticus/status/1463603985730969600))- ✔️ done @ozkriff
    - [x] GBA From Scratch ([1](https://lokathor.github.io/gba-from-scratch/introduction.html), [2](https://twitter.com/Lokathor/status/1455309599054221316)) - ✔️ done in #other-news
    - [x] Ping Pong Tutorial ([1](https://phychic-owl.medium.com/rust-project-ping-pong-game-665766cc45ed)) - ✔️ done in #other-news)
- [x] Engine Updates
    - [x] Tetra 0.6.7 ([1](https://twitter.com/17cupsofcoffee/status/1456688895786106884)) - ✔️ done by @17cupsofcoffee
    - [x] godot-rust ([1](https://twitter.com/GodotRust/status/1458394899339005953)) - ✔️ done by @Bromeon
    - [x] Oxygengine ([1](https://discord.com/channels/676678179678715904/676701885830266891/911695955873632346)) - ✔️ done @PsichiX
    - [x] rg3d ([1](https://twitter.com/DmitryNStepanov/status/1456338636790697986), [2](https://reddit.com/r/rust/comments/qmrx9c/rg3d_game_engine_now_has_a_cheatguide_book), [3](https://discord.com/channels/756573453561102427/756573453561102430/911916187879874570)) -  ✔️ done in #other-news
    - [x] mini/macroquad ([1](https://twitter.com/fedor_games/status/1462804219719831552)) - ✔️ done in #other-news
    - [x] ~~ggez 0.7 ([1](https://reddit.com/r/rust_gamedev/comments/qo5sr8/ggez_07)) - 🆓 **free** (@PSteinhaus?)~~
    - [x] ~~Bevy ([1](https://twitter.com/cart_cart/status/1455372254569717764), [2](https://twitter.com/cart_cart/status/1459363483942719496), [3](https://twitter.com/cart_cart/status/1460743857327378436)) - 🆓 **free** (@cart?)~~
- [x] Tooling Updates
    - [x] SPV v0.1..v0.3 ([1](https://github.com/AlbinSjoegren/SPV), [2](https://discord.com/channels/676678179678715904/676701885830266891/904453701777899670), [3](https://discord.com/channels/676678179678715904/676701885830266891/913892973706641459)) - ✔️ done @AlbinSjoegren
    - [x] PickPicPack ([1](https://twitter.com/p4ymak/status/1459891856389677063), [2](https://github.com/p4ymak/pickpicpack), [3](http://www.p43d.com/pickpicpack)) - ✔️ done @p4ymak
    - [x] Graphite - ✔️ done (@Keavon?)
    - [x] Solid Editor ([1](https://reddit.com/r/rust_gamedev/comments/qrsu1n/solid_editor_a_voxel_editor)) - ✔️ done @ozkriff
- [x] Library Updates
    - [x] pixels v0.8 ([1](https://users.rust-lang.org/t/announcing-pixels-0-8-0/67503)) - ✔️ done by @parasyte
    - [x] quinn 0.8 ([1](https://github.com/quinn-rs/quinn/releases/tag/0.8.0), [2](https://discord.com/channels/676678179678715904/676695619024322561/909562370056142858)) - ✔️ done by @Ralith
    - [x] hecs v0.7 ([1](https://github.com/Ralith/hecs/blob/master/CHANGELOG.md#070), [2](https://discord.com/channels/676678179678715904/676695619024322561/914250017324290060)) - ✔️ done by @Ralith
    - [x] navmesh v0.10..v0.12 ([1](https://github.com/PsichiX/navmesh), [2](https://discord.com/channels/676678179678715904/676695619024322561/914328319925846066)) - ✔️ done @PsichiX
    - [x] Rust-CUDA ([1](https://reddit.com/r/rust/comments/qzv428/announcing_the_rust_cuda)) - ✔️ done @AngelOnFira
    - [x] natura ([1](http://github.com/ziyasal/natura), [2](https://reddit.com/r/rust_gamedev/comments/qlbdmn/preview_a_simple_natura)) - ✔️ done in #other-news
    - [x] ~~Kajiya ([1](https://twitter.com/h3r2tic/status/1455347615722319878), [2](https://twitter.com/h3r2tic/status/1462198747362906112), [3](https://twitter.com/h3r2tic/status/1462971788456079368)) - 🆓 **free** (@h3r2tic?)~~
    - [x] ~~Sparsey v0.5 ([1](https://reddit.com/r/rust/comments/qqcvf6/sparsey_05)) - 🆓 **free** (@LechintanTudor?)~~
- [x] ~~Meeting Minutes - 🚧 WIP by @AngelOnFira~~
- [x] Discussions ([1](https://reddit.com/r/rust_gamedev/comments/qkb77k/using_an_ecs_as_a_generalpurpose_storage_container), [2](https://reddit.com/r/rust_gamedev/comments/qmdw2a/where_to_start), [3](https://reddit.com/r/rust_gamedev/comments/qzhx8u/status_of_wasm32_support), [4](https://reddit.com/r/rust_gamedev/comments/qze1v0/can_rust_do_what_any_c_game_server_can), [5](https://reddit.com/r/rust_gamedev/comments/r0yia7/developing_a_crossplatform_game_for_browser_ios)) - ✔️ done by @ozkriff

Final steps:

- [x] Final review - by everyone
- [x] Publish - by @AngelOnFira
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @AngelOnFira
- [x] Add comment links - by @AngelOnFira
- [x] Add a draft of the 29th newsletter - by @AngelOnFira

**Comment by parasyte** [comment]
Yup, I'll take `pixels` 0.8! 🦀

**Comment by kunos** [comment]
Aye.. will do Hydrofoil Generation. :)

**Comment by jakobwesthoff** [comment]
Yes, will do `Raytracer from Scratch`. 🦀 🔮

**Comment by Bromeon** [comment]
I can do `godot-rust` 🤖🦀

**Comment by Hilku** [comment]
I'll do ` Molecoole ` 🦀🦀

**Comment by cart** [comment]
Bevy didn't have a release this month, so I'll hold off on sharing renderer updates.

**Comment by Tarnadas** [comment]
I'll write about Shroom Kingdom

**Comment by Im-Oab** [comment]
I have some updates for `Flesh` game. :)

**Comment by AlbinSjoegren** [comment]
I will take `SPV` again, still no crate version so it would go under Tooling Updates again

**Comment by dabreegster** [comment]
Sorry, I'm in the middle of moving continents and not likely to make an A/B Street update this month. Also the focus of the project hasn't been on gamification in quite a while, although there is some vague plan to try that again in the future (to get residents involved in planning low-traffic neighborhoods).

**Comment by Bauxitedev** [comment]
I'll write a bit about **Bendyworm**.

**Comment by p4ymak** [comment]
I'll write about **PickPicPack**.

**Comment by PsichiX** [comment]
taking `oxygengine` and `navmesh`

**Comment by LechintanTudor** [comment]
I covered Sparsey 0.5 in the last newsletter and 0.6 will take a bit more time to complete. So no update from me this time :)

**Comment by PSteinhaus** [comment]
There's not that much to say about ggez 0.7.
I plan on releasing 0.8 this month though, so I'll probably write a bit about both releases in the december newsletter.

**Comment by Syn-Nine** [comment]
I'll take Halloween Mahjong Solitaire, thanks for the mention!

**Comment by h3r2tic** [comment]
Thanks for suggesting `kajiya` ❤ ... however I'd rather hold off on that until it actually goes open source. Supposed to be very soon now, but I'm still waiting for some approvals.

**Comment by Ralith** [comment]
Took Quinn and hecs.

**Comment by AngelOnFira** [comment]
@logicsoup just pinging in case @johann2 isn't able to do Idu :)

**Comment by experiment9123** [comment]
i can write a little update for 'Rust Shooter'

**Comment by AngelOnFira** [comment]
Just a reminder to people that today is the deadline!

(@Tarnadas @experiment9123 @PsichiX @AlbinSjoegren @p4ymak)
Looks like you have sections as WIP for you

(@MasonRemaley @setzer22 @smokku @dezajno @I3ck @johann2 @vrmiguel @thebracket @raphlinus @Lokathor @harshvishu @mrDIMAS @not-fl3 @oskargustafsson @Keavon @ziyasal @RDambrosio016)
Looks like you have sections that you can take if you're available/have updates 🙂 


Also, if you have extra time today, feel free to take a few free sections!

**Comment by p4ymak** [comment]
Can't push my commit..
```
p4ymak@Legion:~/Work/00_P4/Rust/rust-gamedev.github.io$ git push
remote: Permission to rust-gamedev/rust-gamedev.github.io.git denied to p4ymak.
fatal: unable to access 'https://github.com/rust-gamedev/rust-gamedev.github.io.git/': The requested URL returned error: 403
```
what am I doing wrong? = )

**Comment by AlbinSjoegren** [comment]
> Can't push my commit..
> 
> ```
> p4ymak@Legion:~/Work/00_P4/Rust/rust-gamedev.github.io$ git push
> remote: Permission to rust-gamedev/rust-gamedev.github.io.git denied to p4ymak.
> fatal: unable to access 'https://github.com/rust-gamedev/rust-gamedev.github.io.git/': The requested URL returned error: 403
> ```
> 
> what am I doing wrong? = )

Try doing a pull request and not a push (pull your fork).

**Comment by johann2** [comment]
I'm doing Idu, I hope it's not too late

**Comment by PsichiX** [comment]
got my job done for today, gonna need ~30 minutes to write my part :D

**Comment by Keavon** [comment]
Finishing up writing Graphite's piece as soon as I wake up. Don't let this block the release though, proceed without it if I'm not done in time.

**Comment by setzer22** [comment]
No update from me this month, probably the next one! :smile:

**Comment by PsichiX** [comment]
btw. what are guides on ordering? bc i always place my notes in order defined in main issue, but sometimes my bits gets reordered.

**Comment by AngelOnFira** [comment]
@PsichiX When I'm editor, I order content based on which PR is made first for each section, unless one requires changes, in which case I take it out of the queue :) Since this is resolved at merge-time, and often has to be changed anyways when I have to merge several PRs at the same time, I haven't explicitly stated it in writing.

I try to also use it as incentive for authors to get their posts done more quickly :)

**Comment by AngelOnFira** [comment]
Taking Rustacean Station, Ralph's Posts, and Rust-Cuda

**Comment by ozkriff** [comment]
I'll try to quickly write out "Combine And Conquer", "Endless Trial", "Hands-on Rust Bonus Content", and "Solid Editor".

**Comment by PsichiX** [comment]
> I try to also use it as incentive for authors to get their posts done more quickly :)

that's something worth noting in the newsletter issues or readme 😅

**Comment by halvnykterist** [comment]
I'd like to add a section for paddlepunks if it's not too late!

**Comment by AngelOnFira** [comment]
The final draft is up, feel free to take a look and comment on any issues you come across!

https://agitated-saha-af60ca.netlify.app/

**Comment by PsichiX** [comment]
Rust CUDA seems to have missing link - `[Rust CUDA]`

**Comment by AngelOnFira** [comment]
@PsichiX Sorry, can I get you to repost that on #887? My bad for not including the link :sweat_smile:

**Comment by PsichiX** [comment]
i mean i's not mine, i just found weird formatting and dunno what the link is :D

**Comment by PsichiX** [comment]
but i'll repost ;p
