### ISSUE TITLE
Newsletter 29 - Dec 2021

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#888]
# Newsletter 29: December 2021

###### tags: `newsletter`

**Editors**: @ozkriff, @17cupsofcoffee, and @AngelOnFira

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with December news!

If you want to help writing the newsletter:

- Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
  - The links in brackets (like "1, 2, 3") are suggestions of links to include in the section. Feel free to add more!
  - Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just a suggestion of who could pick the work up - it's not an obligation, and other people are welcome to take those sections.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint (lint errors will fail the CI build).
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Leave a comment or DM me on Discord if you have any issues.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

------

As with the last few newsletters, we're trying to delegate the writing workload where we can - to quote @AngelOnFira from a few months ago:

> We're also going to be transitioning to having authors or volunteers write about their own content, rather than the editing team doing it all at the end 💯 This means if you want to see your work in the newsletter, you have to write it yourself! If you're not able to write about your work, feel free to comment and I can assign it 🆓 free. We're working on taking some of the load off the editing team where we can with this. Best to keep this sustainable!
>
> Also, we want to make sure contributing to the newsletter feels open to anyone who wants to write a section about their project. If you have anything you can write about, just add a comment to this issue and I'll add it to the todo list 😄

------

## Current Schedule

The soft deadline for all section PRs is the **8th of Jan**. PRs will usually be accepted as long as they are ready before the newsletter's release, but the earlier the better :)

------

⚠️ The most important formatting/style rules from [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md):

- Only one image (<300kb) or GIF (<2.5mb) before the text, with an optional caption and mandatory alt text for accessibility.
- All the rendered text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section (multiple lists are allowed if your project consists of multiple parts that aren't independent enough for their own sections).
- Third-person perspective.
- 80 characters per line and no other markdownlint warnings on CI.

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is a list of our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhastive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

- [x] Rust GameDev Meetup - ✔️ done by @AngelOnFira
- [x] Game Updates
    - [x] Veloren ([1](https://veloren.net/devblog-139/)) - ✔️ done by @AngelOnFira
    - [x] ~~Hydrofoil Generation Sailing ([1](https://twitter.com/KunosStefano/status/1473237800908644352)) - 🚧 WIP by @kunos~~
    - [x] Tet-Rust & The Beast of Monte Carlo ([1](https://github.com/Syn-Nine/rust-mini-games/tree/main/2d-games/tet-rust), [2](https://twitter.com/Syn9Dev/status/1470092175245549586)) - ✔️ done by @Syn-Nine
    - [x] Fish Fight v0.3 ([1](https://reddit.com/r/rust/comments/rebk0r/media_fish_fight_v03), [2](https://twitter.com/fishfightgame/status/1475995140841947142)) - ✔️ done by @erlend-sh
    - [x] country-slice ([1](https://twitter.com/anastasiaopara/status/1469651149422800896)) - ✔️ done by @anopara
    - [x] Molecoole ([1](https://twitter.com/kiss_mrton/status/1467242884927614976), [2](https://twitter.com/kiss_mrton/status/1473725282918014977)) - ✔️ done by @Hilku
    - [x] 10x Sprint Master ([1](https://e-net4.itch.io/10x-sprint-master), [2](https://discord.com/channels/676678179678715904/676701885830266891/915305686039134218), [3](https://dev.to/e_net4/10x-sprint-master-a-technical-and-social-experiment-ahp)) - ✔️ done by @Enet4
    - [x] Bitgun ([1](https://twitter.com/LogLogGames/status/1470392937838256131), [2](https://twitter.com/LogLogGames/status/1473402675106570249)) - ✔️ done by @darthdeus
    - [x] bevy_combat ([1](https://github.com/ElliotB256/bevy_combat)) - ✔️ done by @ozkriff
    - [x] Rust City ([1](https://twitter.com/oliviff/status/1471781741279027204), [2](https://twitter.com/oliviff/status/1472240179301822471), [3](https://twitter.com/oliviff/status/1473266319881654274)) - ✔️ done by @ozkriff
    - [x] Antorum Isles ([1](https://ratwizard.dev/dev-log/antorum/39)) - ✔️ done by @ozkriff
- [x] Learning Material Updates
    - [x] Vange-rs: WebAssembly in Rust ([1](https://twitter.com/caiiiycuk/status/1474366928777060353), [2](https://reddit.com/r/rust_gamedev/comments/rdbl7u/vangers_running_on_webgl)) - ✔️ done by @ozkriff
    - [x] Rust SFML Windows Setup ([1](https://youtube.com/watch?v=nnojR-8PT4M)) - ✔️ done by @ozkriff
    - [x] Rust and Unity game development ([1](https://youtu.be/L7M_vbo1N2g), [2](https://github.com/TanTanDev/runity)) - ✔️ done by @ozkriff
    - [x] Tetris livecoding ([1](https://reddit.com/r/rust/comments/rk8zv5/livecoding_a_tetris_clone_to_showcase)) - ✔️ done by @ozkriff
- [x] Engine Updates
    - [x] Rusty Engine ([1](https://github.com/CleanCut/rusty_engine), [2](https://twitter.com/nathanstocks/status/1476724623903367168)) - ✔️ done by @CleanCut
    - [x] Pyxel ([1](https://github.com/kitao/pyxel), [2](https://reddit.com/r/rust/comments/rh10w6/media_pyxel_v15_a_retro_game_engine), [3](https://twitter.com/kitao/status/1475095396724899843)) - ✔️ done by @ozkriff
- [x] Tooling Updates
    - [x] ~~SPV 0.3.7 ([1](https://github.com/AlbinSjoegren/SPV/releases/tag/0.3.7)) - 🆓 **free** (@AlbinSjoegren?)~~
    - [x] Blackjack - ✔️ done by @setzer22
    - [x] Graphite - ✔️ done by @Keavon
    - [x] Guitar tab viewer ([1](https://notation.fun), [2](https://github.com/notation-fun/notation), [3](https://reddit.com/r/rust_gamedev/comments/r9erd2/guitar_tab_viewer_in_rust_and_bevy)) -         - [x] Pyxel ([1](https://github.com/kitao/pyxel), [2](https://reddit.com/r/rust/comments/rh10w6/media_pyxel_v15_a_retro_game_engine), [3](https://twitter.com/kitao/status/1475095396724899843)) - ✔️ done by @ozkriff
- [x] Library Updates
    - [x] kajiya ([1](https://medium.com/embarkstudios/homegrown-rendering-with-rust-1e39068e56a7), [2](https://reddit.com/r/rust/comments/rkqmk3/homegrown_rendering_with_rust/), [3](https://github.com/EmbarkStudios/kajiya/#platforms), [4](https://github.com/h3r2tic/cornell-mcray), [5](https://twitter.com/h3r2tic/status/1473856011941425155)) - ✔️ done by @h3r2tic
    - [x] assets_manager v0.7 ([1](https://github.com/a1phyr/assets_manager), [2](https://discord.com/channels/676678179678715904/676695619024322561/919735385876217887)) - ✔️ done by @a1phyr
    - [x] Shard 0.2 ([1](https://reddit.com/r/rust/comments/r6mn0g/announcing_shard_020_the_no_std_ecs)) - ✔️ done by @HindrikStegenga
    - [x] bevy_proto ([1](https://github.com/MrGVSV/bevy_proto)) - ✔️ done by @MrGVSV
    - [x] bevy-remote-devtools ([1](https://github.com/reneeichhorn/bevy-remote-devtools)) - ✔️ done by @reneeichhorn
    - [x] wgpu ([1](https://reddit.com/r/rust_gamedev/comments/rjci2n/wgpu012_is_released), [2](https://reddit.com/r/rust/comments/rob7yz/this_year_in_wgpu_2021/)) - ✔️ done by @kvark
    - [x] Pixels v0.9 - ✔️ done by @parasyte
    - [x] rapid-qoi ([1](https://github.com/zakarumych/rapid-qoi), [2](https://twitter.com/zakarum4/status/1473784020450349058)) - ✔️ done by @zakarumych
    - [x] ash v0.34 ([1](https://github.com/MaikKlein/ash/releases/tag/0.34.0)) - ✔️ done by @ozkriff
- [x] Other News
    - [x] Game Updates
        - [x] Bendyworm ([1](https://twitter.com/bauxitedev/status/1467817606111498240)) - ✔️ done by @ozkriff
        - [x] aous ([1](https://vleue.itch.io/aous), [2](https://twitter.com/FrancoisMockers/status/1466125019822673929)) - ✔️ done by @ozkriff
        - [x] Rust Shooter ([1](https://reddit.com/r/rust_gamedev/comments/rj5lut/rust_shooter_another_update)) - ✔️ done by @ozkriff
    - [x] Engine Updates
        - [x] Oxygengine ([1](https://reddit.com/r/rust_gamedev/comments/r5xobe/oxygengine_rpg_game_template_wip), [2](https://discord.com/channels/676678179678715904/676695619024322561/919826315144744960), [3](https://discord.com/channels/676678179678715904/676695619024322561/918013993136820254)) - ✔️ done by @ozkriff
        - [x] rg3d ([1](https://youtube.com/watch?v=TQaCyC_tGko), [2](https://youtube.com/watch?v=OsZCusri1Nw), [3](https://youtube.com/watch?v=FGi8evJFdnw)) - ✔️ done by @ozkriff
        - [x] godot-rust ([1](https://twitter.com/GodotRust/status/1472269798641971200)) - ✔️ done by @ozkriff
    - [x] Library Updates
        - [x] bevy_midi v0.2 ([1](https://github.com/BlackPhlox/bevy_midi)) - ✔️ done by @ozkriff
        - [x] egui 0.16 ([1](https://reddit.com/r/rust/comments/rrantt/announcing_egui_016), [2](https://twitter.com/ernerfeldt/status/1476170987347582977)) - ✔️ done by @ozkriff
- [x] Discussions ([1](https://reddit.com/r/rust_gamedev/comments/r8jh5z/should_i_use_a_syncawait_threads_or_both_to_make_server), [2](https://reddit.com/r/rust_gamedev/comments/r88cjh/should_i_go_through_the_rust_wasm_book_before), [3](https://reddit.com/r/rust_gamedev/comments/rcpzcu/do_any_enginesframeworks_have_console_support_yet), [4](https://reddit.com/r/rust_gamedev/comments/rhd8ou/rust_server_for_unreal_engine_client)) - ✔️ done by @ozkriff

Final steps:

- [x] Other News - by @ozkriff
- [x] Final review - by everyone
- [x] Publish - by @ozkriff
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff
- [x] Add comment links - by @ozkriff
- [x] Add a draft of the n30 - by @17cupsofcoffee

**Comment by kunos** [comment]
I'll pass for this month, wgpu port for Hydrofoil Generation is not done yet, nothing much to say.
Looking forward to write something for next newsletter.

**Comment by Enet4** [comment]
> 10x Sprint Master (1, 2) - free free (@Enet4?)

Absolutely! I already started work on the section.

**Comment by CleanCut** [comment]
> with November news!

Er, December? 😄 

I'll add a thing about the Rusty Engine 3.0 release!

**Comment by CleanCut** [comment]
I don't see a `/content/news/29/index.md` file to add anything to. Who adds that?

**Comment by 17cupsofcoffee** [comment]
@CleanCut: Whoops, that should have been done as part of #852 - I will raise a PR to add it now.

**Comment by 17cupsofcoffee** [comment]
Actually, I apparently have `source` branch powers, so I committed it directly (it's just a copy and paste of the template so hopefully @ozkriff won't be mad at me :p). Should be good to go now!

**Comment by CleanCut** [comment]
@17cupsofcoffee Thanks! Made my PR in #889

**Comment by setzer22** [comment]
I'd be happy to write up a piece on [Blackjack](https://www.reddit.com/r/rust_gamedev/comments/rufvlc/meet_blackjack_a_3d_procedural_modelling/) if you think that fits?

**Comment by Bromeon** [comment]
We will skip a godot-rust update this time, most changes in December were internal and not that interesting.
Will follow up for January 🙂

**Comment by AlbinSjoegren** [comment]
Nothing big on SPV, working on a report featuring it but no big updates this month.  No need to have it in this month.

**Comment by TheFern2** [comment]
Thanks for the shoutout my [Rust Setup for Windows MSVC](https://www.youtube.com/watch?v=nnojR-8PT4M) is specifically for MSVC toolchain. I've also updated the [rust-sfml wiki](https://github.com/jeremyletang/rust-sfml/wiki/Windows) as per my video. If anyone finds any issues don't hesitate to contact me fernandobe+git@pm.me

**Comment by HindrikStegenga** [comment]
I added a small section about my ECS crate in #896.

**Comment by AngelOnFira** [comment]
I'll aim to do Veloren and the gamedev meetup after today's meetup. I might also take some other sections if I have the energy :)

**Comment by Keavon** [comment]
Will write up the article for Graphite in the hours after the meetup.

**Comment by mkiss-crey** [comment]
I'll write about Molecoole soon.

**Comment by Hilku** [comment]
I'll write about Molecoole soon.

**Comment by h3r2tic** [comment]
I'll take `kajiya`!

**Comment by AngelOnFira** [comment]
No meeting minute updates for December!

**Comment by anopara** [comment]
Hope I'm not late yet! I can write about `country-slice`

**Comment by Keavon** [comment]
Working on the Graphite section now. It'll be a couple hours if history is precedent.

**Comment by ozkriff** [comment]
Sorry for the delay, I'll try to prepare the final draft and release the issue later today.

I guess no more contributions are coming at this point, so I'm taking all the unclaimed sections to either write their sections (if they have enough content) or put them into the Other News section as oneliners.

**Comment by ozkriff** [comment]
Sorry for the delay, here's the release: https://gamedev.rs/news/029!
