### ISSUE TITLE
Newsletter 30 - January 2022

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/rust-gamedev.github.io#912]
# Newsletter 30: January 2022

###### tags: `newsletter`

**Editors**: @17cupsofcoffee, @ozkriff, and @AngelOnFira

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with January news!

If you want to help writing the newsletter:

- Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
  - The links in brackets (like "1, 2, 3") are suggestions of links to include in the section. Feel free to add more!
  - Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just a suggestion of who could pick the work up - it's not an obligation, and other people are welcome to take those sections.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint (lint errors will fail the CI build).
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Leave a comment or DM me on Discord if you have any issues.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

------

As with the last few newsletters, we're trying to delegate the writing workload where we can - to quote @AngelOnFira from a few months ago:

> We're also going to be transitioning to having authors or volunteers write about their own content, rather than the editing team doing it all at the end 💯 This means if you want to see your work in the newsletter, you have to write it yourself! If you're not able to write about your work, feel free to comment and I can assign it 🆓 free. We're working on taking some of the load off the editing team where we can with this. Best to keep this sustainable!
>
> Also, we want to make sure contributing to the newsletter feels open to anyone who wants to write a section about their project. If you have anything you can write about, just add a comment to this issue and I'll add it to the todo list 😄

------

## Current Schedule

The soft deadline for all section PRs is the **8th of Feb**. PRs will usually be accepted as long as they are ready before the newsletter's release, but the earlier the better :)

------

⚠️ The most important formatting/style rules from [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md):

- Only one image (<300kb) or GIF (<2.5mb) before the text, with an optional caption and mandatory alt text for accessibility.
- All the rendered text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section (multiple lists are allowed if your project consists of multiple parts that aren't independent enough for their own sections).
- Third-person perspective.
- 80 characters per line and no other markdownlint warnings on CI.

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is a list of our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhastive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

- [x] Rust GameDev Meetup ([1](https://twitter.com/rust_gamedev/status/1479829866174468100)) - ✔️done by @AngelOnFira
- [ ] Game Updates
    - [x] Veloren - ✔️done by @AngelOnFira
    - [x] Not Snake ([1](https://ramirezmike2.itch.io/not-snake/devlog/333283/retrospective-working-on-new-features)) - ✔️done by @ramirezmike
    - [ ] Molecoole ([1](https://twitter.com/kiss_mrton/status/1477330931199496201)) - 🆓**free** (@Hilku?)
    - [x] Flesh ([1](https://twitter.com/Im_Oab/status/1478266743105544192), [2](https://twitter.com/Im_Oab/status/1486244368394899457), [3](https://twitter.com/Im_Oab/status/1487287387721928705)) - ✔️done by @Im-Oab
    - [ ] Wordlet ([1](https://reddit.com/r/rust/comments/s9kjoh/wordlet_a_commandline_clone_of_wordle)) -  🆓**free** (@scottluptowski?)
    - [x] country-slice ([1](https://github.com/anopara/country-slice), [2](https://twitter.com/anastasiaopara/status/1484843005173510149), [3](https://twitter.com/anastasiaopara/status/1477570256180817924)) - ✔️done by @anopara
    - [x] Hydrofoil Generation Sailing ([1](https://twitter.com/KunosStefano), [2](https://twitter.com/KunosStefano/status/1483762264029208585). [3](https://twitter.com/KunosStefano/status/1478316772109565955), [4]()) - ✔️done by @kunos
    - [ ] BITGUN ([1](https://twitter.com/LogLogGames/status/1481358714170970115), [2](https://twitter.com/LogLogGames/status/1479752293306273792). [3](https://twitter.com/LogLogGames/status/1477595533006938112), [4](https://twitter.com/LogLogGames/status/1484889414568493057)) - 🆓**free** (@darthdeus?)
    - [ ] System Fault ([1](https://www.lightsout.games/news/system-fault-early-access)) - 🆓**free** (@lightsoutgames?)
    - [ ] Lantern ([1](https://qatoqat.itch.io/lantern)) - 🆓**free** (@qatoqat?)
    - [ ] Fish Fight ([1](https://spicylobster.itch.io/fishfight/devlog/332434/fish-fights-past-present-and-future), [2](https://twitter.com/fishfightgame/status/1482642646694871045), [3](https://twitter.com/fishfightgame/status/1483564430176755716), [4](https://reddit.com/r/rust_gamedev/comments/shyyhv/fish_fight_v04_ecs_refactor_launcher_asset_pack)) - 🆓**free** (@erlend-sh?)
    - [ ] Starframe ([1](https://moletrooper.me/blog/starframe-ropes)) - 🆓**free** (moletrooper?)
    - [x] Kataster ([1](https://github.com/Bobox214/Kataster)) - ✔️done by @Bobox214
    - [ ] Cake Thieves ([1](https://play.google.com/store/apps/details?id=com.GeTech.CakeThieves), [2](https://twitter.com/GeTech8/status/1480649960207138816)) - 🆓**free** (@getech8?)
    - [ ] Idu ([1](https://twitter.com/logicsoup/status/1487924659693703169)) - 🆓**free** (@johann2?)
    - [ ] sugarcane ([1](https://gitlab.com/macmv/sugarcane), [2](https://reddit.com/r/rust_gamedev/comments/sdumpo/made_a_minecraft_server_in_rust)) - 🆓**free** (@macmv?)
- [ ] Learning Material Updates
    - [x] Making Game Go Fast on Windows ([1](https://reddit.com/r/rust_gamedev/comments/s393sx/making_your_game_go_fast_by_asking_windows_nicely)) - ✔️done by @MasonRemaley
    - [ ] How Bevy uses Rust traits for labeling ([1](https://deterministic.space/bevy-labels.html), [2](https://reddit.com/r/rust/comments/s0fg3m/how_bevy_uses_rust_traits_for_labeling)) - 🆓**free** (@killercup?)
    - [x] Refactoring from Legion to Bevy ([1](https://justinryanh.github.io/post/refactoring_from_legion_to_bevy/)) - ✔️done by @justinryanh
    - [x] Extreme Bevy ([1](https://johanhelsing.studio/posts/extreme-bevy)) - ✔️done by @johanhelsing
    - [ ] Writing a Tiny Rust Game Engine for Web ([1](https://ianjk.com/game-engine-in-rust/)) - 🆓**free** (@kettle11?)
    - [ ] Extending states in Bevy ([1](https://doomy.org/blog/extending-states-in-bevy)) - 🆓**free**
    - [x] writing an AH Scanner in Rust ([1](https://medium.com/digitalfrontiers/taking-rust-for-a-ride-to-azeroth-what-writing-an-ah-scanner-in-rust-taught-me-58edc936cbb)) - ✔️done by @AngelOnFira 
    - [ ] maz.digital's bevy articles ([1](https://maz.digital/mastering-plugin-loadings-bevy-part-12), [2](https://maz.digital/mastering-plugin-loadings-bevy-part-22), [3](https://maz.digital/bevy-stages-or-the-frames-lifecycle)) - 🆓**free** (@RomainMazB?)
- [ ] Engine Updates
    - [x] godot-rust ([1](https://twitter.com/GodotRust/status/1477246477365874692), [2](https://twitter.com/GodotRust/status/1482754475483926531)) - ✔️done by @Bromeon
    - [x] tetra ([1](https://twitter.com/17cupsofcoffee/status/1479584472702062594), [2](https://twitter.com/tesselode/status/1479520056740614146), [3](https://www.seventeencups.net/posts/three-years-of-tetra)) - ✔️done by @17cupsofcoffee
    - [ ] fyrox/rg3d ([1](https://rg3d.rs/general/2022/01/07/0.24-feature-highlights.html)) - 🆓**free** (@mrdimas?)
    - [x] Rusty Engine v0.3 and v0.4 ([1](https://reddit.com/r/rust/comments/rwyrqx/rusty_engine_3), [2](https://reddit.com/r/rust_gamedev/comments/sg2cdg/rusty_engine_4), [3](https://twitter.com/nathanstocks/status/1487667704118988803)) - ✔️done by @CleanCut
    - [ ] Arcana ([1](https://reddit.com/r/rust_gamedev/comments/sdv86z/reducing_boilerplate_in_game_code_with_arcana)) - 🆓**free** (@zakarumych?)
    - [x] bevy v0.6 ([1](https://bevyengine.org/news/bevy-0-6), [2](https://reddit.com/r/rust/comments/rz612l/bevy_06)) - ✔️done by @cart
    - [x] three-d  v0.10 ([1](https://github.com/asny/three-d), [2](https://twitter.com/AsgerNyman/status/1482711259673944067)) - ✔️done by @asny
- [ ] Tooling Updates
    - [ ] Fun Notation 0.5 ([1](https://reddit.com/r/rust_gamedev/comments/sfdl5s/fun_notation_guitar_tab_viewer)) - 🆓**free** (@yjpark?)
    - [ ] gbrs ([1](https://github.com/adamsoutar/gbrs), [2](https://twitter.com/Adam_Soutar/status/1477801421143781381)) - 🆓**free** (@adamsoutar?)
    - [x] nodus ([1](https://github.com/r4gus/nodus)) - ✔️done by @r4gus
- [ ] Library Updates
    - [ ] dimforge ([1](https://twitter.com/dimforge/status/1477706034252849155), [2](https://reddit.com/r/rust/comments/rufetx/the_year_2021_in_dimforge), [3](https://reddit.com/r/rust_gamedev/comments/ruffnw/the_year_2021_in_dimforge)) - 🆓**free** (@sebcrozet?)
    - [ ] EmbarkStudios/poll-promise ([1](https://github.com/EmbarkStudios/poll-promise)) - 🆓**free** (@emilk?)
    - [ ] ezinput ([1](https://twitter.com/eexsty/status/1485942270981464065), [2](http://github.com/eexsty/ezinput)) - 🆓**free** (@eexsty?)
    - [x] bevy_backroll v0.3 ([1](https://reddit.com/r/rust/comments/s6uch9/bevy_backroll_v030_is_now_available)) - ✔️done by @james7132
    - [ ] bevy_asset_loader 0.7 and 0.8 ([1](https://crates.io/crates/bevy_asset_loader)) - 🆓**free** (@NiklasEi?)
    - [x] edict ([1](https://github.com/zakarumych/edict), [2](https://twitter.com/zakarum4/status/1483530416371998722), [3](https://reddit.com/r/rust_gamedev/comments/sbyvz8/edict_v005_experimental_ecs)) - ✔️done by @zakarumych
    - [ ] bevy_game_template ([1](https://github.com/NiklasEi/bevy_game_template), [2](https://twitter.com/nikl_me/status/1480862465265123329), [3](https://twitter.com/nikl_me/status/1481671889412108292)) - 🆓**free** (@NiklasEi?)
    - [x] bevy_smud ([1](https://github.com/johanhelsing/bevy_smud)) - ✔️done by @johanhelsing
    - [x] ~~PetitSet ([1](https://github.com/leafwing-studios/petitset))~~ *author asked to leave it out*
    - [ ] big-brain v0.10 ([1](https://github.com/zkat/big-brain/releases/tag/v0.10.0)) - 🆓**free** (@zkat?)
- [x] Discussions ([1](https://reddit.com/r/rust/comments/ru86vu/rust_alternative_for_pygame)) - ✔️done by @17cupsofcoffee 
- [x] Jobs
    - [x] Gameplay Engineer (Rust) - Creative Play - Embark Studios ([1](https://careers.embark-studios.com/jobs/947916-gameplay-engineer-rust-creative-play)) ✔- ️done by @17cupsofcoffee 

Final steps:

- [x] Other News - by @17cupsofcoffee
- [x] Final review - by everyone
- [x] Publish - by @17cupsofcoffee
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @17cupsofcoffee
- [x] Add comment links - by @17cupsofcoffee
- [x] Add a draft of the n31 - by @17cupsofcoffee

**Comment by Friz64** [comment]
I'd like to write about my [erupt-bootstrap](https://gitlab.com/Friz64/erupt-bootstrap) Vulkan init library.

**Comment by Bombfuse** [comment]
Missed last month, but I can do an update on the release of Harvest Hero Origins! 👍

**Comment by CleanCut** [comment]
I'll do the section for Rusty Engine 4.0.

One observation about the top comment: `The soft deadline for all section PRs is the 8th of Jan.` -> a deadline in the future would probably be more effective. 😉

**Comment by 17cupsofcoffee** [comment]
> One observation about the top comment: `The soft deadline for all section PRs is the 8th of Jan.` -> a deadline in the future would probably be more effective. 😉

you saw nothing 🥷 

(thanks for the heads up!)

**Comment by kunos** [comment]
Will do Hydrofoil Generation.

**Comment by JustinRyanH** [comment]
Will do Refactoring from Legion to Bevy

**Comment by Bromeon** [comment]
Wrote **godot-rust** 🤖🦀

**Comment by cart** [comment]
I'll take bevy!

**Comment by james7132** [comment]
I'll take bevy_backroll!

**Comment by r4gus** [comment]
I'll take nodus

**Comment by CleanCut** [comment]
Rusty Engine 4.0 done in https://github.com/rust-gamedev/rust-gamedev.github.io/pull/914

**Comment by ramirezmike** [comment]
I'll write about Not Snake!

**Comment by Im-Oab** [comment]
I added the current development status of `Flesh`. #916

**Comment by alice-i-cecile** [comment]
I'm not sure petitset is worth including right now; it's extremely specialized and only incidentally related to gamedev. I'll do a write-up for leafwing-input-manager though.

**Comment by eexsty** [comment]
I'd like to write about about my ezinput lib.

**Comment by zakarumych** [comment]
I'll cover Edict

**Comment by AngelOnFira** [comment]
I'll take "writing an AH Scanner in Rust"

**Comment by 17cupsofcoffee** [comment]
⏰ **Reminder: the soft deadline for this month's newsletter is tomorrow!**

If you'd like to write a section, please try to get the PR submitted in the next 24 hours if you can (or let us know if you need more time).

**Comment by johanhelsing** [comment]
@17cupsofcoffee I'll be able to write short entries for bevy_smud and extreme_bevy in a couple of hours if it's not too late.

**Comment by 17cupsofcoffee** [comment]
**The release PR is now up for everyone to review: https://github.com/rust-gamedev/rust-gamedev.github.io/pull/941**

**Comment by Keavon** [comment]
Planning to submit the PR tonight announcing Graphite's imminent alpha release.

**Comment by 17cupsofcoffee** [comment]
@Keavon Sorry, I hit merge on the release PR before seeing this 😩

How soon do you think you'll be able to submit your PR? I can hold off on the announcements if it's coming soon, but I'd really like to get stuff done before it gets too late in my timezone.

**Comment by 17cupsofcoffee** [comment]
I've reverted the release for now.

**Comment by Keavon** [comment]
Ah, sorry to hold you up, didn't mean to cause you trouble. These time zones are hard to think through (it's only 3 PM here in the US-Pacific, on the 8th).

I am working on writing it now so I expect it will take an hour or two (the length limit makes it kinda slow to write). I'll do my best to be quick with it!

**Comment by 17cupsofcoffee** [comment]
@Keavon: No problem - I may have to leave the release till tomorrow in that case, as it's nearly midnight where I am and it'll take me a bit of time to do the social media posts that go with it.
