### ISSUE TITLE
Files are not properly deleted from GitHub Pages

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/rust-gamedev.github.io#945]
I noticed after reverting a change for #912 that when a file is removed from the Zola output, it doesn't get deleted from the `master` branch - this means that the removed content remains accessible on the site.

For example, I reverted the publishing of newsletter 30 to give people more time to submit, but the HTML for it is still accessible if you have a direct link.

This is apparently an issue with the GitHub action we're using to publish: https://github.com/crazy-max/ghaction-github-pages/issues/153

Is there any reason for us to keep `keep_history` set to `true` (the default is `false`)? We have the history for the site on the `source` branch and never directly interact with `master`, so not sure if there's value in having a full history there rather than just having it force pushed every time.

**Comment by ozkriff** [comment]
Originally, I enabled keep_history so it'd be easier to double-check the actual changes in Zola's output (I had a couple of issues with my own blog and early Zola). But it seems like Zola has been behaving well for quite some time now, so I don't mind disabling keep_history.
