### ISSUE TITLE
Newsletter 31 - February 2022

### ISSUE THREAD

**Issue by AngelOnFira** [rust-gamedev/rust-gamedev.github.io#949]
# Newsletter 31: February 2022

###### tags: `newsletter`

**Editors**: @AngelOnFira, @17cupsofcoffee, and @ozkriff

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with February news!

If you want to help writing the newsletter:

- Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
  - The links in brackets (like "1, 2, 3") are suggestions of links to include in the section. Feel free to add more!
  - Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just a suggestion of who could pick the work up - it's not an obligation, and other people are welcome to take those sections.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint (lint errors will fail the CI build).
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Leave a comment or DM me on Discord if you have any issues.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

------

As with the last few newsletters, we're trying to delegate the writing workload where we can - to quote @AngelOnFira from a few months ago:

> We're also going to be transitioning to having authors or volunteers write about their own content, rather than the editing team doing it all at the end 💯 This means if you want to see your work in the newsletter, you have to write it yourself! If you're not able to write about your work, feel free to comment and I can assign it 🆓 free. We're working on taking some of the load off the editing team where we can with this. Best to keep this sustainable!
>
> Also, we want to make sure contributing to the newsletter feels open to anyone who wants to write a section about their project. If you have anything you can write about, just add a comment to this issue and I'll add it to the todo list 😄

------

## Current Schedule

The soft deadline for all section PRs is the **6th of Mar**. PRs will usually be accepted as long as they are ready before the newsletter's release, but the earlier the better :)

------

⚠️ The most important formatting/style rules from [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md):

- Only one image (<300kb) or GIF (<2.5mb) before the text, with an optional caption and mandatory alt text for accessibility.
- All the rendered text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section (multiple lists are allowed if your project consists of multiple parts that aren't independent enough for their own sections).
- Third-person perspective.
- 80 characters per line and no other markdownlint warnings on CI.

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is a list of our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhastive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

- [x] Rust Gamedev Video Showcase Form - ✔️done
- [x] Rust GameDev Meetup - ✔️done
- [x] Game Updates
    - [x] Dom Williams's "name-needed" ([1](https://github.com/DomWilliams0/name-needed), [2](https://domwillia.ms/), [3](https://domwillia.ms/devlog7/)) - ✔️done
    - [x] dis-order ([1](https://twitter.com/jkhelsing/status/1495604656164282374), [2](https://jhelsing.itch.io/dis-order)) - ✔️done
    - [x] Molecoole ([1](https://twitter.com/kiss_mrton/status/1496548484975112196)) - ✔️done
    - [x] Veloren - ✔️done
    - [x] ~~Fish Fight ([1](https://reddit.com/r/rust_gamedev/comments/sokjon/fish_fight_v041_mod_loading), [2](https://twitter.com/orhunp_/status~~/1492467290943770625)) - 🆓**free** (@erlend-sh?)~~
    - [x] ~~vange-rs: emscripten ([1](https://habr.com/en/post/649457/), [2](https://caiiiycuk.medium.com/vangers-3d-example-of-using-emscripten-in-rust-720ee8099d72)) - 🆓**free** (@caiiiycuk?)~~
    - [x] ~~makiomino.fun ([1](http://makiomino.fun), [2](https://twitter.com/makiomino), [3](https://twitter.com/makiomino/status/1496252771909218308)) - 🆓**free**~~
    - [x] ~~country-slice ([1](https://twitter.com/anastasiaopara/status/1492429686294683653)) - 🆓**free** (@anopara?)~~
    - [x] ~~Flesh ([1](https://twitter.com/Im_Oab/status/1490576387589427200)) - 🆓**free** (@Im-Oab?)~~
- [x] Learning Material Updates
    - [x] Bevy Minesweeper Tutorial ([1](https://dev.to/qongzi/bevy-minesweeper-introduction-4l7f), [2](https://twitter.com/ManevilleF/status/1495787155280510977)) - ✔️done
    - [X] Computing image filters with wgpu-rs ([1](https://reddit.com/r/rust/comments/sqwxxn/computing_image_filters_with_wgpurs)) - ✔️done
    - [x] Exporting godot-rust to Android APK on Windows without Android Studio ([1](https://coffeecodechem.com/2022/02/exporting-godot-rust-android-apk-windows/), [2](https://twitter.com/coffeecodechem/status/1492908520249118721)) - ✔️done
    - [x] Actor pattern with async ([1](https://eo-rs.dev/blog/the-actor-pattern-with-async-rust), [2](https://twitter.com/sorokya/status/1495663872275009537)) - ✔️done(@sorokya?)
    - [x] supercharge your web with 3D capabilities by using Rust and Bevy ([1](https://barrage.net/blog/technology/how-to-supercharge-your-web-with-3d-capabilities-by)) - ✔️done
    - [x] ~~Rustenstein 3D: Game programming like it's 1992 ([1](https://tech.nextroll.com/blog/dev/2022/02/02/rustenstein.html)) - 🆓**free** (@facundoolano?)~~
    - [x] ~~Making a 3D Super Munchers Clone with Bevy ([1](https://youtube.com/watch?v=oee3Z69sE-8)) - 🆓**free** (@camsjams?)~~
    - [x] ~~Vulkan with Rust by example ([1](https://nikitablack.github.io/), [2](https://reddit.com/r/rust_gamedev/comments/spvauf/series_of_posts_about_vulkan_usage_with_rust)) @nikitablack?~~
- [x] Engine Updates
    - [x] bevy jam 1 ([1](https://www.reddit.com/r/rust/comments/soxslu/bevy_jam_1/)) - ✔️done
    - [x] dims ([1](https://dims.co), [2](https://twitter.com/jfnoren/status/1491077331850776576), [3](https://reddit.com/r/rust_gamedev/comments/snhi5u/some_months_into)) - ✔️done
    - [x] ~~fyrox/rg3d ([1](https://reddit.com/r/rust_gamedev/comments/sm34s6/media_finally_got_assets_hot_reloading_working_in)) - 🆓**free** (@mrdimas?)~~
    - [x] ~~Hotham VR Engine demo ([1](https://reddit.com/r/rust_gamedev/comments/st4vp1/media_hotham_vr_engine_demo), [2](https://reddit.com/r/rust/comments/ssvbff/media_hotham_vr_engine_demo), [3](https://crates.io/crates/hotham)) - 🆓**free** (@leetvr?)~~
    - [x] ~~godot-rust ([1](https://twitter.com/GodotRust/status/1490282777039753218), [2](https://twitter.com/GodotRust/status/1495904449637896192)) - 🆓**free** (@Bromeon?)~~
- [x] Tooling Updates
    - [x] vismut ([1](https://gitlab.com/vismutorg/vismut)) - ✔️done
    - [x] Blackjack ([1](https://reddit.com/r/rust_gamedev/comments/srgd41/your_rusty_procedural_3d_modeler_blackjack_just), [2](https://reddit.com/r/rust/comments/sfqung/media_blackjacks_eguibased_node_graph_now). [3](https://reddit.com/r/rust_gamedev/comments/swgysq/the_egui_node_graph_behind_blackjack)) - ✔️done
    - [x] Graphite - 🆓**free** (@Keavon?)
    - [x] ~~cosync ([1](https://github.com/sanbox-irl/cosync)) - 🆓**free** (@sanbox-irl?)~~
    - [x] ~~SPIR-Q v0.5 ([1](https://reddit.com/r/rust_gamedev/comments/sr7nnr/spirq_v05_cleaner_api)) - 🆓**free** (@PENGUINLIONG?)~~
- [ ] Library Updates
    - [x] Sparsey 0.7 ([1](https://reddit.com/r/rust_gamedev/comments/svt76p/sparsey_07_release_simplify_and_polish)) - ✔️done
    - [x] vach ([1](https://github.com/zeskeertwee/vach)) - ✔️done
    - [x] notan ([1](https://github.com/Nazariglez/notan), [2](https://reddit.com/r/rust/comments/sxdctc/introducing_notan_a_portable_multimedia_layer)) - ✔️done
    - [x] ~~egui ([1](https://twitter.com/ernerfeldt/status/1491309938169507841), [2](https://twitter.com/ernerfeldt/status/1496200805212475396)) - 🆓**free** (@emilk?)~~
    - [x] ~~sparticles-rs ([1](https://github.com/Norlock/sparticles-rs), [2](https://youtube.com/watch?v=dyxlfOyW90Q)) - 🆓**free** (@Norlock?)~~
    - [x] ~~blender_bevy_toolkit ([1](https://github.com/sdfgeoff/blender_bevy_toolkit), [2](https://reddit.com/r/rust_gamedev/comments/sredt1/blender_bevy_pipeline_progress)) - 🆓**free** (@sdfgeoff?)~~
- [x] Discussions ([1](https://reddit.com/r/bevy/comments/sikrv1/recommended_bevyecs_project_structureconventions), [2](https://reddit.com/r/rust_gamedev/comments/stcnx0/which_is_a_better_game_engine_to_start_with)) - ✔️done
- [x] Jobs
    
Final steps:

- [x] Other News - by @AngelOnFira
- [x] Final review - by everyone
- [x] Publish - by @AngelOnFira
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @AngelOnFira
- [x] Add comment links - by @AngelOnFira
- [ ] Add a draft of the n31 - by @AngelOnFira

**Comment by DomWilliams0** [comment]
I've opened #950 for my game Name Needed

**Comment by Im-Oab** [comment]
I will skip this month. ‘Flesh’ doesn’t have any updates that I can show.

**Comment by Bromeon** [comment]
We will skip godot-rust this time.

**Comment by LechintanTudor** [comment]
I'll take Sparsey

**Comment by cart** [comment]
I'll take Bevy Jam.

**Comment by Hilku** [comment]
I'll take Molecoole

**Comment by lukors** [comment]
When are the soft and/or hard deadlines?

**Comment by AngelOnFira** [comment]
@lukors Just updated the issue details, I've set it to the 6th of March :)

**Comment by AlbinSjoegren** [comment]
> I would like to do SPV again this month but not sure if it goes under tooling or library. It is both in a way, the crate version is currently the main "content" in the project the GUI version is just a basic implementation of that content. It's up to you really.

@AngelOnFira

**Comment by AngelOnFira** [comment]
@AlbinSjoegren let's do tooling, it looks like that's what it was in the past, so it should be good there. The lines are a bit blurred for some projects.

**Comment by Nazariglez** [comment]
I'll take Notan, thanks for the heads up.

**Comment by lukors** [comment]
I'll do Vismut.

**Comment by yeahross0** [comment]
I will have an update for Weegames.

**Comment by anopara** [comment]
Thanks for the mention, but saw it too late and won't have time before end of today :( Will do one for the next month!

**Comment by lukors** [comment]
This issue is not marked with the "coordination" label.

**Comment by Keavon** [comment]
Submitting Graphite in a few hours.

**Comment by sdfgeoff** [comment]
Regarding `blender_bevy_toolkit`, I'd probably like to wait until a future release before writing an article in the newsletter. 

The project is very close to being usable and I'd like the initial presentation in the newsletter to be "Here's the blender bevy toolkit, and here's a small game made with it". I think I'm about a month or so out from that point.

**Comment by Keavon** [comment]
Actually I'll skip Graphite for this month, we've mostly been focused on planning rather than much development.

**Comment by johanhelsing** [comment]
I wrote a small blurb on dis-order, if it's not too late

**Comment by AngelOnFira** [comment]
Alright, I've been quite absent so far this month, but I'll be going over PRs today :+1:

**Comment by zeskeertwee** [comment]
#955 is ready for review now!

**Comment by AngelOnFira** [comment]
There are still lots of sections to take if anyone has time to take some. I'll try to take some tomorrow.

**Comment by sanbox-irl** [comment]
I will take cosync tomorrow!

**Comment by Keavon** [comment]
> Actually I'll skip Graphite for this month, we've mostly been focused on planning rather than much development.

I went ahead and did one for Graphite anyways. #966

**Comment by AngelOnFira** [comment]
Alright, I've gone ahead and added several more sections. Once these have been approved and merged, I'll move forward with the final draft. I'm aiming to get this released within the next 12 hours, but it might end up being tomorrow, we'll see.

**Comment by NiklasEi** [comment]
If still possible I would like to add a short entry about the latest `bevy_asset_loader` update and a related blog post. I will open the PR in a bit. No hard feelings, if I am too late :slightly_smiling_face:

**Comment by AngelOnFira** [comment]
I'm not quite done with some of the bottom sections yet, but everyone is invited to check out #974! Looking at a release tomorrow it seems :100:

**Comment by AngelOnFira** [comment]
Thanks for another great month, everyone! See you next time :)
