### ISSUE TITLE
Newsletter 32 - March 2022

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/rust-gamedev.github.io#979]
**Editors:** @17cupsofcoffee, @AngelOnFira and @ozkriff

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with March's news!

*Note: I'm trialling a slightly updated template for the co-ordination issue this month - let me know if you have any feedback!*

## Current Schedule

**The deadline for all section PRs is the 9th of April.**

We *may* still accept PRs that are submitted later than this, as long as they're ready before the newsletter's release, but this isn't guaranteed. If you want your section to be included, don't leave it till the last minute!

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
    - The links in brackets (like "[1](#), [2](#), [3](#)") are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like "@ozkriff?") is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR *to the `source` branch* (example: #336).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md), but here are the most important rules:

- Write in third-person perspective.
- Each line must be 80 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs! 

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

#### Rust Gamedev Meetup

- [x] Details of this month's meetup - ✔️ done

#### Rust Gamedev Podcast

- [x] A/B Street Interview ([1](https://rustgamedev.com/episodes/interview-with-dustin-a-b-street)) - ✔️ done

#### Game Updates

- [x] Bevy Jam results ([1](https://itch.io/jam/bevy-jam-1/results)) - ✔️ done
    - [x] Petty Party ([1](https://github.com/jabuwu/petty-party), [2](https://jabuwu.itch.io/petty-party)) - ✔️ done
    - [x] ¿Quién es el Mechaburro? ([1](https://ramirezmike2.itch.io/quien-es-el-mechaburro), [2](https://github.com/ramirezmike/quien_es_el_mechaburro)) - ✔️ done
    - [x] Chaz ([1](https://luizchagasjardim.itch.io/chaz)) - ✔️ done
    - [x] Warlock's Gambit ([1](https://gibonus.itch.io/warlocks-gambit), [2](https://github.com/team-plover/warlocks-gambit)) - ✔️ done
    - [x] Cheaters Never Win ([1](https://cdsupina.itch.io/cheaters-never-win), [2](https://github.com/TheRealTeamFReSh/Cheaters-Never-Win)) - ✔️ done
    - *I've tagged the top 5 as a starting point, but feel free to contribute if you also entered the jam!*
- [x] Harvest Hero Origins ([1](https://twitter.com/GemdropGames/status/1505268850304106497)) - ✔️ done
- [ ] Space Frontiers ([1](https://www.youtube.com/watch?v=EF5iUJNFz94), [2](https://github.com/starwolves/space)) - 🆓 **free** (@starwolves?)
- [x] rust-nonogram ([1](https://github.com/henryksloan/rust-nonogram)) - ✔️ done
- [x] V-Racer ([1](https://github.com/Syn-Nine/rust-mini-games/tree/main/2d-games/vracer), [2](https://twitter.com/Syn9Dev/status/1507751510859563016)) - ✔️ done
- [x] terrain_generator ([1](https://ianjk.com/terrain_generator/)) - ✔️ done
- [x] Veloren ([1](https://veloren.net/devblog-164/))  - ✔️ done

#### Learning Material Updates

- [ ] Making One Game Per Week ([1](https://www.youtube.com/watch?v=qufQVtlYqrQ)) - 🆓 **free** (*couldn't find username - let me know if this is your project!*)

#### Engine Updates

- [x] godot-rust 0.10 ([1](https://github.com/godot-rust/godot-rust/blob/master/CHANGELOG.md)) - ✔️ done
- [x] notan ([1](https://github.com/Nazariglez/notan)) - ✔️ done
- [x] Tetra 0.7 ([1](https://github.com/17cupsofcoffee/tetra/blob/main/CHANGELOG.md)) - ✔️ done

#### Tooling Updates

- [x] Noumenal ([1](https://noumenal.app/)) - ✔️ done
- [x] Bloom3D ([1](https://bloom3d.com/)) - ✔️ done

#### Library Updates

- [x] dos-like-rs ([1](https://github.com/Enet4/dos-like-rs)) - ✔️ done
- [x] kira 0.6 ([1](https://github.com/tesselode/kira/releases/tag/v0.6.0)) - ✔️ done
- [x] bevy_match3 ([1](https://crates.io/crates/bevy_match3), [2](https://github.com/Sheepyhead/bevy_match3)) - ✔️ done

#### Other News

- [x] Bullet points of any interesting news that doesn't have its own section - 🆓 **free** (@17cupsofcoffee?)

#### Discussions

- [x] Details of any gamedev-related discussion threads - 🆓 **free** (@17cupsofcoffee?)

#### Jobs

- [x] Embark Studios (Stockholm/Hybrid Remote) - Various roles ([1](https://careers.embark-studios.com/jobs))
- [x] Dims (Stockholm/Remote) - Various roles ([1](https://www.dims.co/jobs))
    
## Publishing Steps

- [x] Final review - by everyone
- [x] Publish - by @17cupsofcoffee
- [x] Post on /r/rust, /r/rust\_gamedev, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @17cupsofcoffee 
- [ ] Pin thread on Twitter - by @ozkriff
- [x] Add comment links - by @17cupsofcoffee 
- [x] Add a draft of next month's newsletter - by @17cupsofcoffee

**Comment by kettle11** [comment]
I'll take `terrain_generator` and `Bloom3D`. 

A question: How do people usually edit their submissions? Using GitHub's markdown editor is nice and easy but there's no way to check the line-width (right? which makes it a bit of a pain. Do most people `Clone` and use a code-editor that automatically wraps based on a configurable line-width?

**Comment by 17cupsofcoffee** [comment]
@kettle11 - I agree it's mega awkward that GitHub doesn't expose this 😢 

I generally just open a new file in VS Code, write my section there and then copy and paste it into the web editor.

**Comment by henryksloan** [comment]
I'll take rust-nonogram.

**Comment by nicopap** [comment]
I'd be more than happy to take the Warlock's Gambit section.

**Comment by Enet4** [comment]
> dos-like-rs ([1](https://github.com/Enet4/dos-like-rs)) - free (@Enet4?)

Yup, I'm on it.

**Comment by HackerFoo** [comment]
> Noumenal ([1](https://noumenal.app/)) - 🆓 free (@HackerFoo?)

I'll do this section, thanks.

**Comment by Sheepyhead** [comment]
I'd like to write about my bevy_match3 library, thanks for the opportunity!

**Comment by Bombfuse** [comment]
will take HHO 👍

**Comment by ramirezmike** [comment]
I'll write about Mechaburro

**Comment by 17cupsofcoffee** [comment]
I've pushed the deadline back to the 9th as I don't think I'll have time to properly review/write sections until the weekend.

**Comment by AngelOnFira** [comment]
Working on Veloren + Meetup + Podcast now :+1:

**Comment by AngelOnFira** [comment]
Working on "Intro to Bevy Video Tutorial Series" from Reddit

**Comment by Nazariglez** [comment]
Notan done, thanks for the heads up!

**Comment by 17cupsofcoffee** [comment]
**⏰ Reminder that today is the deadline for sections!** I'm probably going to aim to get everything merged tonight, and then do the final review/release tomorrow.

I'm going to pick up the Tetra sections and the rest of the Bevy Jam section.

**Comment by Keavon** [comment]
Working on Graphite today.

**Comment by cdsupina** [comment]
Working on cheaters never win today.

**Comment by 17cupsofcoffee** [comment]
@cdsupina: I just merged a section for all the Bevy Jam games, but please feel free to extend it/tweak it!

**Comment by nxsy** [comment]
@17cupsofcoffee, @AngelOnFira and @ozkriff

Any objection to me submitting a pull request to add this analysis of the Bevy Jam entries I did with the Bevy Jam results section: https://techgeneral.org/bevy-jam-1-data-exploration/

**Comment by MasonRemaley** [comment]
If it's not too late I'll have an update on Way of Rhea in ~30 minutes, sorry for doing it last minute! :)

**Comment by 17cupsofcoffee** [comment]
All of the outstanding sections PRs have merged now - will try to get the Other News section + remaining jobs done this evening, then will raise the final review PR.

**Comment by cart** [comment]
Thanks for picking up the Bevy Jam section @17cupsofcoffee! Things have been hectic lately (both on the bevy side and the life side).
